libcryptosec Documentation
SubjectKeyIdentifierExtension Class Reference
#include <SubjectKeyIdentifierExtension.h>
Public Member Functions
SubjectKeyIdentifierExtension ()
SubjectKeyIdentifierExtension (X509_EXTENSION *ext) throw (CertificationException)
virtual ~SubjectKeyIdentifierExtension ()
std::string getXmlEncoded ()
std::string getXmlEncoded (std::string tab)
virtual std::string extValue2Xml (std::string tab="")
void setKeyIdentifier (ByteArray keyIdentifier)
ByteArray getKeyIdentifier () const
X509_EXTENSION * getX509Extension ()
Public Member Functions inherited from Extension
Extension (X509_EXTENSION *ext) throw (CertificationException)
Extension (std::string oid, bool critical, std::string valueBase64) throw (CertificationException)
virtual ~Extension ()
std::string toXml (std::string tab="") throw (CertificationException)
ObjectIdentifier getObjectIdentifier () const
std::string getName ()
Extension::Name getTypeName ()
ByteArray getValue () const
std::string getBase64Value ()
void setCritical (bool critical)
bool isCritical () const
Protected Attributes
ByteArray keyIdentifier
Protected Attributes inherited from Extension
ObjectIdentifier objectIdentifier
bool critical
ByteArray value
Additional Inherited Members
Public Types inherited from Extension
enum Name {
UNKNOWN, KEY_USAGE, EXTENDED_KEY_USAGE, AUTHORITY_KEY_IDENTIFIER,
CRL_DISTRIBUTION_POINTS, AUTHORITY_INFORMATION_ACCESS, BASIC_CONSTRAINTS, CERTIFICATE_POLICIES,
ISSUER_ALTERNATIVE_NAME, SUBJECT_ALTERNATIVE_NAME, SUBJECT_INFORMATION_ACCESS, SUBJECT_KEY_IDENTIFIER,
CRL_NUMBER, DELTA_CRL_INDICATOR
}
Static Public Member Functions inherited from Extension
static Extension::Name getName (int nid)
static Extension::Name getName (X509_EXTENSION *ext)
Protected Member Functions inherited from Extension
Extension ()
Constructor & Destructor Documentation
SubjectKeyIdentifierExtension() [1/2]
SubjectKeyIdentifierExtension::SubjectKeyIdentifierExtension ()
References ObjectIdentifierFactory::getObjectIdentifier(), and Extension::objectIdentifier.
SubjectKeyIdentifierExtension() [2/2]
SubjectKeyIdentifierExtension::SubjectKeyIdentifierExtension (X509_EXTENSION * ext) throw (CertificationException)
References CertificationException::INVALID_TYPE, and keyIdentifier.
~SubjectKeyIdentifierExtension()
SubjectKeyIdentifierExtension::~SubjectKeyIdentifierExtension () virtual
Member Function Documentation
extValue2Xml()
std::string SubjectKeyIdentifierExtension::extValue2Xml (std::string tab = "") virtual
Reimplemented from Extension.
References Base64::encode(), and getKeyIdentifier().
getKeyIdentifier()
ByteArray SubjectKeyIdentifierExtension::getKeyIdentifier () const
References keyIdentifier.
Referenced by extValue2Xml(), and getXmlEncoded().
getX509Extension()
X509_EXTENSION * SubjectKeyIdentifierExtension::getX509Extension () virtual
Reimplemented from Extension.
References Extension::critical, ByteArray::getDataPointer(), keyIdentifier, and ByteArray::size().
getXmlEncoded() [1/2]
std::string SubjectKeyIdentifierExtension::getXmlEncoded () virtual
Deprecated:
Retorna o conteudo da extensão em formato XML.
Esta função será substituida por toXml().
Reimplemented from Extension.
getXmlEncoded() [2/2]
std::string SubjectKeyIdentifierExtension::getXmlEncoded (std::string tab) virtual
Reimplemented from Extension.
References Base64::encode(), getKeyIdentifier(), Extension::getName(), and Extension::isCritical().
setKeyIdentifier()
void SubjectKeyIdentifierExtension::setKeyIdentifier (ByteArray keyIdentifier)
References keyIdentifier.
Member Data Documentation
keyIdentifier
ByteArray SubjectKeyIdentifierExtension::keyIdentifier protected
Referenced by getKeyIdentifier(), getX509Extension(), setKeyIdentifier(), and SubjectKeyIdentifierExtension().
The documentation for this class was generated from the following files:
include/libcryptosec/certificate/SubjectKeyIdentifierExtension.h
src/certificate/SubjectKeyIdentifierExtension.cpp