libcryptosec Documentation
CertificateRevocationListBuilder Class Reference
#include <CertificateRevocationListBuilder.h>
Public Member Functions
CertificateRevocationListBuilder ()
CertificateRevocationListBuilder (std::string pemEncoded) throw (EncodeException)
CertificateRevocationListBuilder (ByteArray &derEncoded) throw (EncodeException)
CertificateRevocationListBuilder (const CertificateRevocationListBuilder &crl)
virtual ~CertificateRevocationListBuilder ()
std::string getXmlEncoded ()
std::string getXmlEncoded (std::string tab)
void setSerialNumber (long serial) throw (CertificationException)
void setSerialNumber (BigInteger serial) throw (CertificationException, BigIntegerException)
Definir serial à partir de BigInteger, para seriais maiores do que um "long".
long getSerialNumber () throw (CertificationException)
BigInteger getSerialNumberBigInt () throw (CertificationException, BigIntegerException)
void setVersion (long version)
long getVersion () throw (CertificationException)
void setIssuer (RDNSequence &issuer) throw (CertificationException)
void setIssuer (X509 *issuer) throw (CertificationException)
RDNSequence getIssuer ()
void setLastUpdate (DateTime &dateTime)
DateTime getLastUpdate ()
void setNextUpdate (DateTime &dateTime)
DateTime getNextUpdate ()
void addRevokedCertificate (RevokedCertificate &revoked) throw (CertificationException)
void addRevokedCertificates (std::vector< RevokedCertificate > &revoked) throw (CertificationException)
std::vector< RevokedCertificate > getRevokedCertificate ()
CertificateRevocationList * sign (PrivateKey &privateKey, MessageDigest::Algorithm messageDigestAlgorithm) throw (CertificationException)
X509_CRL * getX509Crl () const
CertificateRevocationListBuilder & operator= (const CertificateRevocationListBuilder &value)
void addExtension (Extension &extension) throw (CertificationException)
Martin: 14/09/07.
void addExtensions (std::vector< Extension *> &extensions) throw (CertificationException)
Martin: 14/09/07.
void replaceExtension (Extension &extension) throw (CertificationException)
std::vector< Extension * > getExtension (Extension::Name extensionName)
std::vector< Extension * > getExtensions ()
std::vector< Extension * > getUnknownExtensions ()
Protected Attributes
X509_CRL * crl
Constructor & Destructor Documentation
CertificateRevocationListBuilder() [1/4]
CertificateRevocationListBuilder::CertificateRevocationListBuilder ()
References crl, setLastUpdate(), and setNextUpdate().
CertificateRevocationListBuilder() [2/4]
CertificateRevocationListBuilder::CertificateRevocationListBuilder (std::string pemEncoded) throw (EncodeException)
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_WRITING, crl, and EncodeException::PEM_DECODE.
CertificateRevocationListBuilder() [3/4]
CertificateRevocationListBuilder::CertificateRevocationListBuilder (ByteArray & derEncoded) throw (EncodeException)
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_WRITING, crl, and EncodeException::DER_DECODE.
CertificateRevocationListBuilder() [4/4]
CertificateRevocationListBuilder::CertificateRevocationListBuilder (const CertificateRevocationListBuilder & crl)
References getX509Crl().
~CertificateRevocationListBuilder()
CertificateRevocationListBuilder::~CertificateRevocationListBuilder () virtual
References crl.
Member Function Documentation
addExtension()
void CertificateRevocationListBuilder::addExtension (Extension & extension) throw (CertificationException)
Martin: 14/09/07.
References CertificationException::ADDING_EXTENSION, and crl.
Referenced by addExtensions(), and replaceExtension().
addExtensions()
void CertificateRevocationListBuilder::addExtensions (std::vector< Extension *> & extensions) throw (CertificationException)
Martin: 14/09/07.
References addExtension().
addRevokedCertificate()
void CertificateRevocationListBuilder::addRevokedCertificate (RevokedCertificate & revoked) throw (CertificationException)
References crl, and CertificationException::INTERNAL_ERROR.
addRevokedCertificates()
void CertificateRevocationListBuilder::addRevokedCertificates (std::vector< RevokedCertificate > & revoked) throw (CertificationException)
References crl, and CertificationException::INTERNAL_ERROR.
getExtension()
std::vector< Extension * > CertificateRevocationListBuilder::getExtension (Extension::Name extensionName)
References Extension::AUTHORITY_INFORMATION_ACCESS, Extension::AUTHORITY_KEY_IDENTIFIER, Extension::BASIC_CONSTRAINTS, Extension::CERTIFICATE_POLICIES, crl, Extension::CRL_DISTRIBUTION_POINTS, Extension::CRL_NUMBER, Extension::DELTA_CRL_INDICATOR, Extension::EXTENDED_KEY_USAGE, Extension::getName(), Extension::ISSUER_ALTERNATIVE_NAME, Extension::KEY_USAGE, Extension::SUBJECT_ALTERNATIVE_NAME, Extension::SUBJECT_INFORMATION_ACCESS, and Extension::SUBJECT_KEY_IDENTIFIER.
getExtensions()
std::vector< Extension * > CertificateRevocationListBuilder::getExtensions ()
References Extension::AUTHORITY_INFORMATION_ACCESS, Extension::AUTHORITY_KEY_IDENTIFIER, Extension::BASIC_CONSTRAINTS, Extension::CERTIFICATE_POLICIES, crl, Extension::CRL_DISTRIBUTION_POINTS, Extension::CRL_NUMBER, Extension::DELTA_CRL_INDICATOR, Extension::EXTENDED_KEY_USAGE, Extension::getName(), Extension::ISSUER_ALTERNATIVE_NAME, Extension::KEY_USAGE, Extension::SUBJECT_ALTERNATIVE_NAME, Extension::SUBJECT_INFORMATION_ACCESS, and Extension::SUBJECT_KEY_IDENTIFIER.
getIssuer()
RDNSequence CertificateRevocationListBuilder::getIssuer ()
References crl.
Referenced by getXmlEncoded().
getLastUpdate()
DateTime CertificateRevocationListBuilder::getLastUpdate ()
References crl.
Referenced by getXmlEncoded().
getNextUpdate()
DateTime CertificateRevocationListBuilder::getNextUpdate ()
References crl.
Referenced by getXmlEncoded().
getRevokedCertificate()
std::vector< RevokedCertificate > CertificateRevocationListBuilder::getRevokedCertificate ()
References crl.
Referenced by getXmlEncoded().
getSerialNumber()
long CertificateRevocationListBuilder::getSerialNumber () throw (CertificationException)
References crl, CertificationException::INTERNAL_ERROR, CertificationException::INVALID_CRL, and CertificationException::SET_NO_VALUE.
Referenced by getXmlEncoded().
getSerialNumberBigInt()
BigInteger CertificateRevocationListBuilder::getSerialNumberBigInt () throw (CertificationException, BigIntegerException)
References crl, CertificationException::INTERNAL_ERROR, CertificationException::INVALID_CRL, and CertificationException::SET_NO_VALUE.
getUnknownExtensions()
std::vector< Extension * > CertificateRevocationListBuilder::getUnknownExtensions ()
References crl, Extension::getName(), and Extension::UNKNOWN.
getVersion()
long CertificateRevocationListBuilder::getVersion () throw (CertificationException)
References crl, CertificationException::INVALID_CRL, and CertificationException::SET_NO_VALUE.
Referenced by getXmlEncoded().
getX509Crl()
X509_CRL * CertificateRevocationListBuilder::getX509Crl () const
References crl.
Referenced by CertificateRevocationListBuilder(), and operator=().
getXmlEncoded() [1/2]
std::string CertificateRevocationListBuilder::getXmlEncoded ()
Referenced by getXmlEncoded().
getXmlEncoded() [2/2]
std::string CertificateRevocationListBuilder::getXmlEncoded (std::string tab)
References getIssuer(), getLastUpdate(), getNextUpdate(), getRevokedCertificate(), getSerialNumber(), getVersion(), getXmlEncoded(), and DateTime::getXmlEncoded().
operator=()
CertificateRevocationListBuilder & CertificateRevocationListBuilder::operator= (const CertificateRevocationListBuilder & value)
References crl, and getX509Crl().
replaceExtension()
void CertificateRevocationListBuilder::replaceExtension (Extension & extension) throw (CertificationException)
References addExtension(), and crl.
setIssuer() [1/2]
void CertificateRevocationListBuilder::setIssuer (RDNSequence & issuer) throw (CertificationException)
References crl, and CertificationException::INTERNAL_ERROR.
setIssuer() [2/2]
void CertificateRevocationListBuilder::setIssuer (X509 * issuer) throw (CertificationException)
References crl, and CertificationException::INTERNAL_ERROR.
setLastUpdate()
void CertificateRevocationListBuilder::setLastUpdate (DateTime & dateTime)
References crl, and DateTime::getUTCTime().
Referenced by CertificateRevocationListBuilder(), and sign().
setNextUpdate()
void CertificateRevocationListBuilder::setNextUpdate (DateTime & dateTime)
References crl, and DateTime::getAsn1Time().
Referenced by CertificateRevocationListBuilder(), and sign().
setSerialNumber() [1/2]
void CertificateRevocationListBuilder::setSerialNumber (long serial) throw (CertificationException)
References crl, and CertificationException::INTERNAL_ERROR.
setSerialNumber() [2/2]
void CertificateRevocationListBuilder::setSerialNumber (BigInteger serial) throw (CertificationException, BigIntegerException)
Definir serial à partir de BigInteger, para seriais maiores do que um "long".
References crl, and CertificationException::INTERNAL_ERROR.
setVersion()
void CertificateRevocationListBuilder::setVersion (long version)
References crl.
Referenced by sign().
sign()
CertificateRevocationList * CertificateRevocationListBuilder::sign (PrivateKey & privateKey, MessageDigest::Algorithm messageDigestAlgorithm) throw (CertificationException)
References crl, MessageDigest::getMessageDigest(), CertificationException::INTERNAL_ERROR, setLastUpdate(), setNextUpdate(), and setVersion().
Member Data Documentation
crl
X509_CRL* CertificateRevocationListBuilder::crl protected
Referenced by addExtension(), addRevokedCertificate(), addRevokedCertificates(), CertificateRevocationListBuilder(), getExtension(), getExtensions(), getIssuer(), getLastUpdate(), getNextUpdate(), getRevokedCertificate(), getSerialNumber(), getSerialNumberBigInt(), getUnknownExtensions(), getVersion(), getX509Crl(), operator=(), replaceExtension(), setIssuer(), setLastUpdate(), setNextUpdate(), setSerialNumber(), setVersion(), sign(), and ~CertificateRevocationListBuilder().
The documentation for this class was generated from the following files:
include/libcryptosec/certificate/CertificateRevocationListBuilder.h
src/certificate/CertificateRevocationListBuilder.cpp