libcryptosec Documentation
Pkcs7Exception Class Reference
#include <Pkcs7Exception.h>
Public Types
enum ErrorCode {
UNKNOWN, INVALID_PKCS7, INVALID_TYPE, DECRYPTING,
INTERNAL_ERROR, INVALID_SYMMETRIC_CIPHER, INVALID_CERTIFICATE, ADDING_SIGNER,
ADDING_CERTIFICATE
}
Public Member Functions
Pkcs7Exception (std::string where)
Pkcs7Exception (Pkcs7Exception::ErrorCode errorCode, std::string where)
Pkcs7Exception (Pkcs7Exception::ErrorCode errorCode, std::string where, bool opensslDetails)
virtual ~Pkcs7Exception () throw ()
virtual std::string getMessage () const
virtual std::string toString () const
virtual Pkcs7Exception::ErrorCode getErrorCode ()
Public Member Functions inherited from LibCryptoSecException
virtual ~LibCryptoSecException () throw ()
virtual const char * what () const throw ()
virtual const std::string getDetails () const throw ()
Static Public Member Functions
static std::string errorCode2Message (Pkcs7Exception::ErrorCode errorCode)
Protected Attributes
Pkcs7Exception::ErrorCode errorCode
Protected Attributes inherited from LibCryptoSecException
std::string where
std::string details
Member Enumeration Documentation
ErrorCode
enum Pkcs7Exception::ErrorCode
Enumerator
UNKNOWN
INVALID_PKCS7
INVALID_TYPE
DECRYPTING
INTERNAL_ERROR
INVALID_SYMMETRIC_CIPHER
INVALID_CERTIFICATE
ADDING_SIGNER
ADDING_CERTIFICATE
Constructor & Destructor Documentation
Pkcs7Exception() [1/3]
Pkcs7Exception::Pkcs7Exception (std::string where) inline
References errorCode, UNKNOWN, and LibCryptoSecException::where.
Pkcs7Exception() [2/3]
Pkcs7Exception::Pkcs7Exception (Pkcs7Exception::ErrorCode errorCode, std::string where) inline
References errorCode, and LibCryptoSecException::where.
Pkcs7Exception() [3/3]
Pkcs7Exception::Pkcs7Exception (Pkcs7Exception::ErrorCode errorCode, std::string where, bool opensslDetails) inline
References LibCryptoSecException::details, errorCode, OpenSSLErrorHandler::getErrors(), and LibCryptoSecException::where.
~Pkcs7Exception()
virtual Pkcs7Exception::~Pkcs7Exception () throw () inline virtual
Member Function Documentation
errorCode2Message()
static std::string Pkcs7Exception::errorCode2Message (Pkcs7Exception::ErrorCode errorCode) inline static
References ADDING_CERTIFICATE, ADDING_SIGNER, DECRYPTING, INTERNAL_ERROR, INVALID_CERTIFICATE, INVALID_PKCS7, INVALID_SYMMETRIC_CIPHER, INVALID_TYPE, and UNKNOWN.
Referenced by getMessage(), and toString().
getErrorCode()
virtual Pkcs7Exception::ErrorCode Pkcs7Exception::getErrorCode () inline virtual
References errorCode.
getMessage()
virtual std::string Pkcs7Exception::getMessage () const inline virtual
Implements LibCryptoSecException.
References errorCode, and errorCode2Message().
toString()
virtual std::string Pkcs7Exception::toString () const inline virtual
Implements LibCryptoSecException.
References LibCryptoSecException::details, errorCode, errorCode2Message(), UNKNOWN, and LibCryptoSecException::where.
Member Data Documentation
errorCode
Pkcs7Exception::ErrorCode Pkcs7Exception::errorCode protected
Referenced by getErrorCode(), getMessage(), Pkcs7Exception(), and toString().
The documentation for this class was generated from the following file:
include/libcryptosec/exception/Pkcs7Exception.h