libcryptosec Documentation
CertificateRevocationList Class Reference
#include <CertificateRevocationList.h>
Public Member Functions
CertificateRevocationList (X509_CRL *crl)
CertificateRevocationList (std::string pemEncoded) throw (EncodeException)
CertificateRevocationList (ByteArray &derEncoded) throw (EncodeException)
CertificateRevocationList (const CertificateRevocationList &crl)
virtual ~CertificateRevocationList ()
std::string getXmlEncoded ()
std::string getXmlEncoded (std::string tab)
std::string getPemEncoded () throw (EncodeException)
ByteArray getDerEncoded () throw (EncodeException)
long getSerialNumber () throw (CertificationException)
BigInteger getSerialNumberBigInt () throw (CertificationException, BigIntegerException)
long getBaseCRLNumber () throw (CertificationException)
BigInteger getBaseCRLNumberBigInt () throw (CertificationException, BigIntegerException)
long getVersion () throw (CertificationException)
RDNSequence getIssuer ()
DateTime getLastUpdate ()
DateTime getNextUpdate ()
std::vector< RevokedCertificate > getRevokedCertificate ()
bool verify (PublicKey &publicKey)
X509_CRL * getX509Crl () const
CertificateRevocationList & operator= (const CertificateRevocationList &value)
std::vector< Extension * > getExtension (Extension::Name extensionName)
std::vector< Extension * > getExtensions ()
std::vector< Extension * > getUnknownExtensions ()
Protected Attributes
X509_CRL * crl
Constructor & Destructor Documentation
CertificateRevocationList() [1/4]
CertificateRevocationList::CertificateRevocationList (X509_CRL * crl)
References crl.
CertificateRevocationList() [2/4]
CertificateRevocationList::CertificateRevocationList (std::string pemEncoded) throw (EncodeException)
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_WRITING, crl, and EncodeException::PEM_DECODE.
CertificateRevocationList() [3/4]
CertificateRevocationList::CertificateRevocationList (ByteArray & derEncoded) throw (EncodeException)
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_WRITING, crl, and EncodeException::DER_DECODE.
CertificateRevocationList() [4/4]
CertificateRevocationList::CertificateRevocationList (const CertificateRevocationList & crl)
References getX509Crl().
~CertificateRevocationList()
CertificateRevocationList::~CertificateRevocationList () virtual
References crl.
Member Function Documentation
getBaseCRLNumber()
long CertificateRevocationList::getBaseCRLNumber () throw (CertificationException)
References crl, CertificationException::INTERNAL_ERROR, CertificationException::INVALID_CRL, and CertificationException::SET_NO_VALUE.
getBaseCRLNumberBigInt()
BigInteger CertificateRevocationList::getBaseCRLNumberBigInt () throw (CertificationException, BigIntegerException)
References crl, CertificationException::INTERNAL_ERROR, CertificationException::INVALID_CRL, and CertificationException::SET_NO_VALUE.
getDerEncoded()
ByteArray CertificateRevocationList::getDerEncoded () throw (EncodeException)
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_READING, crl, and EncodeException::DER_ENCODE.
getExtension()
std::vector< Extension * > CertificateRevocationList::getExtension (Extension::Name extensionName)
References Extension::AUTHORITY_INFORMATION_ACCESS, Extension::AUTHORITY_KEY_IDENTIFIER, Extension::BASIC_CONSTRAINTS, Extension::CERTIFICATE_POLICIES, crl, Extension::CRL_DISTRIBUTION_POINTS, Extension::CRL_NUMBER, Extension::DELTA_CRL_INDICATOR, Extension::EXTENDED_KEY_USAGE, Extension::getName(), Extension::ISSUER_ALTERNATIVE_NAME, Extension::KEY_USAGE, Extension::SUBJECT_ALTERNATIVE_NAME, Extension::SUBJECT_INFORMATION_ACCESS, and Extension::SUBJECT_KEY_IDENTIFIER.
getExtensions()
std::vector< Extension * > CertificateRevocationList::getExtensions ()
References Extension::AUTHORITY_INFORMATION_ACCESS, Extension::AUTHORITY_KEY_IDENTIFIER, Extension::BASIC_CONSTRAINTS, Extension::CERTIFICATE_POLICIES, crl, Extension::CRL_DISTRIBUTION_POINTS, Extension::CRL_NUMBER, Extension::EXTENDED_KEY_USAGE, Extension::getName(), Extension::ISSUER_ALTERNATIVE_NAME, Extension::KEY_USAGE, Extension::SUBJECT_ALTERNATIVE_NAME, Extension::SUBJECT_INFORMATION_ACCESS, and Extension::SUBJECT_KEY_IDENTIFIER.
getIssuer()
RDNSequence CertificateRevocationList::getIssuer ()
References crl.
Referenced by getXmlEncoded().
getLastUpdate()
DateTime CertificateRevocationList::getLastUpdate ()
References crl.
Referenced by getXmlEncoded().
getNextUpdate()
DateTime CertificateRevocationList::getNextUpdate ()
References crl.
Referenced by getXmlEncoded().
getPemEncoded()
std::string CertificateRevocationList::getPemEncoded () throw (EncodeException)
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_READING, crl, EncodeException::PEM_ENCODE, and ByteArray::toString().
getRevokedCertificate()
std::vector< RevokedCertificate > CertificateRevocationList::getRevokedCertificate ()
References crl.
Referenced by getXmlEncoded().
getSerialNumber()
long CertificateRevocationList::getSerialNumber () throw (CertificationException)
References crl, CertificationException::INTERNAL_ERROR, CertificationException::INVALID_CRL, and CertificationException::SET_NO_VALUE.
Referenced by getXmlEncoded().
getSerialNumberBigInt()
BigInteger CertificateRevocationList::getSerialNumberBigInt () throw (CertificationException, BigIntegerException)
References crl, CertificationException::INTERNAL_ERROR, CertificationException::INVALID_CRL, and CertificationException::SET_NO_VALUE.
getUnknownExtensions()
std::vector< Extension * > CertificateRevocationList::getUnknownExtensions ()
References crl, Extension::getName(), and Extension::UNKNOWN.
getVersion()
long CertificateRevocationList::getVersion () throw (CertificationException)
References crl, CertificationException::INVALID_CRL, and CertificationException::SET_NO_VALUE.
Referenced by getXmlEncoded().
getX509Crl()
X509_CRL * CertificateRevocationList::getX509Crl () const
References crl.
Referenced by CertificateRevocationList(), and operator=().
getXmlEncoded() [1/2]
std::string CertificateRevocationList::getXmlEncoded ()
Referenced by getXmlEncoded().
getXmlEncoded() [2/2]
std::string CertificateRevocationList::getXmlEncoded (std::string tab)
References crl, Base64::encode(), getIssuer(), getLastUpdate(), getNextUpdate(), getRevokedCertificate(), getSerialNumber(), getVersion(), getXmlEncoded(), and DateTime::getXmlEncoded().
operator=()
CertificateRevocationList & CertificateRevocationList::operator= (const CertificateRevocationList & value)
References crl, and getX509Crl().
verify()
bool CertificateRevocationList::verify (PublicKey & publicKey)
References crl, and AsymmetricKey::getEvpPkey().
Member Data Documentation
crl
X509_CRL* CertificateRevocationList::crl protected
Referenced by CertificateRevocationList(), getBaseCRLNumber(), getBaseCRLNumberBigInt(), getDerEncoded(), getExtension(), getExtensions(), getIssuer(), getLastUpdate(), getNextUpdate(), getPemEncoded(), getRevokedCertificate(), getSerialNumber(), getSerialNumberBigInt(), getUnknownExtensions(), getVersion(), getX509Crl(), getXmlEncoded(), operator=(), verify(), and ~CertificateRevocationList().
The documentation for this class was generated from the following files:
include/libcryptosec/certificate/CertificateRevocationList.h
src/certificate/CertificateRevocationList.cpp