libcryptosec Documentation
AsymmetricKeyException Class Reference
#include <AsymmetricKeyException.h>
Public Types
enum ErrorCode {
UNKNOWN, SET_NO_VALUE, INVALID_TYPE, INTERNAL_ERROR,
UNAVAILABLE_KEY, INVALID_ASYMMETRIC_KEY
}
Public Member Functions
AsymmetricKeyException (std::string where)
AsymmetricKeyException (AsymmetricKeyException::ErrorCode errorCode, std::string where)
AsymmetricKeyException (AsymmetricKeyException::ErrorCode errorCode, std::string details, std::string where)
virtual ~AsymmetricKeyException () throw ()
virtual std::string getMessage () const
virtual std::string toString () const
virtual AsymmetricKeyException::ErrorCode getErrorCode ()
Public Member Functions inherited from LibCryptoSecException
virtual ~LibCryptoSecException () throw ()
virtual const char * what () const throw ()
virtual const std::string getDetails () const throw ()
Static Public Member Functions
static std::string errorCode2Message (AsymmetricKeyException::ErrorCode errorCode)
Protected Attributes
AsymmetricKeyException::ErrorCode errorCode
Protected Attributes inherited from LibCryptoSecException
std::string where
std::string details
Member Enumeration Documentation
ErrorCode
enum AsymmetricKeyException::ErrorCode
Enumerator
UNKNOWN
SET_NO_VALUE
INVALID_TYPE
INTERNAL_ERROR
UNAVAILABLE_KEY
INVALID_ASYMMETRIC_KEY
Constructor & Destructor Documentation
AsymmetricKeyException() [1/3]
AsymmetricKeyException::AsymmetricKeyException (std::string where) inline
References LibCryptoSecException::details, errorCode, UNKNOWN, and LibCryptoSecException::where.
AsymmetricKeyException() [2/3]
AsymmetricKeyException::AsymmetricKeyException (AsymmetricKeyException::ErrorCode errorCode, std::string where) inline
References LibCryptoSecException::details, errorCode, and LibCryptoSecException::where.
AsymmetricKeyException() [3/3]
AsymmetricKeyException::AsymmetricKeyException (AsymmetricKeyException::ErrorCode errorCode, std::string details, std::string where) inline
References LibCryptoSecException::details, errorCode, and LibCryptoSecException::where.
~AsymmetricKeyException()
virtual AsymmetricKeyException::~AsymmetricKeyException () throw () inline virtual
Member Function Documentation
errorCode2Message()
static std::string AsymmetricKeyException::errorCode2Message (AsymmetricKeyException::ErrorCode errorCode) inline static
References INTERNAL_ERROR, INVALID_ASYMMETRIC_KEY, INVALID_TYPE, SET_NO_VALUE, UNAVAILABLE_KEY, and UNKNOWN.
Referenced by getMessage(), and toString().
getErrorCode()
virtual AsymmetricKeyException::ErrorCode AsymmetricKeyException::getErrorCode () inline virtual
References errorCode.
getMessage()
virtual std::string AsymmetricKeyException::getMessage () const inline virtual
Implements LibCryptoSecException.
References LibCryptoSecException::details, errorCode, and errorCode2Message().
toString()
virtual std::string AsymmetricKeyException::toString () const inline virtual
Implements LibCryptoSecException.
References LibCryptoSecException::details, errorCode, errorCode2Message(), UNKNOWN, and LibCryptoSecException::where.
Member Data Documentation
errorCode
AsymmetricKeyException::ErrorCode AsymmetricKeyException::errorCode protected
Referenced by AsymmetricKeyException(), getErrorCode(), getMessage(), and toString().
The documentation for this class was generated from the following file:
include/libcryptosec/exception/AsymmetricKeyException.h