libcryptosec Documentation
NetscapeSPKIException Class Reference
#include <NetscapeSPKIException.h>
Public Types
enum ErrorCode { UNKNOWN, SIGNING_SPKI, INVALID_SPKI, SET_NO_VALUE }
Public Member Functions
NetscapeSPKIException (std::string where)
NetscapeSPKIException (NetscapeSPKIException::ErrorCode errorCode, std::string where)
virtual ~NetscapeSPKIException () throw ()
virtual std::string getMessage () const
virtual std::string toString () const
virtual NetscapeSPKIException::ErrorCode getErrorCode ()
Public Member Functions inherited from LibCryptoSecException
virtual ~LibCryptoSecException () throw ()
virtual const char * what () const throw ()
virtual const std::string getDetails () const throw ()
Static Public Member Functions
static std::string errorCode2Message (NetscapeSPKIException::ErrorCode errorCode)
Protected Attributes
NetscapeSPKIException::ErrorCode errorCode
Protected Attributes inherited from LibCryptoSecException
std::string where
std::string details
Member Enumeration Documentation
ErrorCode
enum NetscapeSPKIException::ErrorCode
Enumerator
UNKNOWN
SIGNING_SPKI
INVALID_SPKI
SET_NO_VALUE
Constructor & Destructor Documentation
NetscapeSPKIException() [1/2]
NetscapeSPKIException::NetscapeSPKIException (std::string where) inline
References errorCode, UNKNOWN, and LibCryptoSecException::where.
NetscapeSPKIException() [2/2]
NetscapeSPKIException::NetscapeSPKIException (NetscapeSPKIException::ErrorCode errorCode, std::string where) inline
References errorCode, and LibCryptoSecException::where.
~NetscapeSPKIException()
virtual NetscapeSPKIException::~NetscapeSPKIException () throw () inline virtual
Member Function Documentation
errorCode2Message()
static std::string NetscapeSPKIException::errorCode2Message (NetscapeSPKIException::ErrorCode errorCode) inline static
References INVALID_SPKI, SET_NO_VALUE, SIGNING_SPKI, and UNKNOWN.
Referenced by getMessage(), and toString().
getErrorCode()
virtual NetscapeSPKIException::ErrorCode NetscapeSPKIException::getErrorCode () inline virtual
References errorCode.
getMessage()
virtual std::string NetscapeSPKIException::getMessage () const inline virtual
Implements LibCryptoSecException.
References errorCode, and errorCode2Message().
toString()
virtual std::string NetscapeSPKIException::toString () const inline virtual
Implements LibCryptoSecException.
References errorCode, errorCode2Message(), UNKNOWN, and LibCryptoSecException::where.
Member Data Documentation
errorCode
NetscapeSPKIException::ErrorCode NetscapeSPKIException::errorCode protected
Referenced by getErrorCode(), getMessage(), NetscapeSPKIException(), and toString().
The documentation for this class was generated from the following file:
include/libcryptosec/exception/NetscapeSPKIException.h