libcryptosec Documentation
GeneralNames Class Reference
#include <GeneralNames.h>
Public Member Functions
GeneralNames ()
GeneralNames (GENERAL_NAMES *generalNames)
virtual ~GeneralNames ()
std::string getXmlEncoded ()
std::string getXmlEncoded (std::string tab)
void addGeneralName (GeneralName &generalName)
std::vector< GeneralName > getGeneralNames () const
int getNumberOfEntries () const
GENERAL_NAMES * getInternalGeneralNames ()
GeneralNames & operator= (const GeneralNames &value)
Static Protected Member Functions
static std::string data2IpAddress (unsigned char *data)
Protected Attributes
std::vector< GeneralName > generalNames
Constructor & Destructor Documentation
GeneralNames() [1/2]
GeneralNames::GeneralNames ()
GeneralNames() [2/2]
GeneralNames::GeneralNames (GENERAL_NAMES * generalNames)
~GeneralNames()
GeneralNames::~GeneralNames () virtual
Member Function Documentation
addGeneralName()
void GeneralNames::addGeneralName (GeneralName & generalName)
References generalNames.
data2IpAddress()
std::string GeneralNames::data2IpAddress (unsigned char * data) static protected
Deprecated:
Método movido para a classe GeneralName.
Futuramente poderá ser removido dessa classe.
References GeneralName::data2IpAddress().
getGeneralNames()
std::vector< GeneralName > GeneralNames::getGeneralNames () const
References generalNames.
Referenced by operator=().
getInternalGeneralNames()
GENERAL_NAMES * GeneralNames::getInternalGeneralNames ()
References generalNames.
Referenced by DistributionPoint::getDistPoint(), DistributionPointName::getDistPointName(), IssuerAlternativeNameExtension::getX509Extension(), SubjectAlternativeNameExtension::getX509Extension(), and AuthorityKeyIdentifierExtension::getX509Extension().
getNumberOfEntries()
int GeneralNames::getNumberOfEntries () const
References generalNames.
Referenced by AuthorityKeyIdentifierExtension::extValue2Xml(), DistributionPoint::getDistPoint(), AuthorityKeyIdentifierExtension::getX509Extension(), DistributionPoint::getXmlEncoded(), and AuthorityKeyIdentifierExtension::getXmlEncoded().
getXmlEncoded() [1/2]
std::string GeneralNames::getXmlEncoded ()
Referenced by IssuerAlternativeNameExtension::extValue2Xml(), SubjectAlternativeNameExtension::extValue2Xml(), AuthorityKeyIdentifierExtension::extValue2Xml(), DistributionPoint::getXmlEncoded(), DistributionPointName::getXmlEncoded(), SubjectAlternativeNameExtension::getXmlEncoded(), IssuerAlternativeNameExtension::getXmlEncoded(), and AuthorityKeyIdentifierExtension::getXmlEncoded().
getXmlEncoded() [2/2]
std::string GeneralNames::getXmlEncoded (std::string tab)
References generalNames.
operator=()
GeneralNames & GeneralNames::operator= (const GeneralNames & value)
References generalNames, and getGeneralNames().
Member Data Documentation
generalNames
std::vector<GeneralName> GeneralNames::generalNames protected
Referenced by addGeneralName(), getGeneralNames(), getInternalGeneralNames(), getNumberOfEntries(), getXmlEncoded(), and operator=().
The documentation for this class was generated from the following files:
include/libcryptosec/certificate/GeneralNames.h
src/certificate/GeneralNames.cpp