libcryptosec Documentation
CertificateBuilder Class Reference
#include <CertificateBuilder.h>
Public Member Functions
CertificateBuilder ()
CertificateBuilder (std::string pemEncoded) throw (EncodeException)
CertificateBuilder (ByteArray &derEncoded) throw (EncodeException)
CertificateBuilder (CertificateRequest &request)
CertificateBuilder (const CertificateBuilder &cert)
virtual ~CertificateBuilder ()
std::string getPemEncoded () throw (EncodeException)
ByteArray getDerEncoded () throw (EncodeException)
std::string getXmlEncoded ()
std::string getXmlEncoded (std::string tab)
virtual std::string toXml (std::string tab="")
void setSerialNumber (long serial)
void setSerialNumber (BigInteger serial) throw (BigIntegerException)
Definir serial à partir de BigInteger, para seriais maiores do que um "long".
long getSerialNumber () throw (CertificationException)
BigInteger getSerialNumberBigInt () throw (CertificationException, BigIntegerException)
MessageDigest::Algorithm getMessageDigestAlgorithm () throw (MessageDigestException)
void setPublicKey (PublicKey &publicKey)
PublicKey * getPublicKey () throw (CertificationException, AsymmetricKeyException)
ByteArray getPublicKeyInfo () throw (CertificationException)
void setVersion (long version)
long getVersion () throw (CertificationException)
void setNotBefore (DateTime &dateTime)
DateTime getNotBefore ()
void setNotAfter (DateTime &dateTime)
DateTime getNotAfter ()
void setIssuer (RDNSequence &name)
Define o campo "issuer" a partir de um RDNSequence, utilizando o codificação de string padrão do OpenSSL.
void setIssuer (X509 *issuer) throw (CertificationException)
Define o campo "issuer" a partir de um X509, respeitando o codificação de string existente.
RDNSequence getIssuer ()
void alterSubject (RDNSequence &name) throw (CertificationException)
Altera o campo "subject" a partir de um RDNSequence, respeitando a codificação de string existente.
void setSubject (RDNSequence &name)
Define o campo "subject" a partir de um RDNSequence, utilizando a codificação de string padrão do OpenSSL.
void setSubject (X509_REQ *req) throw (CertificationException)
Define o campo "subject" a partir de um X509_REQ, respeitando a codificação de string existente.
RDNSequence getSubject ()
void addExtension (Extension &extension) throw (CertificationException)
void addExtensions (std::vector< Extension *> &extensions) throw (CertificationException)
void replaceExtension (Extension &extension) throw (CertificationException)
std::vector< Extension * > removeExtension (Extension::Name extensionName) throw (CertificationException)
std::vector< Extension * > removeExtension (ObjectIdentifier extOID) throw (CertificationException)
std::vector< Extension * > getExtension (Extension::Name extensionName)
std::vector< Extension * > getExtensions ()
std::vector< Extension * > getUnknownExtensions ()
Certificate * sign (PrivateKey &privateKey, MessageDigest::Algorithm messageDigestAlgorithm) throw (CertificationException, AsymmetricKeyException)
X509 * getX509 () const
CertificateBuilder & operator= (const CertificateBuilder &value)
bool isIncludeEcdsaParameters () const
void setIncludeEcdsaParameters (bool includeEcdsaParameters)
void includeEcdsaParameters ()
Protected Attributes
X509 * cert
bool includeECDSAParameters
Constructor & Destructor Documentation
CertificateBuilder() [1/5]
CertificateBuilder::CertificateBuilder ()
References cert, setIncludeEcdsaParameters(), setNotAfter(), and setNotBefore().
CertificateBuilder() [2/5]
CertificateBuilder::CertificateBuilder (std::string pemEncoded) throw (EncodeException)
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_WRITING, cert, EncodeException::PEM_DECODE, and setIncludeEcdsaParameters().
CertificateBuilder() [3/5]
CertificateBuilder::CertificateBuilder (ByteArray & derEncoded) throw (EncodeException)
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_WRITING, cert, EncodeException::DER_DECODE, and setIncludeEcdsaParameters().
CertificateBuilder() [4/5]
CertificateBuilder::CertificateBuilder (CertificateRequest & request)
References addExtension(), cert, CertificateRequest::getExtensions(), CertificateRequest::getPublicKey(), CertificateRequest::getX509Req(), setIncludeEcdsaParameters(), setNotAfter(), setNotBefore(), setPublicKey(), and setSubject().
CertificateBuilder() [5/5]
CertificateBuilder::CertificateBuilder (const CertificateBuilder & cert)
References getX509(), isIncludeEcdsaParameters(), and setIncludeEcdsaParameters().
~CertificateBuilder()
CertificateBuilder::~CertificateBuilder () virtual
References cert.
Member Function Documentation
addExtension()
void CertificateBuilder::addExtension (Extension & extension) throw (CertificationException)
References CertificationException::ADDING_EXTENSION, and cert.
Referenced by CertificateBuilder(), and replaceExtension().
addExtensions()
void CertificateBuilder::addExtensions (std::vector< Extension *> & extensions) throw (CertificationException)
References CertificationException::ADDING_EXTENSION, and cert.
alterSubject()
void CertificateBuilder::alterSubject (RDNSequence & name) throw (CertificationException)
Altera o campo "subject" a partir de um RDNSequence, respeitando a codificação de string existente.
Parameters
name subject
References cert, and CertificationException::INTERNAL_ERROR.
getDerEncoded()
ByteArray CertificateBuilder::getDerEncoded () throw (EncodeException)
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_READING, cert, and EncodeException::DER_ENCODE.
getExtension()
std::vector< Extension * > CertificateBuilder::getExtension (Extension::Name extensionName)
References Extension::AUTHORITY_INFORMATION_ACCESS, Extension::AUTHORITY_KEY_IDENTIFIER, Extension::BASIC_CONSTRAINTS, cert, Extension::CERTIFICATE_POLICIES, Extension::CRL_DISTRIBUTION_POINTS, Extension::EXTENDED_KEY_USAGE, Extension::getName(), Extension::ISSUER_ALTERNATIVE_NAME, Extension::KEY_USAGE, Extension::SUBJECT_ALTERNATIVE_NAME, Extension::SUBJECT_INFORMATION_ACCESS, and Extension::SUBJECT_KEY_IDENTIFIER.
getExtensions()
std::vector< Extension * > CertificateBuilder::getExtensions ()
References Extension::AUTHORITY_INFORMATION_ACCESS, Extension::AUTHORITY_KEY_IDENTIFIER, Extension::BASIC_CONSTRAINTS, cert, Extension::CERTIFICATE_POLICIES, Extension::CRL_DISTRIBUTION_POINTS, Extension::EXTENDED_KEY_USAGE, Extension::getName(), Extension::ISSUER_ALTERNATIVE_NAME, Extension::KEY_USAGE, Extension::SUBJECT_ALTERNATIVE_NAME, Extension::SUBJECT_INFORMATION_ACCESS, and Extension::SUBJECT_KEY_IDENTIFIER.
Referenced by getXmlEncoded(), and toXml().
getIssuer()
RDNSequence CertificateBuilder::getIssuer ()
References cert.
Referenced by getXmlEncoded(), and toXml().
getMessageDigestAlgorithm()
MessageDigest::Algorithm CertificateBuilder::getMessageDigestAlgorithm () throw (MessageDigestException)
References cert, and MessageDigest::getMessageDigest().
getNotAfter()
DateTime CertificateBuilder::getNotAfter ()
References cert.
Referenced by getXmlEncoded(), and toXml().
getNotBefore()
DateTime CertificateBuilder::getNotBefore ()
References cert.
Referenced by getXmlEncoded(), and toXml().
getPemEncoded()
std::string CertificateBuilder::getPemEncoded () throw (EncodeException)
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_READING, cert, EncodeException::PEM_ENCODE, and ByteArray::toString().
getPublicKey()
PublicKey * CertificateBuilder::getPublicKey () throw (CertificationException, AsymmetricKeyException)
References cert, and CertificationException::SET_NO_VALUE.
Referenced by includeEcdsaParameters(), and sign().
getPublicKeyInfo()
ByteArray CertificateBuilder::getPublicKeyInfo () throw (CertificationException)
References cert, ByteArray::getDataPointer(), and CertificationException::SET_NO_VALUE.
getSerialNumber()
long CertificateBuilder::getSerialNumber () throw (CertificationException)
References cert, CertificationException::INTERNAL_ERROR, and CertificationException::SET_NO_VALUE.
Referenced by getXmlEncoded().
getSerialNumberBigInt()
BigInteger CertificateBuilder::getSerialNumberBigInt () throw (CertificationException, BigIntegerException)
References cert, CertificationException::INTERNAL_ERROR, and CertificationException::SET_NO_VALUE.
Referenced by toXml().
getSubject()
RDNSequence CertificateBuilder::getSubject ()
References cert.
Referenced by getXmlEncoded(), and toXml().
getUnknownExtensions()
std::vector< Extension * > CertificateBuilder::getUnknownExtensions ()
References cert, Extension::getName(), and Extension::UNKNOWN.
getVersion()
long CertificateBuilder::getVersion () throw (CertificationException)
References cert, CertificationException::INVALID_CERTIFICATE, and CertificationException::SET_NO_VALUE.
Referenced by getXmlEncoded(), and toXml().
getX509()
X509 * CertificateBuilder::getX509 () const
References cert.
Referenced by CertificateBuilder(), and operator=().
getXmlEncoded() [1/2]
std::string CertificateBuilder::getXmlEncoded ()
Deprecated:
Retorna o conteudo da extensão em formato XML.
Esta função será substituida por toXml().
Referenced by getXmlEncoded(), and toXml().
getXmlEncoded() [2/2]
std::string CertificateBuilder::getXmlEncoded (std::string tab)
References cert, Base64::encode(), getExtensions(), getIssuer(), getNotAfter(), getNotBefore(), getSerialNumber(), getSubject(), getVersion(), and getXmlEncoded().
includeEcdsaParameters()
void CertificateBuilder::includeEcdsaParameters ()
References cert, AsymmetricKey::ECDSA, AsymmetricKey::getAlgorithm(), RDNSequence::getEntries(), AsymmetricKey::getEvpPkey(), getPublicKey(), CertificationException::INTERNAL_ERROR, isIncludeEcdsaParameters(), and setPublicKey().
Referenced by setIncludeEcdsaParameters().
isIncludeEcdsaParameters()
bool CertificateBuilder::isIncludeEcdsaParameters () const
References includeECDSAParameters.
Referenced by CertificateBuilder(), includeEcdsaParameters(), and operator=().
operator=()
CertificateBuilder & CertificateBuilder::operator= (const CertificateBuilder & value)
References cert, getX509(), isIncludeEcdsaParameters(), and setIncludeEcdsaParameters().
removeExtension() [1/2]
std::vector< Extension * > CertificateBuilder::removeExtension (Extension::Name extensionName) throw (CertificationException)
References Extension::AUTHORITY_INFORMATION_ACCESS, Extension::AUTHORITY_KEY_IDENTIFIER, Extension::BASIC_CONSTRAINTS, cert, Extension::CERTIFICATE_POLICIES, Extension::CRL_DISTRIBUTION_POINTS, Extension::EXTENDED_KEY_USAGE, Extension::getName(), Extension::ISSUER_ALTERNATIVE_NAME, Extension::KEY_USAGE, Extension::SUBJECT_ALTERNATIVE_NAME, Extension::SUBJECT_INFORMATION_ACCESS, and Extension::SUBJECT_KEY_IDENTIFIER.
removeExtension() [2/2]
std::vector< Extension * > CertificateBuilder::removeExtension (ObjectIdentifier extOID) throw (CertificationException)
References Extension::AUTHORITY_INFORMATION_ACCESS, Extension::AUTHORITY_KEY_IDENTIFIER, Extension::BASIC_CONSTRAINTS, cert, Extension::CERTIFICATE_POLICIES, Extension::CRL_DISTRIBUTION_POINTS, Extension::EXTENDED_KEY_USAGE, Extension::getName(), Extension::ISSUER_ALTERNATIVE_NAME, Extension::KEY_USAGE, Extension::SUBJECT_ALTERNATIVE_NAME, Extension::SUBJECT_INFORMATION_ACCESS, and Extension::SUBJECT_KEY_IDENTIFIER.
replaceExtension()
void CertificateBuilder::replaceExtension (Extension & extension) throw (CertificationException)
References addExtension(), CertificationException::ADDING_EXTENSION, and cert.
setIncludeEcdsaParameters()
void CertificateBuilder::setIncludeEcdsaParameters (bool includeEcdsaParameters)
References includeEcdsaParameters(), and includeECDSAParameters.
Referenced by CertificateBuilder(), and operator=().
setIssuer() [1/2]
void CertificateBuilder::setIssuer (RDNSequence & name)
Define o campo "issuer" a partir de um RDNSequence, utilizando o codificação de string padrão do OpenSSL.
Parameters
name issuer
References cert, and RDNSequence::getX509Name().
setIssuer() [2/2]
void CertificateBuilder::setIssuer (X509 * issuer) throw (CertificationException)
Define o campo "issuer" a partir de um X509, respeitando o codificação de string existente.
Parameters
issuer issuer
References cert, and CertificationException::INTERNAL_ERROR.
setNotAfter()
void CertificateBuilder::setNotAfter (DateTime & dateTime)
References cert, and DateTime::getAsn1Time().
Referenced by CertificateBuilder(), and sign().
setNotBefore()
void CertificateBuilder::setNotBefore (DateTime & dateTime)
References cert, and DateTime::getAsn1Time().
Referenced by CertificateBuilder(), and sign().
setPublicKey()
void CertificateBuilder::setPublicKey (PublicKey & publicKey)
References cert, and AsymmetricKey::getEvpPkey().
Referenced by CertificateBuilder(), and includeEcdsaParameters().
setSerialNumber() [1/2]
void CertificateBuilder::setSerialNumber (long serial)
References cert.
setSerialNumber() [2/2]
void CertificateBuilder::setSerialNumber (BigInteger serial) throw (BigIntegerException)
Definir serial à partir de BigInteger, para seriais maiores do que um "long".
References cert.
setSubject() [1/2]
void CertificateBuilder::setSubject (RDNSequence & name)
Define o campo "subject" a partir de um RDNSequence, utilizando a codificação de string padrão do OpenSSL.
Parameters
name subject
References cert, and RDNSequence::getX509Name().
Referenced by CertificateBuilder().
setSubject() [2/2]
void CertificateBuilder::setSubject (X509_REQ * req) throw (CertificationException)
Define o campo "subject" a partir de um X509_REQ, respeitando a codificação de string existente.
Parameters
name subject
References cert, and CertificationException::INTERNAL_ERROR.
setVersion()
void CertificateBuilder::setVersion (long version)
References cert.
sign()
Certificate * CertificateBuilder::sign (PrivateKey & privateKey, MessageDigest::Algorithm messageDigestAlgorithm) throw (CertificationException, AsymmetricKeyException)
References cert, MessageDigest::getMessageDigest(), getPublicKey(), CertificationException::INTERNAL_ERROR, setNotAfter(), and setNotBefore().
toXml()
std::string CertificateBuilder::toXml (std::string tab = "") virtual
References cert, Base64::encode(), getExtensions(), getIssuer(), getNotAfter(), getNotBefore(), getSerialNumberBigInt(), getSubject(), getVersion(), getXmlEncoded(), and BigInteger::toDec().
Member Data Documentation
cert
X509* CertificateBuilder::cert protected
Referenced by addExtension(), addExtensions(), alterSubject(), CertificateBuilder(), getDerEncoded(), getExtension(), getExtensions(), getIssuer(), getMessageDigestAlgorithm(), getNotAfter(), getNotBefore(), getPemEncoded(), getPublicKey(), getPublicKeyInfo(), getSerialNumber(), getSerialNumberBigInt(), getSubject(), getUnknownExtensions(), getVersion(), getX509(), getXmlEncoded(), includeEcdsaParameters(), operator=(), removeExtension(), replaceExtension(), setIssuer(), setNotAfter(), setNotBefore(), setPublicKey(), setSerialNumber(), setSubject(), setVersion(), sign(), toXml(), and ~CertificateBuilder().
includeECDSAParameters
bool CertificateBuilder::includeECDSAParameters protected
Referenced by isIncludeEcdsaParameters(), and setIncludeEcdsaParameters().
The documentation for this class was generated from the following files:
include/libcryptosec/certificate/CertificateBuilder.h
src/certificate/CertificateBuilder.cpp