libcryptosec Documentation
BigIntegerException Class Reference
#include <BigIntegerException.h>
Public Types
enum ErrorCode {
UNKNOWN = 0, MEMORY_ALLOC = 1, INTERNAL_ERROR = 3, UNSIGNED_LONG_OVERFLOW = 4,
DIVISION_BY_ZERO = 5
}
Public Member Functions
BigIntegerException (ErrorCode errorCode=UNKNOWN, std::string where="")
virtual ~BigIntegerException () throw ()
virtual std::string getMessage () const
virtual std::string toString () const
virtual ErrorCode getErrorCode ()
Public Member Functions inherited from LibCryptoSecException
virtual ~LibCryptoSecException () throw ()
virtual const char * what () const throw ()
virtual const std::string getDetails () const throw ()
Static Public Member Functions
static std::string errorCode2Message (ErrorCode errorCode)
Protected Attributes
ErrorCode errorCode
Protected Attributes inherited from LibCryptoSecException
std::string where
std::string details
Member Enumeration Documentation
ErrorCode
enum BigIntegerException::ErrorCode
Enumerator
UNKNOWN
MEMORY_ALLOC
INTERNAL_ERROR
UNSIGNED_LONG_OVERFLOW
DIVISION_BY_ZERO
Constructor & Destructor Documentation
BigIntegerException()
BigIntegerException::BigIntegerException (ErrorCode errorCode = UNKNOWN, std::string where = "") inline
References errorCode, and LibCryptoSecException::where.
~BigIntegerException()
virtual BigIntegerException::~BigIntegerException () throw () inline virtual
Member Function Documentation
errorCode2Message()
static std::string BigIntegerException::errorCode2Message (ErrorCode errorCode) inline static
References DIVISION_BY_ZERO, INTERNAL_ERROR, MEMORY_ALLOC, UNKNOWN, and UNSIGNED_LONG_OVERFLOW.
Referenced by getMessage(), and toString().
getErrorCode()
virtual ErrorCode BigIntegerException::getErrorCode () inline virtual
References errorCode.
getMessage()
virtual std::string BigIntegerException::getMessage () const inline virtual
Implements LibCryptoSecException.
References errorCode, and errorCode2Message().
toString()
virtual std::string BigIntegerException::toString () const inline virtual
Implements LibCryptoSecException.
References errorCode, errorCode2Message(), UNKNOWN, and LibCryptoSecException::where.
Member Data Documentation
errorCode
ErrorCode BigIntegerException::errorCode protected
Referenced by BigIntegerException(), getErrorCode(), getMessage(), and toString().
The documentation for this class was generated from the following file:
include/libcryptosec/exception/BigIntegerException.h