libcryptosec Documentation
MessageDigestException Class Reference
#include <MessageDigestException.h>
Public Types
enum ErrorCode {
UNKNOWN, CTX_INIT, CTX_UPDATE, CTX_FINISH,
INVALID_ALGORITHM
}
Public Member Functions
MessageDigestException (std::string where)
MessageDigestException (MessageDigestException::ErrorCode errorCode, std::string where)
virtual ~MessageDigestException () throw ()
virtual std::string getMessage () const
virtual std::string toString () const
virtual MessageDigestException::ErrorCode getErrorCode ()
Public Member Functions inherited from LibCryptoSecException
virtual ~LibCryptoSecException () throw ()
virtual const char * what () const throw ()
virtual const std::string getDetails () const throw ()
Static Public Member Functions
static std::string errorCode2Message (MessageDigestException::ErrorCode errorCode)
Protected Attributes
MessageDigestException::ErrorCode errorCode
Protected Attributes inherited from LibCryptoSecException
std::string where
std::string details
Member Enumeration Documentation
ErrorCode
enum MessageDigestException::ErrorCode
Enumerator
UNKNOWN
CTX_INIT
CTX_UPDATE
CTX_FINISH
INVALID_ALGORITHM
Constructor & Destructor Documentation
MessageDigestException() [1/2]
MessageDigestException::MessageDigestException (std::string where) inline
References errorCode, UNKNOWN, and LibCryptoSecException::where.
MessageDigestException() [2/2]
MessageDigestException::MessageDigestException (MessageDigestException::ErrorCode errorCode, std::string where) inline
References errorCode, and LibCryptoSecException::where.
~MessageDigestException()
virtual MessageDigestException::~MessageDigestException () throw () inline virtual
Member Function Documentation
errorCode2Message()
static std::string MessageDigestException::errorCode2Message (MessageDigestException::ErrorCode errorCode) inline static
References CTX_FINISH, CTX_INIT, CTX_UPDATE, INVALID_ALGORITHM, and UNKNOWN.
Referenced by getMessage(), and toString().
getErrorCode()
virtual MessageDigestException::ErrorCode MessageDigestException::getErrorCode () inline virtual
References errorCode.
getMessage()
virtual std::string MessageDigestException::getMessage () const inline virtual
Implements LibCryptoSecException.
References errorCode, and errorCode2Message().
toString()
virtual std::string MessageDigestException::toString () const inline virtual
Implements LibCryptoSecException.
References errorCode, errorCode2Message(), UNKNOWN, and LibCryptoSecException::where.
Member Data Documentation
errorCode
MessageDigestException::ErrorCode MessageDigestException::errorCode protected
Referenced by getErrorCode(), getMessage(), MessageDigestException(), and toString().
The documentation for this class was generated from the following file:
include/libcryptosec/exception/MessageDigestException.h