libcryptosec Documentation
NetscapeSPKI Class Reference
Classes Relacionadas ao Padrão Netscape SPKI
Implementa o padrão NetscapeSPKI.
#include <NetscapeSPKI.h>
Public Member Functions
NetscapeSPKI (NETSCAPE_SPKI *netscapeSPKI) throw (NetscapeSPKIException)
Construtor.
NetscapeSPKI (std::string netscapeSPKIBase64) throw (EncodeException)
Construtor.
virtual ~NetscapeSPKI ()
Destrutor.
std::string getBase64Encoded () throw (EncodeException)
Obtem objeto NetscapeSPKI em formato base64.
PublicKey * getPublicKey () throw (AsymmetricKeyException, NetscapeSPKIException)
Retorna a chave pública do objeto NetscapeSPKI.
std::string getChallenge ()
Retorna desafio do objeto NetscapeSPKI.
bool verify () throw (AsymmetricKeyException, NetscapeSPKIException)
Verifica a assinatura do NetscapeSPKI.
bool verify (PublicKey &publicKey)
Verifica a assinatura do NetscapeSPKI.
bool isSigned ()
Protected Attributes
NETSCAPE_SPKI * netscapeSPKI
Estrutura do OpenSSL para representar um objeto NetscapeSPKI.
Detailed Description
Implementa o padrão NetscapeSPKI.
Este é uma estrutura que contém: estrutura SPKAC (chave pública e desafio), o algoritmo de assinatura e a assinatura em formato ASN1 String do SPKAC.
Constructor & Destructor Documentation
NetscapeSPKI() [1/2]
NetscapeSPKI::NetscapeSPKI (NETSCAPE_SPKI * netscapeSPKI) throw (NetscapeSPKIException)
Construtor.
Cria um objeto NetscapeSPKI a partir de uma estrutura NETSCAPE_SPKI do OpenSSL.
Parameters
netscapeSPKI estrutura NETSCAPE_SPKI.
References NetscapeSPKIException::INVALID_SPKI.
NetscapeSPKI() [2/2]
NetscapeSPKI::NetscapeSPKI (std::string netscapeSPKIBase64) throw (EncodeException)
Construtor.
Cria um objeto NetscapeSPKI a partir outro do mesmo tipo mas codificado em base64.
Parameters
netscapeSPKI estrutura NETSCAPE_SPKI.
References EncodeException::BASE64_DECODE.
~NetscapeSPKI()
NetscapeSPKI::~NetscapeSPKI () virtual
Destrutor.
References netscapeSPKI.
Member Function Documentation
getBase64Encoded()
std::string NetscapeSPKI::getBase64Encoded () throw (EncodeException)
Obtem objeto NetscapeSPKI em formato base64.
Returns
objeto NetscapeSPKI em formato base64.
Exceptions
EncodeException caso ocorra algum erro interno durante a codificação do objeto em base64.
References EncodeException::BASE64_ENCODE, and netscapeSPKI.
getChallenge()
std::string NetscapeSPKI::getChallenge ()
Retorna desafio do objeto NetscapeSPKI.
Returns
desafio do objeto NetscapeSPKI.
References netscapeSPKI.
getPublicKey()
PublicKey * NetscapeSPKI::getPublicKey () throw (AsymmetricKeyException, NetscapeSPKIException)
Retorna a chave pública do objeto NetscapeSPKI.
Returns
Retorna a chave pública do objeto NetscapeSPKI.
Exceptions
NetscapeSPKIException caso a chave pública não esteja disponível no objeto NetscapeSPKI.
AsymmetricKeyException caso não seja possível instanciar um objeto PublicKey a partir da chave pública obtida de NetscapeSPKI.
References netscapeSPKI, and NetscapeSPKIException::SET_NO_VALUE.
Referenced by CertificateRequestSPKAC::CertificateRequestSPKAC(), and verify().
isSigned()
bool NetscapeSPKI::isSigned ()
References netscapeSPKI.
Referenced by CertificateRequestSPKAC::isSigned().
verify() [1/2]
bool NetscapeSPKI::verify () throw (AsymmetricKeyException, NetscapeSPKIException)
Verifica a assinatura do NetscapeSPKI.
Returns
true caso a assinatura seja verificada com sucesso, false caso contrário.
Exceptions
NetscapeSPKIException caso a chave pública não esteja disponível no objeto NetscapeSPKI.
AsymmetricKeyException caso não seja possível instanciar um objeto PublicKey a partir da chave pública obtida de NetscapeSPKI.
References AsymmetricKey::getEvpPkey(), getPublicKey(), and netscapeSPKI.
Referenced by CertificateRequestSPKAC::verify().
verify() [2/2]
bool NetscapeSPKI::verify (PublicKey & publicKey)
Verifica a assinatura do NetscapeSPKI.
Parameters
publicKey chave pública.
Returns
true caso a assinatura seja verificada com sucesso, false caso contrário.
Exceptions
NetscapeSPKIException caso a chave pública não esteja disponível no objeto NetscapeSPKI.
AsymmetricKeyException caso não seja possível instanciar um objeto PublicKey a partir da chave pública obtida de NetscapeSPKI.
References AsymmetricKey::getEvpPkey(), and netscapeSPKI.
Member Data Documentation
netscapeSPKI
NETSCAPE_SPKI* NetscapeSPKI::netscapeSPKI protected
Estrutura do OpenSSL para representar um objeto NetscapeSPKI.
Referenced by getBase64Encoded(), getChallenge(), getPublicKey(), isSigned(), verify(), and ~NetscapeSPKI().
The documentation for this class was generated from the following files:
include/libcryptosec/NetscapeSPKI.h
src/NetscapeSPKI.cpp