libcryptosec Documentation
MessageDigest Class Reference
Classes Relacionadas Utilitárias de Criptografia
Implementa as funcionalidades de resumo criptográfico.
#include <MessageDigest.h>
Public Types
enum Algorithm {
MD4, MD5, RIPEMD160, SHA,
SHA1, SHA224, SHA256, SHA384,
SHA512
}
Public Member Functions
MessageDigest ()
Construtor padrão.
MessageDigest (MessageDigest::Algorithm algorithm) throw (MessageDigestException)
Construtor Constroi um objeto MessageDigest.
MessageDigest (MessageDigest::Algorithm algorithm, Engine &engine) throw (MessageDigestException)
Construtor Constroi um objeto MessageDigest utilizando uma engine.
virtual ~MessageDigest ()
Destrutor.
void init (MessageDigest::Algorithm algorithm) throw (MessageDigestException)
Inicializa estruturas de resumos do OpenSSL.
void init (MessageDigest::Algorithm algorithm, Engine &engine) throw (MessageDigestException)
Inicializa estruturas de resumos do OpenSSL utilizando uma engine.
void update (ByteArray &data) throw (MessageDigestException, InvalidStateException)
Define o conteúdo de entrada função de resumo.
void update (std::string &data) throw (MessageDigestException, InvalidStateException)
Define o conteúdo de entrada função de resumo.
ByteArray doFinal () throw (MessageDigestException, InvalidStateException)
Realiza resumo criptográfico.
ByteArray doFinal (ByteArray &data) throw (MessageDigestException, InvalidStateException)
Realiza atualização do contexto e faz resumo criptográfico.
ByteArray doFinal (std::string &data) throw (MessageDigestException, InvalidStateException)
Realiza atualização do contexto e faz resumo criptográfico.
MessageDigest::Algorithm getAlgorithm () throw (InvalidStateException)
Retorna algoritmo de resumo selecionado.
Static Public Member Functions
static const EVP_MD * getMessageDigest (MessageDigest::Algorithm algorithm)
Retorna a estrutura do OpenSSL que representa o algoritmo de resumo desejado.
static MessageDigest::Algorithm getMessageDigest (int algorithmNid) throw (MessageDigestException)
Obtem algoritmo de resumo a partir do identificador numérico do algoritmo no OpenSSL.
static void loadMessageDigestAlgorithms ()
Carrega todos os algoritmos de resumo.
Protected Types
enum State { NO_INIT, INIT, UPDATE }
Protected Attributes
MessageDigest::Algorithm algorithm
Algoritmo selecionado.
MessageDigest::State state
Estado das estruturas de resumo.
EVP_MD_CTX ctx
Estrutura OpenSSL que representa o algoritmo de resumo.
Detailed Description
Implementa as funcionalidades de resumo criptográfico.
Antes de utilizar os algortimos de resumo devem-se carregá-los através de init(Algorithm) ou de loadMessageDigestAlgorithms().
Member Enumeration Documentation
Algorithm
enum MessageDigest::Algorithm
Enumerator
MD4
MD5
RIPEMD160
SHA
SHA1
SHA224
SHA256
SHA384
SHA512
State
enum MessageDigest::State protected
Enumerator
NO_INIT
INIT
UPDATE
Constructor & Destructor Documentation
MessageDigest() [1/3]
MessageDigest::MessageDigest ()
Construtor padrão.
Controi objeto MessageDigest não inicializado.
References NO_INIT, and state.
MessageDigest() [2/3]
MessageDigest::MessageDigest (MessageDigest::Algorithm algorithm) throw (MessageDigestException)
Construtor Constroi um objeto MessageDigest.
Parameters
algorithm algoritmo de resumo.
Exceptions
MessageDigestException caso ocorra erro ao inicializar a estrutura de resumos do OpenSSL.
References algorithm, ctx, MessageDigestException::CTX_INIT, getMessageDigest(), INIT, and state.
MessageDigest() [3/3]
MessageDigest::MessageDigest (MessageDigest::Algorithm algorithm, Engine & engine) throw (MessageDigestException)
Construtor Constroi um objeto MessageDigest utilizando uma engine.
Parameters
algorithm algoritmo de resumo.
engine objeto Engine.
Exceptions
MessageDigestException caso ocorra erro ao inicializar a estrutura de resumos do OpenSSL.
References algorithm, ctx, MessageDigestException::CTX_INIT, getMessageDigest(), INIT, and state.
~MessageDigest()
MessageDigest::~MessageDigest () virtual
Destrutor.
References ctx.
Member Function Documentation
doFinal() [1/3]
ByteArray MessageDigest::doFinal () throw (MessageDigestException, InvalidStateException)
Realiza resumo criptográfico.
Returns
bytes que representam o resumo calculado.
Exceptions
MessageDigestException caso ocorra erro ao finalizar o contexto de resumo do OpenSSL.
InvalidStateException caso o objeto MessageDigest não tenha sido inicializado corretamente ou caso não tenha sido passado o conteúdo para calculo do resumo.
References ctx, MessageDigestException::CTX_FINISH, INIT, NO_INIT, and state.
Referenced by doFinal(), Certificate::getFingerPrint(), and CertificateRequest::getFingerPrint().
doFinal() [2/3]
ByteArray MessageDigest::doFinal (ByteArray & data) throw (MessageDigestException, InvalidStateException)
Realiza atualização do contexto e faz resumo criptográfico.
Equivalente a executar MessageDigest::update(ByteArray &data) e, em seguida, MessageDigest::doFinal().
Parameters
data conteúdo para resumo.
Returns
bytes que representam o resumo calculado.
Exceptions
MessageDigestException caso ocorra erro ao finalizar o contexto de resumo do OpenSSL.
InvalidStateException caso o objeto MessageDigest não tenha sido inicializado corretamente ou caso não tenha sido passado o conteúdo para calculo do resumo.
References doFinal(), and update().
doFinal() [3/3]
ByteArray MessageDigest::doFinal (std::string & data) throw (MessageDigestException, InvalidStateException)
Realiza atualização do contexto e faz resumo criptográfico.
Equivalente a executar MessageDigest::update(ByteArray &data) e, em seguida, MessageDigest::doFinal().
Parameters
data conteúdo para resumo.
Returns
bytes que representam o resumo calculado.
Exceptions
MessageDigestException caso ocorra erro ao finalizar o contexto de resumo do OpenSSL.
InvalidStateException caso o objeto MessageDigest não tenha sido inicializado corretamente ou caso não tenha sido passado o conteúdo para calculo do resumo.
References doFinal(), and update().
getAlgorithm()
MessageDigest::Algorithm MessageDigest::getAlgorithm () throw (InvalidStateException)
Retorna algoritmo de resumo selecionado.
Returns
algoritmo de resumo selecionado.
Exceptions
InvalidStateException caso o objeto MessageDigest não tenha sido inicializado corretamente.
References algorithm, NO_INIT, and state.
getMessageDigest() [1/2]
const EVP_MD * MessageDigest::getMessageDigest (MessageDigest::Algorithm algorithm) static
Retorna a estrutura do OpenSSL que representa o algoritmo de resumo desejado.
Returns
objeto EVP_MD referente ao algoritmo passado.
References MD4, MD5, RIPEMD160, SHA, SHA1, SHA224, SHA256, SHA384, and SHA512.
Referenced by Pkcs7SignedDataBuilder::addSigner(), CertificateRequest::getMessageDigestAlgorithm(), Certificate::getMessageDigestAlgorithm(), CertificateBuilder::getMessageDigestAlgorithm(), Certificate::getNewCertificateRequest(), Pkcs7SignedDataBuilder::init(), init(), Hmac::init(), MessageDigest(), Pkcs7SignedDataBuilder::Pkcs7SignedDataBuilder(), Signer::sign(), CertificateRevocationListBuilder::sign(), CertificateRequest::sign(), NetscapeSPKIBuilder::sign(), CertificateBuilder::sign(), and Signer::verify().
getMessageDigest() [2/2]
MessageDigest::Algorithm MessageDigest::getMessageDigest (int algorithmNid) throw (MessageDigestException) static
Obtem algoritmo de resumo a partir do identificador numérico do algoritmo no OpenSSL.
Returns
objeto MessageDigest::Algorithm relativo ao identificador passado.
Exceptions
MessageDigestException caso o identificador passado seja inválido.
References MessageDigestException::INVALID_ALGORITHM, MD4, MD5, RIPEMD160, SHA, SHA1, SHA224, SHA256, SHA384, and SHA512.
init() [1/2]
void MessageDigest::init (MessageDigest::Algorithm algorithm) throw (MessageDigestException)
Inicializa estruturas de resumos do OpenSSL.
Parameters
algorithm algoritmo de resumo.
Exceptions
MessageDigestException caso ocorra erro ao inicializar a estrutura de resumos do OpenSSL.
References algorithm, ctx, MessageDigestException::CTX_INIT, getMessageDigest(), INIT, NO_INIT, and state.
Referenced by Certificate::getFingerPrint(), and CertificateRequest::getFingerPrint().
init() [2/2]
void MessageDigest::init (MessageDigest::Algorithm algorithm, Engine & engine) throw (MessageDigestException)
Inicializa estruturas de resumos do OpenSSL utilizando uma engine.
Parameters
algorithm algoritmo de resumo.
engine objeto Engine.
Exceptions
MessageDigestException caso ocorra erro ao inicializar a estrutura de resumos do OpenSSL.
References algorithm, ctx, MessageDigestException::CTX_INIT, getMessageDigest(), INIT, NO_INIT, and state.
loadMessageDigestAlgorithms()
void MessageDigest::loadMessageDigestAlgorithms () static
Carrega todos os algoritmos de resumo.
update() [1/2]
void MessageDigest::update (ByteArray & data) throw (MessageDigestException, InvalidStateException)
Define o conteúdo de entrada função de resumo.
Parameters
data conteúdo para resumo.
Exceptions
MessageDigestException caso ocorra erro ao atualizar o contexto de resumo do OpenSSL.
InvalidStateException caso o objeto MessageDigest não tenha sido inicializado corretamente.
References ctx, MessageDigestException::CTX_UPDATE, NO_INIT, state, and UPDATE.
Referenced by doFinal().
update() [2/2]
void MessageDigest::update (std::string & data) throw (MessageDigestException, InvalidStateException)
Define o conteúdo de entrada função de resumo.
Parameters
data conteúdo para resumo.
Exceptions
MessageDigestException caso ocorra erro ao atualizar o contexto de resumo do OpenSSL.
InvalidStateException caso o objeto MessageDigest não tenha sido inicializado corretamente.
References update().
Referenced by update().
Member Data Documentation
algorithm
MessageDigest::Algorithm MessageDigest::algorithm protected
Algoritmo selecionado.
Referenced by getAlgorithm(), init(), and MessageDigest().
ctx
EVP_MD_CTX MessageDigest::ctx protected
Estrutura OpenSSL que representa o algoritmo de resumo.
Referenced by doFinal(), init(), MessageDigest(), update(), and ~MessageDigest().
state
MessageDigest::State MessageDigest::state protected
Estado das estruturas de resumo.
Referenced by doFinal(), getAlgorithm(), init(), MessageDigest(), and update().
The documentation for this class was generated from the following files:
include/libcryptosec/MessageDigest.h
src/MessageDigest.cpp