libcryptosec Documentation
CertificateRequest Class Reference
#include <CertificateRequest.h>
Public Member Functions
CertificateRequest ()
CertificateRequest (X509_REQ *req)
CertificateRequest (std::string &pemEncoded) throw (EncodeException)
CertificateRequest (ByteArray &derEncoded) throw (EncodeException)
CertificateRequest (const CertificateRequest &req)
virtual ~CertificateRequest ()
std::string getXmlEncoded ()
std::string getXmlEncoded (std::string tab)
virtual std::string toXml (std::string tab="")
std::string getPemEncoded () throw (EncodeException)
ByteArray getDerEncoded () const throw (EncodeException)
MessageDigest::Algorithm getMessageDigestAlgorithm () throw (MessageDigestException)
void setVersion (long version)
long getVersion ()
void setPublicKey (PublicKey &publicKey)
PublicKey * getPublicKey () throw (CertificationException, AsymmetricKeyException)
ByteArray getPublicKeyInfo () throw (CertificationException)
void setSubject (RDNSequence &name)
RDNSequence getSubject ()
void addExtension (Extension &extension)
void addExtensions (std::vector< Extension *> &extensions)
void replaceExtension (Extension &extension) throw (CertificationException)
std::vector< Extension * > removeExtension (Extension::Name extensionName) throw (CertificationException)
std::vector< Extension * > removeExtension (ObjectIdentifier extOID) throw (CertificationException)
std::vector< Extension * > getExtension (Extension::Name extensionName)
std::vector< Extension * > getExtensions ()
std::vector< Extension * > getUnknownExtensions ()
ByteArray getFingerPrint (MessageDigest::Algorithm algorithm) const throw (CertificationException, EncodeException, MessageDigestException)
void sign (PrivateKey &privateKey, MessageDigest::Algorithm messageDigestAlgorithm) throw (CertificationException)
virtual bool verify ()
virtual bool isSigned () const throw ()
X509_REQ * getX509Req () const
CertificateRequest & operator= (const CertificateRequest &value)
Protected Attributes
X509_REQ * req
Constructor & Destructor Documentation
CertificateRequest() [1/5]
CertificateRequest::CertificateRequest ()
References req.
CertificateRequest() [2/5]
CertificateRequest::CertificateRequest (X509_REQ * req)
References req.
CertificateRequest() [3/5]
CertificateRequest::CertificateRequest (std::string & pemEncoded) throw (EncodeException)
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_WRITING, EncodeException::PEM_DECODE, and req.
CertificateRequest() [4/5]
CertificateRequest::CertificateRequest (ByteArray & derEncoded) throw (EncodeException)
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_WRITING, EncodeException::DER_DECODE, and req.
CertificateRequest() [5/5]
CertificateRequest::CertificateRequest (const CertificateRequest & req)
References getX509Req().
~CertificateRequest()
CertificateRequest::~CertificateRequest () virtual
References req.
Member Function Documentation
addExtension()
void CertificateRequest::addExtension (Extension & extension)
References Extension::getX509Extension(), and req.
addExtensions()
void CertificateRequest::addExtensions (std::vector< Extension *> & extensions)
References req.
getDerEncoded()
ByteArray CertificateRequest::getDerEncoded () const throw (EncodeException)
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_READING, EncodeException::DER_ENCODE, and req.
Referenced by getFingerPrint().
getExtension()
std::vector< Extension * > CertificateRequest::getExtension (Extension::Name extensionName)
References Extension::AUTHORITY_INFORMATION_ACCESS, Extension::AUTHORITY_KEY_IDENTIFIER, Extension::BASIC_CONSTRAINTS, Extension::CERTIFICATE_POLICIES, Extension::CRL_DISTRIBUTION_POINTS, Extension::EXTENDED_KEY_USAGE, Extension::getName(), Extension::ISSUER_ALTERNATIVE_NAME, Extension::KEY_USAGE, req, Extension::SUBJECT_ALTERNATIVE_NAME, Extension::SUBJECT_INFORMATION_ACCESS, and Extension::SUBJECT_KEY_IDENTIFIER.
getExtensions()
std::vector< Extension * > CertificateRequest::getExtensions ()
References Extension::AUTHORITY_INFORMATION_ACCESS, Extension::AUTHORITY_KEY_IDENTIFIER, Extension::BASIC_CONSTRAINTS, Extension::CERTIFICATE_POLICIES, Extension::CRL_DISTRIBUTION_POINTS, Extension::EXTENDED_KEY_USAGE, Extension::getName(), Extension::ISSUER_ALTERNATIVE_NAME, Extension::KEY_USAGE, req, Extension::SUBJECT_ALTERNATIVE_NAME, Extension::SUBJECT_INFORMATION_ACCESS, and Extension::SUBJECT_KEY_IDENTIFIER.
Referenced by CertificateBuilder::CertificateBuilder(), getXmlEncoded(), and toXml().
getFingerPrint()
ByteArray CertificateRequest::getFingerPrint (MessageDigest::Algorithm algorithm) const throw (CertificationException, EncodeException, MessageDigestException)
References MessageDigest::doFinal(), getDerEncoded(), and MessageDigest::init().
getMessageDigestAlgorithm()
MessageDigest::Algorithm CertificateRequest::getMessageDigestAlgorithm () throw (MessageDigestException)
References MessageDigest::getMessageDigest(), and req.
getPemEncoded()
std::string CertificateRequest::getPemEncoded () throw (EncodeException)
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_READING, EncodeException::PEM_ENCODE, req, and ByteArray::toString().
getPublicKey()
PublicKey * CertificateRequest::getPublicKey () throw (CertificationException, AsymmetricKeyException)
References req, and CertificationException::SET_NO_VALUE.
Referenced by CertificateBuilder::CertificateBuilder(), sign(), and verify().
getPublicKeyInfo()
ByteArray CertificateRequest::getPublicKeyInfo () throw (CertificationException)
References ByteArray::getDataPointer(), req, and CertificationException::SET_NO_VALUE.
Referenced by getXmlEncoded(), and toXml().
getSubject()
RDNSequence CertificateRequest::getSubject ()
References req.
Referenced by getXmlEncoded(), and toXml().
getUnknownExtensions()
std::vector< Extension * > CertificateRequest::getUnknownExtensions ()
References Extension::getName(), req, and Extension::UNKNOWN.
getVersion()
long CertificateRequest::getVersion ()
References req.
Referenced by getXmlEncoded(), and toXml().
getX509Req()
X509_REQ * CertificateRequest::getX509Req () const
References req.
Referenced by CertificateBuilder::CertificateBuilder(), CertificateRequest(), and operator=().
getXmlEncoded() [1/2]
std::string CertificateRequest::getXmlEncoded ()
Deprecated:
Retorna o conteudo da extensão em formato XML.
Esta função será substituida por toXml().
getXmlEncoded() [2/2]
std::string CertificateRequest::getXmlEncoded (std::string tab)
References Base64::encode(), getExtensions(), getPublicKeyInfo(), getSubject(), getVersion(), and RDNSequence::getXmlEncoded().
isSigned()
bool CertificateRequest::isSigned () const throw () virtual
Reimplemented in CertificateRequestSPKAC.
References req.
operator=()
CertificateRequest & CertificateRequest::operator= (const CertificateRequest & value)
References getX509Req(), and req.
removeExtension() [1/2]
std::vector< Extension * > CertificateRequest::removeExtension (Extension::Name extensionName) throw (CertificationException)
References Extension::AUTHORITY_INFORMATION_ACCESS, Extension::AUTHORITY_KEY_IDENTIFIER, Extension::BASIC_CONSTRAINTS, Extension::CERTIFICATE_POLICIES, Extension::CRL_DISTRIBUTION_POINTS, Extension::EXTENDED_KEY_USAGE, Extension::getName(), Extension::ISSUER_ALTERNATIVE_NAME, Extension::KEY_USAGE, req, Extension::SUBJECT_ALTERNATIVE_NAME, Extension::SUBJECT_INFORMATION_ACCESS, and Extension::SUBJECT_KEY_IDENTIFIER.
Referenced by removeExtension().
removeExtension() [2/2]
std::vector< Extension * > CertificateRequest::removeExtension (ObjectIdentifier extOID) throw (CertificationException)
References Extension::getName(), and removeExtension().
replaceExtension()
void CertificateRequest::replaceExtension (Extension & extension) throw (CertificationException)
References CertificationException::ADDING_EXTENSION, and req.
setPublicKey()
void CertificateRequest::setPublicKey (PublicKey & publicKey)
References AsymmetricKey::getEvpPkey(), and req.
Referenced by CertificateRequestSPKAC::CertificateRequestSPKAC().
setSubject()
void CertificateRequest::setSubject (RDNSequence & name)
References RDNSequence::getX509Name(), and req.
setVersion()
void CertificateRequest::setVersion (long version)
References req.
sign()
void CertificateRequest::sign (PrivateKey & privateKey, MessageDigest::Algorithm messageDigestAlgorithm) throw (CertificationException)
References MessageDigest::getMessageDigest(), getPublicKey(), CertificationException::INTERNAL_ERROR, and req.
toXml()
std::string CertificateRequest::toXml (std::string tab = "") virtual
References Base64::encode(), getExtensions(), getPublicKeyInfo(), getSubject(), getVersion(), and RDNSequence::getXmlEncoded().
verify()
bool CertificateRequest::verify () virtual
Reimplemented in CertificateRequestSPKAC.
References AsymmetricKey::getEvpPkey(), getPublicKey(), and req.
Member Data Documentation
req
X509_REQ* CertificateRequest::req protected
Referenced by addExtension(), addExtensions(), CertificateRequest(), getDerEncoded(), getExtension(), getExtensions(), getMessageDigestAlgorithm(), getPemEncoded(), getPublicKey(), getPublicKeyInfo(), getSubject(), getUnknownExtensions(), getVersion(), getX509Req(), isSigned(), operator=(), removeExtension(), replaceExtension(), setPublicKey(), setSubject(), setVersion(), sign(), verify(), and ~CertificateRequest().
The documentation for this class was generated from the following files:
include/libcryptosec/certificate/CertificateRequest.h
src/certificate/CertificateRequest.cpp