libcryptosec Documentation
AsymmetricCipher Class Reference
Classes Relacionadas Utilitárias de Criptografia
static class to perform asymmetric ciphers, using asymmetric keys (eg.
#include <AsymmetricCipher.h>
Public Types
enum Padding { NO_PADDING, PKCS1, SSLV23, PKCS1_OAEP }
supported padding values to perform asymmetric ciphers.
Static Public Member Functions
static ByteArray encrypt (RSAPublicKey &key, ByteArray &data, AsymmetricCipher::Padding padding) throw (AsymmetricCipherException)
encrypt unreadable data using a asymmetric public key
static ByteArray encrypt (RSAPublicKey &key, std::string &data, AsymmetricCipher::Padding padding) throw (AsymmetricCipherException)
encrypt readable data using a asymmetric public key
static ByteArray decrypt (RSAPrivateKey &key, ByteArray &data, AsymmetricCipher::Padding padding) throw (AsymmetricCipherException)
decrypt encrypted data using a asymmetric private key
Detailed Description
static class to perform asymmetric ciphers, using asymmetric keys (eg.
RSA keys)
Member Enumeration Documentation
Padding
enum AsymmetricCipher::Padding
supported padding values to perform asymmetric ciphers.
Default: PKCS1.
Enumerator
NO_PADDING
PKCS1
SSLV23
PKCS1_OAEP
Member Function Documentation
decrypt()
ByteArray AsymmetricCipher::decrypt (RSAPrivateKey & key, ByteArray & data, AsymmetricCipher::Padding padding) throw (AsymmetricCipherException) static
decrypt encrypted data using a asymmetric private key
Parameters
key private key to decrypt encrypted data
data data to be decrypted type of padding to use in process (must be the same used to perform the encrypting operation
Returns
encrypted data
Exceptions
AsymmetricCipherException if any problem happen, throw this exception with a ENCRYPTING_DATA code.
References AsymmetricCipherException::DECRYPTING_DATA, ByteArray::getDataPointer(), NO_PADDING, PKCS1, PKCS1_OAEP, and SSLV23.
encrypt() [1/2]
ByteArray AsymmetricCipher::encrypt (RSAPublicKey & key, ByteArray & data, AsymmetricCipher::Padding padding) throw (AsymmetricCipherException) static
encrypt unreadable data using a asymmetric public key
Parameters
key public key to encrypt data
data data to be encrypted type of padding to use in process
Returns
encrypted data
Exceptions
AsymmetricCipherException if any problem happen, throw this exception with a ENCRYPTING_DATA code.
References AsymmetricCipherException::ENCRYPTING_DATA, and ByteArray::getDataPointer().
encrypt() [2/2]
ByteArray AsymmetricCipher::encrypt (RSAPublicKey & key, std::string & data, AsymmetricCipher::Padding padding) throw (AsymmetricCipherException) static
encrypt readable data using a asymmetric public key
Parameters
key public key to encrypt data
data data to be encrypted type of padding to use in process
Returns
encrypted data
Exceptions
AsymmetricCipherException if any problem happen, throw this exception with a ENCRYPTING_DATA code.
References AsymmetricCipherException::ENCRYPTING_DATA, and ByteArray::getDataPointer().
The documentation for this class was generated from the following files:
include/libcryptosec/AsymmetricCipher.h
src/AsymmetricCipher.cpp