libcryptosec Documentation
ByteArray Class Reference
Classes Relacionadas Utilitárias de Criptografia
Classe usada para transportar dados binários pelo sistema.
#include <ByteArray.h>
Public Member Functions
ByteArray ()
Default constructor.
ByteArray (unsigned int length)
ByteArray com tamanho definido.
ByteArray (const unsigned char *data, unsigned int length)
ByteArray a partir do buffer desejado, copiando os dados.
ByteArray (std::ostringstream *buffer)
ByteArray a partir de ostringstream copiando os dados.
ByteArray (std::string data)
ByteArray a partir de dados legíveis.
ByteArray (char *data)
ByteArray (int length)
ByteArray com tamanho definido.
ByteArray (const ByteArray &value)
ByteArray a partir de outro ByteArray (que será copiado).
virtual ~ByteArray ()
Deafult destructor.
char at (int pos) const throw (out_of_range)
Ler o byte da posição desejada.
ByteArray & operator= (const ByteArray &value)
Fazer uma cópia profunda ao invés de copiar a referência.
unsigned char & operator[] (int pos) throw (out_of_range)
Ler o byte da posição desejada.
void copyFrom (unsigned char *data, unsigned int length)
Copy bytes from desired memory location.
void copyFrom (int offset, int length, ByteArray &data, int offset2)
Copy bytes from desired ByteArray, considering an offset.
std::istringstream * toStream ()
Returns an istringstream representing current byte array.
void setDataPointer (unsigned char *data, unsigned int length)
Set the content of ByteArray to be an already allocated memory space.
unsigned char * getDataPointer ()
Returns the memory location of byte array content.
unsigned int size () const
Returns the memory location of byte array content.
virtual std::string toString ()
Consider that current byte array is a char array, and retuirns it as a QString.
virtual std::string toHex ()
Converts the content of this bytearray to hexadecimal value.
virtual std::string toHex (char separator)
Converts the content of this bytearray to hexadecimal value separated using the char informed as argument.
Static Public Member Functions
static ByteArray xOr (vector< ByteArray > &array)
Computes multiple xor of vector elements.
Friends
bool operator== (const ByteArray &left, const ByteArray &right)
Permitir comparação booleana de ByteArray's.
bool operator!= (const ByteArray &left, const ByteArray &right)
Permitir diferença booleana de ByteArray's.
ByteArray & operator xor (const ByteArray &left, const ByteArray &right)
Fazer ou-exclusivo entre dois ByteArray's.
Detailed Description
Classe usada para transportar dados binários pelo sistema.
Pode ser usada para conversão de texto em array de bytes e vice-versa. Usar esta classe ao invés do QByteArray por causa do uso de "unsigned char", e pela possibilidade de fazer "cópias profundas" dos dados.
Constructor & Destructor Documentation
ByteArray() [1/8]
ByteArray::ByteArray ()
Default constructor.
Referenced by operator xor().
ByteArray() [2/8]
ByteArray::ByteArray (unsigned int length)
ByteArray com tamanho definido.
Parameters
length Tamanho do novo ByteArray.
ByteArray() [3/8]
ByteArray::ByteArray (const unsigned char * data, unsigned int length)
ByteArray a partir do buffer desejado, copiando os dados.
Parameters
data Buffer de origem dos bytes.
length Tamanho do buffer.
ByteArray() [4/8]
ByteArray::ByteArray (std::ostringstream * buffer)
ByteArray a partir de ostringstream copiando os dados.
Parameters
buffer ostream com os dados para colocar no ByteArray
ByteArray() [5/8]
ByteArray::ByteArray (std::string data)
ByteArray a partir de dados legíveis.
Parameters
data dados que serão colocados no objeto
ByteArray() [6/8]
ByteArray::ByteArray (char * data)
ByteArray() [7/8]
ByteArray::ByteArray (int length)
ByteArray com tamanho definido.
Parameters
length Tamanho do novo ByteArray.
ByteArray() [8/8]
ByteArray::ByteArray (const ByteArray & value)
ByteArray a partir de outro ByteArray (que será copiado).
Parameters
value ByteArray de origem.
~ByteArray()
ByteArray::~ByteArray () virtual
Deafult destructor.
Member Function Documentation
at()
char ByteArray::at (int pos) const throw (out_of_range)
Ler o byte da posição desejada.
Parameters
pos Posição desejada.
Referenced by operator xor().
copyFrom() [1/2]
void ByteArray::copyFrom (unsigned char * data, unsigned int length)
Copy bytes from desired memory location.
Parameters
data Desired memory location.
length Amount to copy.
copyFrom() [2/2]
void ByteArray::copyFrom (int offset, int length, ByteArray & data, int offset2)
Copy bytes from desired ByteArray, considering an offset.
Parameters
offset Offset to consider for copying.
length Amount to copy.
data Desired ByteArray.
offset2 Offset to consider for copy begin in data.
getDataPointer()
unsigned char * ByteArray::getDataPointer ()
Returns the memory location of byte array content.
Referenced by Random::bytes(), ECDSAKeyPair::createGroup(), Base64::decode(), AsymmetricCipher::decrypt(), SmartcardSlot::decrypt(), Pkcs7Builder::doFinal(), SymmetricCipher::doFinal(), Base64::encode(), AsymmetricCipher::encrypt(), PublicKey::getKeyIdentifier(), SymmetricCipher::getOperation(), CertificateRequest::getPublicKeyInfo(), Certificate::getPublicKeyInfo(), CertificateBuilder::getPublicKeyInfo(), SubjectKeyIdentifierExtension::getX509Extension(), AuthorityKeyIdentifierExtension::getX509Extension(), Extension::getX509Extension(), SymmetricCipher::init(), PrivateKey::passphraseCallBack(), KeyPair::passphraseCallBack(), Random::pseudoBytes(), Random::seedData(), Signer::sign(), SymmetricCipher::SymmetricCipher(), and SymmetricCipher::update().
operator=()
ByteArray & ByteArray::operator= (const ByteArray & value)
Fazer uma cópia profunda ao invés de copiar a referência.
Parameters
value ByteArray a ser copiado.
operator[]()
unsigned char & ByteArray::operator[] (int pos) throw (out_of_range)
Ler o byte da posição desejada.
Parameters
pos Posição desejada.
setDataPointer()
void ByteArray::setDataPointer (unsigned char * data, unsigned int length)
Set the content of ByteArray to be an already allocated memory space.
Parameters
data Desired memory location.
length Length of allocated memory.
Referenced by Hmac::doFinal(), and BigInteger::getBinValue().
size()
unsigned int ByteArray::size () const
Returns the memory location of byte array content.
Returns the byte array content encoded as base 64 characters. Returns the size of current byte array.
Referenced by ECDSAKeyPair::createGroup(), Base64::decode(), SymmetricCipher::doFinal(), Base64::encode(), AuthorityKeyIdentifierExtension::extValue2Xml(), SymmetricCipher::getOperation(), SymmetricKey::getSize(), SubjectKeyIdentifierExtension::getX509Extension(), AuthorityKeyIdentifierExtension::getX509Extension(), Extension::getX509Extension(), AuthorityKeyIdentifierExtension::getXmlEncoded(), operator xor(), PrivateKey::passphraseCallBack(), KeyPair::passphraseCallBack(), Random::seedData(), and SymmetricCipher::update().
toHex() [1/2]
std::string ByteArray::toHex () virtual
Converts the content of this bytearray to hexadecimal value.
toHex() [2/2]
std::string ByteArray::toHex (char separator) virtual
Converts the content of this bytearray to hexadecimal value separated using the char informed as argument.
toStream()
std::istringstream * ByteArray::toStream ()
Returns an istringstream representing current byte array.
toString()
std::string ByteArray::toString () virtual
Consider that current byte array is a char array, and retuirns it as a QString.
Referenced by OpenSSLErrorHandler::getErrors(), CertificateRevocationList::getPemEncoded(), CertificateBuilder::getPemEncoded(), Certificate::getPemEncoded(), CertificateRequest::getPemEncoded(), PublicKey::getPemEncoded(), PrivateKey::getPemEncoded(), Pkcs7::getPemEncoded(), KeyPair::getPemEncoded(), and KeyPair::getPublicKeyPemEncoded().
xOr()
ByteArray ByteArray::xOr (vector< ByteArray > & array) static
Computes multiple xor of vector elements.
Friends And Related Function Documentation
operator xor
ByteArray& operator xor (const ByteArray & left, const ByteArray & right) friend
Fazer ou-exclusivo entre dois ByteArray's.
Parameters
left Primeiro ByteArray da operação.
right Segundo ByteArray da operação.
operator!=
bool operator!= (const ByteArray & left, const ByteArray & right) friend
Permitir diferença booleana de ByteArray's.
Parameters
left Primeiro ByteArray da comparação.
right Segundo ByteArray da comparação.
operator==
bool operator== (const ByteArray & left, const ByteArray & right) friend
Permitir comparação booleana de ByteArray's.
Parameters
left Primeiro ByteArray da comparação.
right Segundo ByteArray da comparação.
The documentation for this class was generated from the following files:
include/libcryptosec/ByteArray.h
src/ByteArray.cpp