libcryptosec Documentation
PrivateKey Class Reference
Classes relacionadas ao uso de chaves assimétricas.
Representa uma chave privada.
#include <PrivateKey.h>
Public Member Functions
PrivateKey (EVP_PKEY *key) throw (AsymmetricKeyException)
Construtor para uso interno recebendo um ponteiro para a estrutura OpenSSL EVP_PKEY.
PrivateKey (ByteArray &derEncoded) throw (EncodeException)
Construtor recebendo a representação da chave privada no formato DER.
PrivateKey (std::string &pemEncoded) throw (EncodeException)
Construtor recebendo a representação da chave privada no formato PEM.
PrivateKey (std::string &pemEncoded, ByteArray &passphrase) throw (EncodeException)
Construtor recebendo a representação da chave privada no formato PEM protegida por uma senha.
virtual ~PrivateKey ()
Destrutor padrão, limpa a estrutura interna EVP_PKEY.
std::string getPemEncoded () throw (EncodeException)
Retorna a representação da chave no formato PEM.
std::string getPemEncoded (SymmetricKey &passphrase, SymmetricCipher::OperationMode mode) throw (SymmetricCipherException, EncodeException)
Retorna a representação da chave no formato PEM cifrada com uma senha.
ByteArray getDerEncoded () throw (EncodeException)
Retorna a representação da chave no formato DER.
bool operator== (PrivateKey &priv) throw ()
Public Member Functions inherited from AsymmetricKey
AsymmetricKey (EVP_PKEY *key) throw (AsymmetricKeyException)
Construtor padrão recebendo um ponteiro para a estrutura OpenSSL EVP_PKEY.
AsymmetricKey (ByteArray &encoded)
Carrega uma chave assimétrica a partir da sua equivalente codificada em DER.
AsymmetricKey (std::string &encoded)
Carrega uma chave assimétrica a partir da sua equivalente codificada em PEM.
virtual ~AsymmetricKey ()
Destrutor padrão.
AsymmetricKey::Algorithm getAlgorithm () throw (AsymmetricKeyException)
Retorna o algoritmo assimétrico que deve ser usado com a chave atual.
int getSize () throw (AsymmetricKeyException)
Retorna o tamanho da chave em bytes.
int getSizeBits () throw (AsymmetricKeyException)
Retorna o tamanho da chave em bits.
EVP_PKEY * getEvpPkey ()
Uso interno.
Static Protected Member Functions
static int passphraseCallBack (char *buf, int size, int rwflag, void *u)
Método usado em formas alternativas de obter a senha para abrir a chave privada.
Additional Inherited Members
Public Types inherited from AsymmetricKey
enum Algorithm { RSA, DSA, ECDSA }
Algoritmos assimétricos suportados.
enum Curve {
X962_PRIME192V1 = 409, X962_PRIME192V2 = 410, X962_PRIME192V3 = 411, X962_PRIME239V1 = 412,
X962_PRIME239V2 = 413, X962_PRIME239V3 = 414, X962_PRIME256V1 = 415, X962_C2PNB163V1 = 684,
X962_C2PNB163V2 = 685, X962_C2PNB163V3 = 686, X962_C2PNB176V1 = 687, X962_C2TNB191V1 = 688,
X962_C2TNB191V2 = 689, X962_C2TNB191V3 = 690, X962_C2PNB208W1 = 693, X962_C2TNB239V1 = 694,
X962_C2TNB239V2 = 695, X962_C2TNB239V3 = 696, X962_C2PNB272W1 = 699, X962_C2PNB304W1 = 700,
X962_C2TNB359V1 = 701, X962_C2PNB368W1 = 702, X962_C2TNB431R1 = 703, SECG_SECP160K1 = 708,
SECG_SECP160R1 = 709, SECG_SECP160R2 = 710, SECG_SECP192K1 = 711, SECG_SECP224K1 = 712,
SECG_SECP256K1 = 714, SECG_SECT163R1 = 722, SECG_SECT193R1 = 724, SECG_SECT193R2 = 725,
SECG_SECT239K1 = 728, NISTSECG_SECP224R1 = 713, NISTSECG_SECP384R1 = 715, NISTSECG_SECP521R1 = 716,
NISTSECG_SECT163K1 = 721, NISTSECG_SECT163R2 = 723, NISTSECG_SECT233K1 = 726, NISTSECG_SECT233R1 = 727,
NISTSECG_SECT283K1 = 729, NISTSECG_SECT283R1 = 730, NISTSECG_SECT409K1 = 731, NISTSECG_SECT409R1 = 732,
NISTSECG_SECT571K1 = 733, NISTSECG_SECT571R1 = 734, BRAINPOOL_P160R1 = 921, BRAINPOOL_P160T1 = 922,
BRAINPOOL_P192R1 = 923, BRAINPOOL_P192T1 = 924, BRAINPOOL_P224R1 = 925, BRAINPOOL_P224T1 = 926,
BRAINPOOL_P256R1 = 927, BRAINPOOL_P256T1 = 928, BRAINPOOL_P320R1 = 929, BRAINPOOL_P320T1 = 930,
BRAINPOOL_P384R1 = 931, BRAINPOOL_P384T1 = 932, BRAINPOOL_P512R1 = 933, BRAINPOOL_P512T1 = 934
}
Curvas Elipticas suportadas (= NID)
Protected Attributes inherited from AsymmetricKey
EVP_PKEY * key
Ponteiro para a estrutura interna OpenSSL EVP_PKEY.
Detailed Description
Representa uma chave privada.
Para a criação de chaves assimetricas a classe KeyPair deve ser consultada.
See also
KeyPair
Constructor & Destructor Documentation
PrivateKey() [1/4]
PrivateKey::PrivateKey (EVP_PKEY * key) throw (AsymmetricKeyException)
Construtor para uso interno recebendo um ponteiro para a estrutura OpenSSL EVP_PKEY.
Parameters
key ponteiro para a estrutura OpenSSL EVP_PKEY.
Exceptions
AsymmetricKeyException caso a estrutura EVP_PKEY não seja uma estrutura OpenSSL válida ou ocorra algum problema na sua carga.
References AsymmetricKeyException::INVALID_ASYMMETRIC_KEY.
PrivateKey() [2/4]
PrivateKey::PrivateKey (ByteArray & derEncoded) throw (EncodeException)
Construtor recebendo a representação da chave privada no formato DER.
Parameters
derEncoded chave privada codificada no formato DER.
Exceptions
EncodeException caso tenha ocorrido um erro com a decodificação do DER.
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_WRITING, and EncodeException::DER_DECODE.
PrivateKey() [3/4]
PrivateKey::PrivateKey (std::string & pemEncoded) throw (EncodeException)
Construtor recebendo a representação da chave privada no formato PEM.
Parameters
pemEncoded chave privada codificada no formato PEM.
Exceptions
EncodeException caso tenha ocorrido um erro com a decodificação do PEM.
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_WRITING, and EncodeException::PEM_DECODE.
PrivateKey() [4/4]
PrivateKey::PrivateKey (std::string & pemEncoded, ByteArray & passphrase) throw (EncodeException)
Construtor recebendo a representação da chave privada no formato PEM protegida por uma senha.
Parameters
pemEncoded chave privada codificada no formato PEM protegida por uma senha.
passphrase senha que permitirá a decodificação e abertura da chave.
Exceptions
EncodeException caso tenha ocorrido um erro com a decodificação do PEM.
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_WRITING, passphraseCallBack(), and EncodeException::PEM_DECODE.
~PrivateKey()
PrivateKey::~PrivateKey () virtual
Destrutor padrão, limpa a estrutura interna EVP_PKEY.
Member Function Documentation
getDerEncoded()
ByteArray PrivateKey::getDerEncoded () throw (EncodeException) virtual
Retorna a representação da chave no formato DER.
Returns
a chave privada codificada em DER.
Exceptions
EncodeException caso ocorra um erro na codificação da chave.
Implements AsymmetricKey.
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_READING, EncodeException::DER_ENCODE, and AsymmetricKey::key.
getPemEncoded() [1/2]
std::string PrivateKey::getPemEncoded () throw (EncodeException) virtual
Retorna a representação da chave no formato PEM.
Returns
a chave privada codificada em PEM.
Exceptions
EncodeException caso ocorra um erro na codificação da chave.
Implements AsymmetricKey.
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_READING, AsymmetricKey::key, EncodeException::PEM_ENCODE, and ByteArray::toString().
getPemEncoded() [2/2]
std::string PrivateKey::getPemEncoded (SymmetricKey & passphrase, SymmetricCipher::OperationMode mode) throw (SymmetricCipherException, EncodeException)
Retorna a representação da chave no formato PEM cifrada com uma senha.
Parameters
passphrase a senha que cifrará a chave codificada em PEM.
mode o algoritmo simétrico que será usado para proteger a chave privada.
Returns
a chave privada codificada em PEM.
Exceptions
EncodeException caso ocorra um erro na codificação da chave.
SymmetricCipherException caso o algoritmo escolhido não seja suportado ou seja inválido.
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_READING, SymmetricCipher::getCipher(), AsymmetricKey::key, passphraseCallBack(), EncodeException::PEM_ENCODE, and ByteArray::toString().
operator==()
bool PrivateKey::operator== (PrivateKey & priv) throw ()
References AsymmetricKey::getEvpPkey().
passphraseCallBack()
int PrivateKey::passphraseCallBack (char * buf, int size, int rwflag, void * u) static protected
Método usado em formas alternativas de obter a senha para abrir a chave privada.
Parameters
buf
size
rwflag
u
References ByteArray::getDataPointer(), and ByteArray::size().
Referenced by getPemEncoded(), and PrivateKey().
The documentation for this class was generated from the following files:
include/libcryptosec/PrivateKey.h
src/PrivateKey.cpp