libcryptosec Documentation
EllipticCurve Class Reference
Classes Relacionadas Utilitárias de Criptografia
Classe usada para representar curvas elípticas.
#include <EllipticCurve.h>
Public Member Functions
EllipticCurve ()
EllipticCurve (ByteArray &encoded)
Cria uma curva elíptica a partir da descrição de seus parâmetros codificados em DER.
EllipticCurve (std::string &encoded)
Cria uma curva elíptica a partir da descrição de seus parâmetros codificados em PEM.
~EllipticCurve ()
const BIGNUM * BN_a () const throw ()
const BIGNUM * BN_b () const throw ()
const BIGNUM * BN_p () const throw ()
const BIGNUM * BN_x () const throw ()
const BIGNUM * BN_y () const throw ()
const BIGNUM * BN_order () const throw ()
const BIGNUM * BN_cofactor () const throw ()
const BigInteger getA () const
void setA (const BigInteger a)
void setA (const std::string hex)
const BigInteger getB () const
void setB (const BigInteger b)
void setB (const std::string hex)
const BigInteger getCofactor () const
void setCofactor (const BigInteger cofactor)
void setCofactor (const std::string hex)
const std::string getName () const
void setName (const std::string name)
const std::string getOid () const
void setOid (const std::string oid)
const BigInteger getOrder () const
void setOrder (const BigInteger order)
void setOrder (const std::string hex)
const BigInteger getP () const
void setP (const BigInteger p)
void setP (const std::string hex)
const BigInteger getX () const
void setX (const BigInteger x)
void setX (const std::string hex)
const BigInteger getY () const
void setY (const BigInteger y)
void setY (const std::string hex)
Protected Attributes
std::string oid
std::string name
BigInteger a
BigInteger b
BigInteger p
BigInteger x
BigInteger y
BigInteger order
BigInteger cofactor
Static Protected Attributes
static const std::string notSpecified = "Not Specified"
Detailed Description
Classe usada para representar curvas elípticas.
Esta classe possui funções para que os parâmetros das curvas sejam obtidos ou gerados a partir de um arquivo em PEM/DER
Constructor & Destructor Documentation
EllipticCurve() [1/3]
EllipticCurve::EllipticCurve ()
EllipticCurve() [2/3]
EllipticCurve::EllipticCurve (ByteArray & encoded)
Cria uma curva elíptica a partir da descrição de seus parâmetros codificados em DER.
Parameters
encoded parâmetros de curva o formato DER.
EllipticCurve() [3/3]
EllipticCurve::EllipticCurve (std::string & encoded)
Cria uma curva elíptica a partir da descrição de seus parâmetros codificados em PEM.
Parameters
encoded parâmetros de curva o formato PEM.
~EllipticCurve()
EllipticCurve::~EllipticCurve ()
Member Function Documentation
BN_a()
const BIGNUM * EllipticCurve::BN_a () const throw ()
References a, and BigInteger::getBIGNUM().
Referenced by ECDSAKeyPair::createGroup().
BN_b()
const BIGNUM * EllipticCurve::BN_b () const throw ()
References b, and BigInteger::getBIGNUM().
Referenced by ECDSAKeyPair::createGroup().
BN_cofactor()
const BIGNUM * EllipticCurve::BN_cofactor () const throw ()
References cofactor, and BigInteger::getBIGNUM().
Referenced by ECDSAKeyPair::createGroup().
BN_order()
const BIGNUM * EllipticCurve::BN_order () const throw ()
References BigInteger::getBIGNUM(), and order.
Referenced by ECDSAKeyPair::createGroup().
BN_p()
const BIGNUM * EllipticCurve::BN_p () const throw ()
References BigInteger::getBIGNUM(), and p.
Referenced by ECDSAKeyPair::createGroup().
BN_x()
const BIGNUM * EllipticCurve::BN_x () const throw ()
References BigInteger::getBIGNUM(), and x.
Referenced by ECDSAKeyPair::createGroup().
BN_y()
const BIGNUM * EllipticCurve::BN_y () const throw ()
References BigInteger::getBIGNUM(), and y.
Referenced by ECDSAKeyPair::createGroup().
getA()
const BigInteger EllipticCurve::getA () const
References a.
getB()
const BigInteger EllipticCurve::getB () const
References b.
getCofactor()
const BigInteger EllipticCurve::getCofactor () const
References cofactor.
getName()
const std::string EllipticCurve::getName () const
References name.
getOid()
const std::string EllipticCurve::getOid () const
References oid.
getOrder()
const BigInteger EllipticCurve::getOrder () const
References order.
getP()
const BigInteger EllipticCurve::getP () const
References p.
getX()
const BigInteger EllipticCurve::getX () const
References x.
getY()
const BigInteger EllipticCurve::getY () const
References y.
setA() [1/2]
void EllipticCurve::setA (const BigInteger a)
References a.
Referenced by BrainpoolCurveFactory::getCurve().
setA() [2/2]
void EllipticCurve::setA (const std::string hex)
References a, and BigInteger::setHexValue().
setB() [1/2]
void EllipticCurve::setB (const BigInteger b)
References b.
Referenced by BrainpoolCurveFactory::getCurve().
setB() [2/2]
void EllipticCurve::setB (const std::string hex)
References b, and BigInteger::setHexValue().
setCofactor() [1/2]
void EllipticCurve::setCofactor (const BigInteger cofactor)
References cofactor.
Referenced by BrainpoolCurveFactory::getCurve().
setCofactor() [2/2]
void EllipticCurve::setCofactor (const std::string hex)
References cofactor, and BigInteger::setHexValue().
setName()
void EllipticCurve::setName (const std::string name)
References name.
Referenced by BrainpoolCurveFactory::getCurve().
setOid()
void EllipticCurve::setOid (const std::string oid)
References oid.
setOrder() [1/2]
void EllipticCurve::setOrder (const BigInteger order)
References order.
Referenced by BrainpoolCurveFactory::getCurve().
setOrder() [2/2]
void EllipticCurve::setOrder (const std::string hex)
References order, and BigInteger::setHexValue().
setP() [1/2]
void EllipticCurve::setP (const BigInteger p)
References p.
Referenced by BrainpoolCurveFactory::getCurve().
setP() [2/2]
void EllipticCurve::setP (const std::string hex)
References p, and BigInteger::setHexValue().
setX() [1/2]
void EllipticCurve::setX (const BigInteger x)
References x.
Referenced by BrainpoolCurveFactory::getCurve().
setX() [2/2]
void EllipticCurve::setX (const std::string hex)
References BigInteger::setHexValue(), and x.
setY() [1/2]
void EllipticCurve::setY (const BigInteger y)
References y.
Referenced by BrainpoolCurveFactory::getCurve().
setY() [2/2]
void EllipticCurve::setY (const std::string hex)
References BigInteger::setHexValue(), and y.
Member Data Documentation
a
BigInteger EllipticCurve::a protected
Referenced by BN_a(), getA(), and setA().
b
BigInteger EllipticCurve::b protected
Referenced by BN_b(), getB(), and setB().
cofactor
BigInteger EllipticCurve::cofactor protected
Referenced by BN_cofactor(), getCofactor(), and setCofactor().
name
std::string EllipticCurve::name protected
Referenced by getName(), and setName().
notSpecified
const std::string EllipticCurve::notSpecified = "Not Specified" static protected
oid
std::string EllipticCurve::oid protected
Referenced by getOid(), and setOid().
order
BigInteger EllipticCurve::order protected
Referenced by BN_order(), getOrder(), and setOrder().
p
BigInteger EllipticCurve::p protected
Referenced by BN_p(), getP(), and setP().
x
BigInteger EllipticCurve::x protected
Referenced by BN_x(), getX(), and setX().
y
BigInteger EllipticCurve::y protected
Referenced by BN_y(), getY(), and setY().
The documentation for this class was generated from the following files:
include/libcryptosec/ec/EllipticCurve.h
src/ec/EllipticCurve.cpp