libcryptosec Documentation
SmartcardModuleException Class Reference
#include <SmartcardModuleException.h>
Public Types
enum ErrorCode {
UNKNOWN = 1, ENUMERATING_CERTIFICATES = 2, ENUMERATING_PRIVATE_KEYS = 3, DECRYPTING_DATA = 4,
SMARTCARD_NOT_AVAILABLE = 5, SMARTCARD_READER_NOT_AVAILABLE = 6, INVALID_PIN = 0x000000A0, INVALID_PKCS11_MODULE = 8,
BLOCKED_PIN = 0x000000A4, ID_NOT_FOUND = 9
}
Public Member Functions
SmartcardModuleException (std::string where)
SmartcardModuleException (SmartcardModuleException::ErrorCode errorCode, std::string where)
SmartcardModuleException (SmartcardModuleException::ErrorCode errorCode, std::string where, bool opensslDetails)
virtual ~SmartcardModuleException () throw ()
virtual std::string getMessage () const
virtual std::string toString () const
virtual SmartcardModuleException::ErrorCode getErrorCode ()
Public Member Functions inherited from LibCryptoSecException
virtual ~LibCryptoSecException () throw ()
virtual const char * what () const throw ()
virtual const std::string getDetails () const throw ()
Static Public Member Functions
static std::string errorCode2Message (SmartcardModuleException::ErrorCode errorCode)
Protected Attributes
SmartcardModuleException::ErrorCode errorCode
Protected Attributes inherited from LibCryptoSecException
std::string where
std::string details
Member Enumeration Documentation
ErrorCode
enum SmartcardModuleException::ErrorCode
Enumerator
UNKNOWN
ENUMERATING_CERTIFICATES
ENUMERATING_PRIVATE_KEYS
DECRYPTING_DATA
SMARTCARD_NOT_AVAILABLE
SMARTCARD_READER_NOT_AVAILABLE
INVALID_PIN
INVALID_PKCS11_MODULE
BLOCKED_PIN
ID_NOT_FOUND
Constructor & Destructor Documentation
SmartcardModuleException() [1/3]
SmartcardModuleException::SmartcardModuleException (std::string where) inline
References LibCryptoSecException::details, errorCode, UNKNOWN, and LibCryptoSecException::where.
SmartcardModuleException() [2/3]
SmartcardModuleException::SmartcardModuleException (SmartcardModuleException::ErrorCode errorCode, std::string where) inline
References LibCryptoSecException::details, errorCode, and LibCryptoSecException::where.
SmartcardModuleException() [3/3]
SmartcardModuleException::SmartcardModuleException (SmartcardModuleException::ErrorCode errorCode, std::string where, bool opensslDetails) inline
References LibCryptoSecException::details, errorCode, OpenSSLErrorHandler::getErrors(), and LibCryptoSecException::where.
~SmartcardModuleException()
virtual SmartcardModuleException::~SmartcardModuleException () throw () inline virtual
Member Function Documentation
errorCode2Message()
static std::string SmartcardModuleException::errorCode2Message (SmartcardModuleException::ErrorCode errorCode) inline static
References BLOCKED_PIN, DECRYPTING_DATA, ENUMERATING_CERTIFICATES, ENUMERATING_PRIVATE_KEYS, ID_NOT_FOUND, INVALID_PIN, INVALID_PKCS11_MODULE, SMARTCARD_NOT_AVAILABLE, SMARTCARD_READER_NOT_AVAILABLE, and UNKNOWN.
Referenced by getMessage(), and toString().
getErrorCode()
virtual SmartcardModuleException::ErrorCode SmartcardModuleException::getErrorCode () inline virtual
References errorCode.
getMessage()
virtual std::string SmartcardModuleException::getMessage () const inline virtual
Implements LibCryptoSecException.
References errorCode, and errorCode2Message().
toString()
virtual std::string SmartcardModuleException::toString () const inline virtual
Implements LibCryptoSecException.
References LibCryptoSecException::details, errorCode, errorCode2Message(), UNKNOWN, and LibCryptoSecException::where.
Member Data Documentation
errorCode
SmartcardModuleException::ErrorCode SmartcardModuleException::errorCode protected
Referenced by getErrorCode(), getMessage(), SmartcardModuleException(), and toString().
The documentation for this class was generated from the following file:
include/libcryptosec/exception/SmartcardModuleException.h