libcryptosec Documentation
ObjectIdentifier Class Reference
#include <ObjectIdentifier.h>
Public Member Functions
ObjectIdentifier ()
ObjectIdentifier (ASN1_OBJECT *asn1Object)
ObjectIdentifier (const ObjectIdentifier &objectIdentifier)
virtual ~ObjectIdentifier ()
std::string getXmlEncoded ()
std::string getXmlEncoded (std::string tab)
std::string getOid () throw (CertificationException)
int getNid () const
std::string getName ()
ASN1_OBJECT * getObjectIdentifier () const
ObjectIdentifier & operator= (const ObjectIdentifier &value)
Protected Attributes
ASN1_OBJECT * asn1Object
Constructor & Destructor Documentation
ObjectIdentifier() [1/3]
ObjectIdentifier::ObjectIdentifier ()
References asn1Object.
ObjectIdentifier() [2/3]
ObjectIdentifier::ObjectIdentifier (ASN1_OBJECT * asn1Object)
References asn1Object.
ObjectIdentifier() [3/3]
ObjectIdentifier::ObjectIdentifier (const ObjectIdentifier & objectIdentifier)
References asn1Object, and getObjectIdentifier().
~ObjectIdentifier()
ObjectIdentifier::~ObjectIdentifier () virtual
References asn1Object.
Member Function Documentation
getName()
std::string ObjectIdentifier::getName ()
References asn1Object, and getOid().
Referenced by Extension::getName(), and GeneralName::getXmlEncoded().
getNid()
int ObjectIdentifier::getNid () const
References asn1Object.
Referenced by AuthorityKeyIdentifierExtension::AuthorityKeyIdentifierExtension(), Extension::getTypeName(), and PolicyQualifierInfo::PolicyQualifierInfo().
getObjectIdentifier()
ASN1_OBJECT * ObjectIdentifier::getObjectIdentifier () const
References asn1Object.
Referenced by AccessDescription::getAccessDescription(), GeneralName::getGeneralName(), PolicyInformation::getPolicyInfo(), PolicyQualifierInfo::getPolicyQualInfo(), Extension::getX509Extension(), ObjectIdentifier(), and operator=().
getOid()
std::string ObjectIdentifier::getOid () throw (CertificationException)
References asn1Object, and CertificationException::SET_NO_VALUE.
Referenced by getName(), getXmlEncoded(), and Extension::toXml().
getXmlEncoded() [1/2]
std::string ObjectIdentifier::getXmlEncoded ()
Referenced by AccessDescription::getXmlEncoded(), PolicyInformation::getXmlEncoded(), and PolicyQualifierInfo::getXmlEncoded().
getXmlEncoded() [2/2]
std::string ObjectIdentifier::getXmlEncoded (std::string tab)
References getOid().
operator=()
ObjectIdentifier & ObjectIdentifier::operator= (const ObjectIdentifier & value)
References asn1Object, and getObjectIdentifier().
Member Data Documentation
asn1Object
ASN1_OBJECT* ObjectIdentifier::asn1Object protected
Referenced by getName(), getNid(), getObjectIdentifier(), getOid(), ObjectIdentifier(), operator=(), and ~ObjectIdentifier().
The documentation for this class was generated from the following files:
include/libcryptosec/certificate/ObjectIdentifier.h
src/certificate/ObjectIdentifier.cpp