libcryptosec Documentation
BigInteger Class Reference
Classes Relacionadas Utilitárias de Criptografia
Classe usada para representar números grandes.
#include <BigInteger.h>
Public Member Functions
BigInteger () throw (BigIntegerException)
Construtor padrão.
BigInteger (BIGNUM const *bn) throw (BigIntegerException)
BigInteger a partir de um estrutura BIGNUM do OpenSSL.
BigInteger (long val) throw (BigIntegerException)
BigInteger a partir de um tipo primitivo (unsigned long).
BigInteger (ASN1_INTEGER *val) throw (BigIntegerException)
BigInteger a partir de uma estrutura ASN1_INTEGER do OpenSSL.
BigInteger (ByteArray &b) throw (BigIntegerException)
BigInteger a partir de um objeto ByteArray.
BigInteger (BigInteger const &b) throw (BigIntegerException)
Construtor de cópia.
BigInteger (std::string dec) throw (BigIntegerException)
BigInteger a partir do string de um número inteiro na base decimal.
virtual ~BigInteger ()
Destrutor padrão.
void setValue (const long val=0) throw (BigIntegerException)
Define o valor inteiro de um BigInteger.
double getValue () const throw (BigIntegerException)
Retorna o valor inteiro correspondente do BigInteger.
bool isNegative () const throw ()
Retorna se o BigInteger é negativo.
ASN1_INTEGER * getASN1Value () const throw (BigIntegerException)
Retorna estrutura ASN1_INTEGER com o valor do BigInteger.
ByteArray * getBinValue () const throw (BigIntegerException)
Retorna ponteiro para um objeto ByteArray com o valor do BigInteger.
BIGNUM const * getBIGNUM () const throw ()
Retorna ponteiro para estrutura constante BIGNUM membro de BigInteger.
std::string toHex () const throw ()
Retorna string com valor do BigInteger em base 16.
std::string toDec () const throw ()
Retorna string com valor do BigInteger em base 10.
void setHexValue (std::string hex) throw (BigIntegerException)
Define o valor inteiro em base 16 de um BigInteger.
void setDecValue (std::string dec) throw (BigIntegerException)
Define o valor inteiro em base 10 de um BigInteger.
void setRandValue (int numBits=64) throw (BigIntegerException)
Define um valor inteiro randômico (positivo ou negativo).
void setNegative (bool neg=true) throw ()
Define o sinal do BigInteger.
int size () const throw ()
Retorna o tamanho do valor inteiro do BigInteger em bits.
BigInteger & add (BigInteger const &a) throw (BigIntegerException)
Soma os valores inteiros entre dois BigIntegers.
BigInteger & add (long const a) throw (BigIntegerException)
BigInteger & sub (BigInteger const &a) throw (BigIntegerException)
Subtração entre os valores inteiros de dois BigIntegers.
BigInteger & sub (long const a) throw (BigIntegerException)
BigInteger & mul (BigInteger const &a) throw (BigIntegerException)
BigInteger & mul (long const a) throw (BigIntegerException)
BigInteger operator* (BigInteger const &a) const throw (BigIntegerException)
BigInteger operator* (long const c) const throw (BigIntegerException)
BigInteger & div (BigInteger const &a) throw (BigIntegerException)
BigInteger & div (long const a) throw (BigIntegerException)
BigInteger operator/ (BigInteger const &a) const throw (BigIntegerException)
BigInteger operator/ (long const c) const throw (BigIntegerException)
BigInteger & mod (BigInteger const &a) throw (BigIntegerException)
BigInteger & mod (long const a) throw (BigIntegerException)
BigInteger operator% (BigInteger const &a) const throw (BigIntegerException)
BigInteger operator% (long const c) const throw (BigIntegerException)
int compare (BigInteger const &a) const throw ()
BigInteger operator+ (BigInteger const &c) const throw (BigIntegerException)
Operador de soma.
BigInteger operator+ (long const c) const throw (BigIntegerException)
BigInteger & operator+= (BigInteger const &c) throw (BigIntegerException)
BigInteger & operator+= (long const c) throw (BigIntegerException)
BigInteger operator- (BigInteger const &c) const throw (BigIntegerException)
Operador de subtração.
BigInteger operator- (long const c) const throw (BigIntegerException)
bool operator== (BigInteger const &c) const throw ()
bool operator== (long const c) const throw (BigIntegerException)
bool operator!= (BigInteger const &c) const throw ()
bool operator!= (long const c) const throw (BigIntegerException)
bool operator> (BigInteger const &c) const throw ()
bool operator> (long const c) const throw (BigIntegerException)
bool operator>= (BigInteger const &c) const throw ()
bool operator>= (long const c) const throw (BigIntegerException)
bool operator< (BigInteger const &c) const throw ()
bool operator< (long const c) const throw (BigIntegerException)
bool operator<= (BigInteger const &c) const throw ()
bool operator<= (long const c) const throw (BigIntegerException)
bool operator! () const throw ()
bool operator|| (BigInteger const &c) const throw ()
bool operator|| (long const c) const throw (BigIntegerException)
bool operator && (BigInteger const &c) const throw ()
bool operator && (long const c) const throw (BigIntegerException)
BigInteger & operator= (BigInteger const &c) throw (BigIntegerException)
Operador de atribuição.
BigInteger & operator= (long const c) throw (BigIntegerException)
Protected Attributes
BIGNUM * bigInt
Detailed Description
Classe usada para representar números grandes.
A limitação do tamanho do número depende da memória disponível
Constructor & Destructor Documentation
BigInteger() [1/7]
BigInteger::BigInteger () throw (BigIntegerException)
Construtor padrão.
Cria um objeto BigInteger com o valor inteiro 0.
Exceptions
BigIntegerException no caso de falta de memória ao criar o BigInteger.
References bigInt, BigIntegerException::MEMORY_ALLOC, and setValue().
BigInteger() [2/7]
BigInteger::BigInteger (BIGNUM const * bn) throw (BigIntegerException)
BigInteger a partir de um estrutura BIGNUM do OpenSSL.
Parameters
bn ponteiro para estrutra constante BIGNUM.
Exceptions
BigIntegerException no caso de erro interno do OpenSSL ao criar o BigInteger.
References bigInt, and BigIntegerException::INTERNAL_ERROR.
BigInteger() [3/7]
BigInteger::BigInteger (long val) throw (BigIntegerException)
BigInteger a partir de um tipo primitivo (unsigned long).
Parameters
val valor inteiro.
Exceptions
BigIntegerException no caso de falta de memória ao criar o BigInteger.
References bigInt, BigIntegerException::MEMORY_ALLOC, and setValue().
BigInteger() [4/7]
BigInteger::BigInteger (ASN1_INTEGER * val) throw (BigIntegerException)
BigInteger a partir de uma estrutura ASN1_INTEGER do OpenSSL.
Parameters
val ponteiro para estrutura ASN1_INTEGER.
Exceptions
BigIntegerException no caso de falta de memória ao criar o BigInteger.
References bigInt, BigIntegerException::INTERNAL_ERROR, and BigIntegerException::MEMORY_ALLOC.
BigInteger() [5/7]
BigInteger::BigInteger (ByteArray & b) throw (BigIntegerException)
BigInteger a partir de um objeto ByteArray.
Parameters
val referência para objeto constante ByteArray.
Exceptions
BigIntegerException no caso de falta de memória ao criar o BigInteger ou devido a um erro interno do OpenSSL.
References bigInt, BigIntegerException::INTERNAL_ERROR, and BigIntegerException::MEMORY_ALLOC.
BigInteger() [6/7]
BigInteger::BigInteger (BigInteger const & b) throw (BigIntegerException)
Construtor de cópia.
Parameters
b referência para um objeto constante BigInteger.
Exceptions
BigIntegerException no caso de falta de memória ao criar o BigInteger.
References bigInt, and BigIntegerException::MEMORY_ALLOC.
BigInteger() [7/7]
BigInteger::BigInteger (std::string dec) throw (BigIntegerException)
BigInteger a partir do string de um número inteiro na base decimal.
Parameters
dec string contendo um número inteiro em base 10.
Exceptions
BigIntegerException no caso de falta de memória ao criar o BigInteger.
References bigInt, BigIntegerException::MEMORY_ALLOC, and setDecValue().
~BigInteger()
BigInteger::~BigInteger () virtual
Destrutor padrão.
References bigInt.
Member Function Documentation
add() [1/2]
BigInteger & BigInteger::add (BigInteger const & a) throw (BigIntegerException)
Soma os valores inteiros entre dois BigIntegers.
Parameters
a referência para objeto constante BigInteger.
Returns
referência para objeto BigInteger com o resultado da soma.
Exceptions
BigIntegerException no caso de um erro interno do OpenSSL.
References bigInt, and BigIntegerException::INTERNAL_ERROR.
Referenced by add(), DateTime::addDays(), DateTime::addHours(), DateTime::addMinutes(), DateTime::addSeconds(), DateTime::addYears(), DateTime::date2epoch(), operator+(), operator+=(), and operator-().
add() [2/2]
BigInteger & BigInteger::add (long const a) throw (BigIntegerException)
References add().
compare()
int BigInteger::compare (BigInteger const & a) const throw ()
References getBIGNUM().
Referenced by operator!=(), operator<(), operator<=(), operator==(), operator>(), and operator>=().
div() [1/2]
BigInteger & BigInteger::div (BigInteger const & a) throw (BigIntegerException)
References bigInt, BigIntegerException::DIVISION_BY_ZERO, BigIntegerException::INTERNAL_ERROR, and BigIntegerException::MEMORY_ALLOC.
Referenced by div(), DateTime::getDate(), and operator/().
div() [2/2]
BigInteger & BigInteger::div (long const a) throw (BigIntegerException)
References div().
getASN1Value()
ASN1_INTEGER * BigInteger::getASN1Value () const throw (BigIntegerException)
Retorna estrutura ASN1_INTEGER com o valor do BigInteger.
Returns
estrutura ASN1_INTEGER.
Exceptions
BigIntegerException no caso de falta de memória ao criar o ASN1_INTEGER.
References bigInt, and BigIntegerException::MEMORY_ALLOC.
Referenced by RevokedCertificate::getX509Revoked().
getBIGNUM()
BIGNUM const * BigInteger::getBIGNUM () const throw ()
Retorna ponteiro para estrutura constante BIGNUM membro de BigInteger.
Returns
ponteiro para estrutura constante BIGNUM.
References bigInt.
Referenced by EllipticCurve::BN_a(), EllipticCurve::BN_b(), EllipticCurve::BN_cofactor(), EllipticCurve::BN_order(), EllipticCurve::BN_p(), EllipticCurve::BN_x(), EllipticCurve::BN_y(), and compare().
getBinValue()
ByteArray * BigInteger::getBinValue () const throw (BigIntegerException)
Retorna ponteiro para um objeto ByteArray com o valor do BigInteger.
O objeto ByteArray tem codificação mpi (inclui sinal) e deve ser deletado.
Returns
ponteiro para objeto ByteArray.
Exceptions
BigIntegerException no caso de falta de memória ao criar o ByteArray.
References bigInt, BigIntegerException::MEMORY_ALLOC, and ByteArray::setDataPointer().
getValue()
double BigInteger::getValue () const throw (BigIntegerException)
Retorna o valor inteiro correspondente do BigInteger.
Returns
valor inteiro do BigInteger.
Exceptions
BigIntegerException caso o valor do BigInteger não possa ser representado em um unsigned long (overflow).
References bigInt, isNegative(), and BigIntegerException::UNSIGNED_LONG_OVERFLOW.
Referenced by RevokedCertificate::getCertificateSerialNumber(), DateTime::getDate(), and DateTime::getDateTime().
isNegative()
bool BigInteger::isNegative () const throw ()
Retorna se o BigInteger é negativo.
Returns
true se o BigInteger é negativo, false caso contrário.
References bigInt.
Referenced by getValue().
mod() [1/2]
BigInteger & BigInteger::mod (BigInteger const & a) throw (BigIntegerException)
References bigInt, BigIntegerException::DIVISION_BY_ZERO, BigIntegerException::INTERNAL_ERROR, and BigIntegerException::MEMORY_ALLOC.
Referenced by DateTime::getDate(), mod(), and operator%().
mod() [2/2]
BigInteger & BigInteger::mod (long const a) throw (BigIntegerException)
References mod().
mul() [1/2]
BigInteger & BigInteger::mul (BigInteger const & a) throw (BigIntegerException)
References bigInt, BigIntegerException::INTERNAL_ERROR, and BigIntegerException::MEMORY_ALLOC.
Referenced by DateTime::addDays(), DateTime::addHours(), DateTime::addMinutes(), DateTime::addYears(), DateTime::date2epoch(), mul(), and operator*().
mul() [2/2]
BigInteger & BigInteger::mul (long const a) throw (BigIntegerException)
References mul().
operator &&() [1/2]
bool BigInteger::operator&& (BigInteger const & c) const throw ()
Referenced by operator||().
operator &&() [2/2]
bool BigInteger::operator&& (long const c) const throw (BigIntegerException)
operator!()
bool BigInteger::operator! () const throw ()
operator!=() [1/2]
bool BigInteger::operator!= (BigInteger const & c) const throw ()
References compare().
operator!=() [2/2]
bool BigInteger::operator!= (long const c) const throw (BigIntegerException)
References compare().
operator%() [1/2]
BigInteger BigInteger::operator% (BigInteger const & a) const throw (BigIntegerException)
References mod().
operator%() [2/2]
BigInteger BigInteger::operator% (long const c) const throw (BigIntegerException)
References mod().
operator*() [1/2]
BigInteger BigInteger::operator* (BigInteger const & a) const throw (BigIntegerException)
References mul().
operator*() [2/2]
BigInteger BigInteger::operator* (long const c) const throw (BigIntegerException)
References mul().
operator+() [1/2]
BigInteger BigInteger::operator+ (BigInteger const & c) const throw (BigIntegerException)
Operador de soma.
Parameters
c referência para objeto constante BigInteger.
Returns
referência para objeto BigInteger com o resultado da soma.
Exceptions
BigIntegerException no caso de um erro interno do OpenSSL.
References add().
operator+() [2/2]
BigInteger BigInteger::operator+ (long const c) const throw (BigIntegerException)
References add().
operator+=() [1/2]
BigInteger & BigInteger::operator+= (BigInteger const & c) throw (BigIntegerException)
References add().
operator+=() [2/2]
BigInteger & BigInteger::operator+= (long const c) throw (BigIntegerException)
References add().
operator-() [1/2]
BigInteger BigInteger::operator- (BigInteger const & c) const throw (BigIntegerException)
Operador de subtração.
Parameters
c referência para objeto constante BigInteger.
Returns
referência para objeto BigInteger com o resultado da subtração.
Exceptions
BigIntegerException no caso de um erro interno do OpenSSL.
References add(), and sub().
operator-() [2/2]
BigInteger BigInteger::operator- (long const c) const throw (BigIntegerException)
References add(), and sub().
operator/() [1/2]
BigInteger BigInteger::operator/ (BigInteger const & a) const throw (BigIntegerException)
References div().
operator/() [2/2]
BigInteger BigInteger::operator/ (long const c) const throw (BigIntegerException)
References div().
operator<() [1/2]
bool BigInteger::operator< (BigInteger const & c) const throw ()
References compare().
operator<() [2/2]
bool BigInteger::operator< (long const c) const throw (BigIntegerException)
References compare().
operator<=() [1/2]
bool BigInteger::operator<= (BigInteger const & c) const throw ()
References compare().
operator<=() [2/2]
bool BigInteger::operator<= (long const c) const throw (BigIntegerException)
operator=() [1/2]
BigInteger & BigInteger::operator= (BigInteger const & c) throw (BigIntegerException)
Operador de atribuição.
Parameters
c referência para objeto constante BigInteger.
Returns
referência para objeto BigInteger.
Exceptions
BigIntegerException no caso de um erro interno do OpenSSL.
References bigInt, and BigIntegerException::INTERNAL_ERROR.
operator=() [2/2]
BigInteger & BigInteger::operator= (long const c) throw (BigIntegerException)
References setValue().
operator==() [1/2]
bool BigInteger::operator== (BigInteger const & c) const throw ()
References compare().
operator==() [2/2]
bool BigInteger::operator== (long const c) const throw (BigIntegerException)
References compare().
operator>() [1/2]
bool BigInteger::operator> (BigInteger const & c) const throw ()
References compare().
operator>() [2/2]
bool BigInteger::operator> (long const c) const throw (BigIntegerException)
References compare().
operator>=() [1/2]
bool BigInteger::operator>= (BigInteger const & c) const throw ()
References compare().
operator>=() [2/2]
bool BigInteger::operator>= (long const c) const throw (BigIntegerException)
operator||() [1/2]
bool BigInteger::operator|| (BigInteger const & c) const throw ()
operator||() [2/2]
bool BigInteger::operator|| (long const c) const throw (BigIntegerException)
References operator &&().
setDecValue()
void BigInteger::setDecValue (std::string dec) throw (BigIntegerException)
Define o valor inteiro em base 10 de um BigInteger.
Não utilizar string "0x" para identificar base 16.
Parameters
dec valor inteiro.
Exceptions
BigIntegerException no caso de um erro interno do OpenSSL.
References bigInt, and BigIntegerException::INTERNAL_ERROR.
Referenced by BigInteger().
setHexValue()
void BigInteger::setHexValue (std::string hex) throw (BigIntegerException)
Define o valor inteiro em base 16 de um BigInteger.
Não utilizar string "0x" para identificar base 16.
Parameters
hex valor inteiro.
Exceptions
BigIntegerException no caso de um erro interno do OpenSSL.
References bigInt, and BigIntegerException::INTERNAL_ERROR.
Referenced by EllipticCurve::setA(), EllipticCurve::setB(), EllipticCurve::setCofactor(), EllipticCurve::setOrder(), EllipticCurve::setP(), EllipticCurve::setX(), and EllipticCurve::setY().
setNegative()
void BigInteger::setNegative (bool neg = true) throw ()
Define o sinal do BigInteger.
Parameters
bool true se negativo, false se positivo. Se nenhum parâmetro é passado, assume-se negativo.
References bigInt.
Referenced by setValue().
setRandValue()
void BigInteger::setRandValue (int numBits = 64) throw (BigIntegerException)
Define um valor inteiro randômico (positivo ou negativo).
Parameters
numBits número de bits do BigInteger. Se nenhum parâmetro é passado, assume-se numBits = 64.
Exceptions
BigIntegerException no caso de um erro interno do OpenSSL.
References bigInt, and BigIntegerException::INTERNAL_ERROR.
setValue()
void BigInteger::setValue (const long val = 0) throw (BigIntegerException)
Define o valor inteiro de um BigInteger.
Se nenhum valor é passado, define o valor zero.
Parameters
val valor inteiro.
Exceptions
BigIntegerException no caso de um erro interno do OpenSSL.
References bigInt, BigIntegerException::INTERNAL_ERROR, and setNegative().
Referenced by BigInteger(), and operator=().
size()
int BigInteger::size () const throw ()
Retorna o tamanho do valor inteiro do BigInteger em bits.
Returns
tamanho do BigInteger
References bigInt.
sub() [1/2]
BigInteger & BigInteger::sub (BigInteger const & a) throw (BigIntegerException)
Subtração entre os valores inteiros de dois BigIntegers.
Parameters
a referência para objeto constante BigInteger.
Returns
referência para objeto BigInteger com o resultado da subtração.
Exceptions
BigIntegerException no caso de um erro interno do OpenSSL.
References bigInt, and BigIntegerException::INTERNAL_ERROR.
Referenced by DateTime::getDate(), operator-(), and sub().
sub() [2/2]
BigInteger & BigInteger::sub (long const a) throw (BigIntegerException)
References sub().
toDec()
string BigInteger::toDec () const throw ()
Retorna string com valor do BigInteger em base 10.
Returns
string com valor inteiro.
References bigInt.
Referenced by RevokedCertificate::getXmlEncoded(), CertificateBuilder::toXml(), and Certificate::toXml().
toHex()
string BigInteger::toHex () const throw ()
Retorna string com valor do BigInteger em base 16.
Returns
string com valor inteiro.
References bigInt.
Member Data Documentation
bigInt
BIGNUM* BigInteger::bigInt protected
Referenced by add(), BigInteger(), div(), getASN1Value(), getBIGNUM(), getBinValue(), getValue(), isNegative(), mod(), mul(), operator=(), setDecValue(), setHexValue(), setNegative(), setRandValue(), setValue(), size(), sub(), toDec(), toHex(), and ~BigInteger().
The documentation for this class was generated from the following files:
include/libcryptosec/BigInteger.h
src/BigInteger.cpp