libcryptosec Documentation
OpenSSLErrorHandler Class Reference
Utilities to turn it easier to use some OpenSSL procedures.
#include <OpenSSLErrorHandler.h>
Public Types
enum ErrorsString {
ENCODE, ENGINE, MESSAGE_DIGEST, SYMMETRIC_CIPHER,
PKCS11_MODULE, PKCS7, RANDOM, ASYMMETRIC_KEY,
CERTIFICATION
}
Static Public Member Functions
static void loadErrorsString (OpenSSLErrorHandler::ErrorsString errorsString)
Default constructor.
static std::string getErrors ()
Gets OpenSSL error list as returned by ERR_print_errors.
static void clearErrors ()
Clears OpenSSL error queue by calling ERR_clear_errors and clearing internal BIO (errorBio).
Detailed Description
Utilities to turn it easier to use some OpenSSL procedures.
Member Enumeration Documentation
ErrorsString
enum OpenSSLErrorHandler::ErrorsString
Enumerator
ENCODE
ENGINE
MESSAGE_DIGEST
SYMMETRIC_CIPHER
PKCS11_MODULE
PKCS7
RANDOM
ASYMMETRIC_KEY
CERTIFICATION
Member Function Documentation
clearErrors()
void OpenSSLErrorHandler::clearErrors () static
Clears OpenSSL error queue by calling ERR_clear_errors and clearing internal BIO (errorBio).
Referenced by getErrors().
getErrors()
std::string OpenSSLErrorHandler::getErrors () static
Gets OpenSSL error list as returned by ERR_print_errors.
References clearErrors(), and ByteArray::toString().
Referenced by EngineException::EngineException(), Pkcs7Exception::Pkcs7Exception(), and SmartcardModuleException::SmartcardModuleException().
loadErrorsString()
void OpenSSLErrorHandler::loadErrorsString (OpenSSLErrorHandler::ErrorsString errorsString) static
Default constructor.
Default destructor.
References ASYMMETRIC_KEY, CERTIFICATION, ENCODE, ENGINE, MESSAGE_DIGEST, PKCS11_MODULE, PKCS7, RANDOM, and SYMMETRIC_CIPHER.
The documentation for this class was generated from the following files:
include/libcryptosec/OpenSSLErrorHandler.h
src/OpenSSLErrorHandler.cpp