libcryptosec Documentation
ECDSAKeyPair Class Reference
Classes relacionadas ao uso de chaves assimétricas.
Representa um par de chaves assimétricas ECDSA.
#include <ECDSAKeyPair.h>
Public Member Functions
ECDSAKeyPair (ByteArray &derEncoded) throw (AsymmetricKeyException)
Cria par por parâmetros informados em DER TODO.
ECDSAKeyPair (std::string &encoded) throw (AsymmetricKeyException)
Cria par por parâmetros informados em PEM TODO.
ECDSAKeyPair (const EllipticCurve &curve) throw (AsymmetricKeyException)
Cria par por parãmetros informados por um objeto Curve TODO.
ECDSAKeyPair (AsymmetricKey::Curve curve, bool named=true) throw (AsymmetricKeyException)
virtual ~ECDSAKeyPair ()
virtual PublicKey * getPublicKey () throw (AsymmetricKeyException, EncodeException)
gets the public key from key pair
virtual PrivateKey * getPrivateKey () throw (AsymmetricKeyException)
gets the private from key pair
virtual AsymmetricKey::Algorithm getAlgorithm () throw (AsymmetricKeyException)
gets algorithm id from the key
Public Member Functions inherited from KeyPair
KeyPair (AsymmetricKey::Algorithm algorithm, int length) throw (AsymmetricKeyException)
create a KeyPair object, creating a new key pair
KeyPair (Engine *engine, std::string keyId) throw (EngineException)
KeyPair (std::string pemEncoded, ByteArray passphrase) throw (EncodeException)
create a KeyPair object, loading the key pair from encoded (PEM format), decrypting with key
KeyPair (std::string pemEncoded) throw (EncodeException)
create a KeyPair object, loading the key pair from encoded (PEM format)
KeyPair (ByteArray derEncoded) throw (EncodeException)
create a KeyPair object, loading the key pair from encoded (DER format)
KeyPair (const KeyPair &keyPair)
virtual ~KeyPair ()
std::string getPemEncoded (SymmetricKey &passphrase, SymmetricCipher::OperationMode mode) throw (SymmetricCipherException, EncodeException)
encode the key pair in PEM format encrypted
std::string getPemEncoded () throw (EncodeException)
encode the key pair in PEM format
ByteArray getDerEncoded () throw (EncodeException)
encode the key pair in DER format
int getSize () throw (AsymmetricKeyException)
gets the key size
int getSizeBits () throw (AsymmetricKeyException)
gets the key size in bits
EVP_PKEY * getEvpPkey () const
ENGINE * getEngine () const
std::string getKeyId () const
Protected Member Functions
void generateKey (EC_GROUP *group) throw (AsymmetricKeyException)
EC_GROUP * createGroup (const EllipticCurve &curve)
EC_GROUP * createGroup (ByteArray &derEncoded)
Protected Member Functions inherited from KeyPair
KeyPair ()
std::string getPublicKeyPemEncoded () throw (EncodeException)
Additional Inherited Members
Static Protected Member Functions inherited from KeyPair
static int passphraseCallBack (char *buf, int size, int rwflag, void *u)
Protected Attributes inherited from KeyPair
EVP_PKEY * key
struct from OpenSSL that represents the key pair
std::string keyId
ENGINE * engine
Detailed Description
Representa um par de chaves assimétricas ECDSA.
Essa classe deve ser usada para a criação de chaves assimétricas ECDSA que não possui nome ou NID definido no OpenSSL. Par de chaves é gerada através dos parâmetros da curva, enviados em ASN1 (PEM ou DER) ou pela classe EllipticCurve. É uma especialização da classe KeyPair
See also
EllipticCurve
BrainpoolCurveFactory
Constructor & Destructor Documentation
ECDSAKeyPair() [1/4]
ECDSAKeyPair::ECDSAKeyPair (ByteArray & derEncoded) throw (AsymmetricKeyException)
Cria par por parâmetros informados em DER TODO.
ECDSAKeyPair() [2/4]
ECDSAKeyPair::ECDSAKeyPair (std::string & encoded) throw (AsymmetricKeyException)
Cria par por parâmetros informados em PEM TODO.
References Base64::decode().
ECDSAKeyPair() [3/4]
ECDSAKeyPair::ECDSAKeyPair (const EllipticCurve & curve) throw (AsymmetricKeyException)
Cria par por parãmetros informados por um objeto Curve TODO.
ECDSAKeyPair() [4/4]
ECDSAKeyPair::ECDSAKeyPair (AsymmetricKey::Curve curve, bool named = true) throw (AsymmetricKeyException)
References AsymmetricKeyException::INTERNAL_ERROR.
~ECDSAKeyPair()
ECDSAKeyPair::~ECDSAKeyPair () virtual
References KeyPair::engine, and KeyPair::key.
Member Function Documentation
createGroup() [1/2]
EC_GROUP * ECDSAKeyPair::createGroup (const EllipticCurve & curve) protected
References EllipticCurve::BN_a(), EllipticCurve::BN_b(), EllipticCurve::BN_cofactor(), EllipticCurve::BN_order(), EllipticCurve::BN_p(), EllipticCurve::BN_x(), EllipticCurve::BN_y(), and AsymmetricKeyException::INTERNAL_ERROR.
createGroup() [2/2]
EC_GROUP * ECDSAKeyPair::createGroup (ByteArray & derEncoded) protected
References KeyPair::engine, ByteArray::getDataPointer(), AsymmetricKeyException::INTERNAL_ERROR, KeyPair::key, and ByteArray::size().
generateKey()
void ECDSAKeyPair::generateKey (EC_GROUP * group) throw (AsymmetricKeyException) protected
References AsymmetricKeyException::INTERNAL_ERROR, and KeyPair::key.
getAlgorithm()
AsymmetricKey::Algorithm ECDSAKeyPair::getAlgorithm () throw (AsymmetricKeyException) virtual
gets algorithm id from the key
Returns
algorithm id
Reimplemented from KeyPair.
References AsymmetricKey::ECDSA.
getPrivateKey()
PrivateKey * ECDSAKeyPair::getPrivateKey () throw (AsymmetricKeyException) virtual
gets the private from key pair
Returns
a private key from key pair
Reimplemented from KeyPair.
References KeyPair::engine, AsymmetricKeyException::INVALID_TYPE, KeyPair::key, KeyPair::keyId, and AsymmetricKeyException::UNAVAILABLE_KEY.
getPublicKey()
PublicKey * ECDSAKeyPair::getPublicKey () throw (AsymmetricKeyException, EncodeException) virtual
gets the public key from key pair
Returns
a public key from key pair
Reimplemented from KeyPair.
References KeyPair::getPublicKeyPemEncoded().
The documentation for this class was generated from the following files:
include/libcryptosec/ECDSAKeyPair.h
src/ECDSAKeyPair.cpp