libcryptosec Documentation
Pkcs12Exception Class Reference
#include <Pkcs12Exception.h>
Public Types
enum ErrorCode { UNKNOWN, KEY_AND_CERT_DO_NOT_MATCH, PARSE_ERROR, MAC_VERIFY_FAILURE }
Public Member Functions
Pkcs12Exception ()
virtual ~Pkcs12Exception () throw ()
Pkcs12Exception (std::string where)
Pkcs12Exception (Pkcs12Exception::ErrorCode errorCode, std::string where)
virtual std::string getMessage () const
virtual std::string toString () const
virtual Pkcs12Exception::ErrorCode getErrorCode ()
Public Member Functions inherited from LibCryptoSecException
virtual ~LibCryptoSecException () throw ()
virtual const char * what () const throw ()
virtual const std::string getDetails () const throw ()
Static Public Member Functions
static std::string errorCode2Message (Pkcs12Exception::ErrorCode errorCode)
Protected Attributes
Pkcs12Exception::ErrorCode errorCode
Protected Attributes inherited from LibCryptoSecException
std::string where
std::string details
Member Enumeration Documentation
ErrorCode
enum Pkcs12Exception::ErrorCode
Enumerator
UNKNOWN
KEY_AND_CERT_DO_NOT_MATCH
PARSE_ERROR
MAC_VERIFY_FAILURE
Constructor & Destructor Documentation
Pkcs12Exception() [1/3]
Pkcs12Exception::Pkcs12Exception ()
~Pkcs12Exception()
virtual Pkcs12Exception::~Pkcs12Exception () throw () inline virtual
Pkcs12Exception() [2/3]
Pkcs12Exception::Pkcs12Exception (std::string where) inline
References errorCode, UNKNOWN, and LibCryptoSecException::where.
Pkcs12Exception() [3/3]
Pkcs12Exception::Pkcs12Exception (Pkcs12Exception::ErrorCode errorCode, std::string where) inline
References errorCode, and LibCryptoSecException::where.
Member Function Documentation
errorCode2Message()
static std::string Pkcs12Exception::errorCode2Message (Pkcs12Exception::ErrorCode errorCode) inline static
References KEY_AND_CERT_DO_NOT_MATCH, MAC_VERIFY_FAILURE, PARSE_ERROR, and UNKNOWN.
Referenced by getMessage(), and toString().
getErrorCode()
virtual Pkcs12Exception::ErrorCode Pkcs12Exception::getErrorCode () inline virtual
References errorCode.
getMessage()
virtual std::string Pkcs12Exception::getMessage () const inline virtual
Implements LibCryptoSecException.
References errorCode, and errorCode2Message().
toString()
virtual std::string Pkcs12Exception::toString () const inline virtual
Implements LibCryptoSecException.
References LibCryptoSecException::details, errorCode, errorCode2Message(), UNKNOWN, and LibCryptoSecException::where.
Member Data Documentation
errorCode
Pkcs12Exception::ErrorCode Pkcs12Exception::errorCode protected
Referenced by getErrorCode(), getMessage(), Pkcs12Exception(), and toString().
The documentation for this class was generated from the following file:
include/libcryptosec/exception/Pkcs12Exception.h