libcryptosec Documentation
Pkcs12 Class Reference
#include <Pkcs12.h>
Public Member Functions
Pkcs12 (PKCS12 *p12)
virtual ~Pkcs12 ()
ByteArray getDerEncoded () const throw (EncodeException)
PrivateKey * getPrivKey (string password) throw (Pkcs12Exception)
Retorna uma copia da chave privada encapsulada pelo objeto Pkcs12.
Certificate * getCertificate (string password) throw (Pkcs12Exception)
Retorna uma copia do certificado encapsulados pelo objeto Pkcs12.
vector< Certificate * > getAdditionalCertificates (string password) throw (Pkcs12Exception)
Retorna uma copia dos certificados adicionais encapsulados pelo objeto Pkcs12.
Protected Member Functions
void parse (string password) throw (Pkcs12Exception)
Popula os objetos internos da classe: privKey, cert e ca.
Protected Attributes
PrivateKey * privKey
Certificate * cert
vector< Certificate * > ca
PKCS12 * pkcs12
Constructor & Destructor Documentation
Pkcs12()
Pkcs12::Pkcs12 (PKCS12 * p12)
References cert, pkcs12, and privKey.
~Pkcs12()
Pkcs12::~Pkcs12 () virtual
References ca, cert, pkcs12, and privKey.
Member Function Documentation
getAdditionalCertificates()
vector< Certificate * > Pkcs12::getAdditionalCertificates (string password) throw (Pkcs12Exception)
Retorna uma copia dos certificados adicionais encapsulados pelo objeto Pkcs12.
Parameters
password passphrase do pacote Pkcs12
References ca, parse(), and privKey.
getCertificate()
Certificate * Pkcs12::getCertificate (string password) throw (Pkcs12Exception)
Retorna uma copia do certificado encapsulados pelo objeto Pkcs12.
Parameters
password passphrase do pacote Pkcs12
References cert, Certificate::getX509(), parse(), and privKey.
getDerEncoded()
ByteArray Pkcs12::getDerEncoded () const throw (EncodeException)
Returns
o conteudo em codificacao DER do pacote Pkcs12
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_READING, EncodeException::DER_ENCODE, and pkcs12.
getPrivKey()
PrivateKey * Pkcs12::getPrivKey (string password) throw (Pkcs12Exception)
Retorna uma copia da chave privada encapsulada pelo objeto Pkcs12.
Parameters
password passphrase do pacote Pkcs12
References AsymmetricKey::DSA, AsymmetricKey::ECDSA, AsymmetricKey::getAlgorithm(), AsymmetricKey::getEvpPkey(), AsymmetricKeyException::INVALID_TYPE, parse(), privKey, and AsymmetricKey::RSA.
parse()
void Pkcs12::parse (string password) throw (Pkcs12Exception) protected
Popula os objetos internos da classe: privKey, cert e ca.
Parameters
password passphrase do pacote Pkcs12
References ca, cert, Pkcs12Exception::MAC_VERIFY_FAILURE, Pkcs12Exception::PARSE_ERROR, pkcs12, and privKey.
Referenced by getAdditionalCertificates(), getCertificate(), and getPrivKey().
Member Data Documentation
ca
vector<Certificate*> Pkcs12::ca protected
Referenced by getAdditionalCertificates(), parse(), and ~Pkcs12().
cert
Certificate* Pkcs12::cert protected
Referenced by getCertificate(), parse(), Pkcs12(), and ~Pkcs12().
pkcs12
PKCS12* Pkcs12::pkcs12 protected
Referenced by getDerEncoded(), parse(), Pkcs12(), and ~Pkcs12().
privKey
PrivateKey* Pkcs12::privKey protected
Referenced by getAdditionalCertificates(), getCertificate(), getPrivKey(), parse(), Pkcs12(), and ~Pkcs12().
The documentation for this class was generated from the following files:
include/libcryptosec/Pkcs12.h
src/Pkcs12.cpp