libcryptosec Documentation
ByteArray.cpp File Reference
#include <libcryptosec/ByteArray.h>
Functions
bool operator== (const ByteArray &left, const ByteArray &right)
bool operator!= (const ByteArray &left, const ByteArray &right)
ByteArray & operator xor (const ByteArray &left, const ByteArray &right)
Function Documentation
operator xor()
ByteArray& operator xor (const ByteArray & left, const ByteArray & right)
Parameters
left Primeiro ByteArray da operação.
right Segundo ByteArray da operação.
References ByteArray::at(), ByteArray::ByteArray(), and ByteArray::size().
operator!=()
bool operator!= (const ByteArray & left, const ByteArray & right)
Parameters
left Primeiro ByteArray da comparação.
right Segundo ByteArray da comparação.
operator==()
bool operator== (const ByteArray & left, const ByteArray & right)
Parameters
left Primeiro ByteArray da comparação.
right Segundo ByteArray da comparação.