libcryptosec Documentation
BrainpoolCurveFactory Class Reference
Classes Relacionadas Utilitárias de Criptografia
Classe para fabricação de curvas do padrão Brainpool.
#include <BrainpoolCurveFactory.h>
Public Types
enum CurveName {
BP160r1, BP160t1, BP192r1, BP192t1,
BP224r1, BP224t1, BP256r1, BP256t1,
BP320r1, BP320t1, BP384r1, BP384t1,
BP512r1, BP512t1
}
Public Member Functions
virtual ~BrainpoolCurveFactory ()
Static Public Member Functions
static const EllipticCurve * getCurve (BrainpoolCurveFactory::CurveName curveName) throw (BigIntegerException)
Detailed Description
Classe para fabricação de curvas do padrão Brainpool.
Member Enumeration Documentation
CurveName
enum BrainpoolCurveFactory::CurveName
Enumerator
BP160r1
BP160t1
BP192r1
BP192t1
BP224r1
BP224t1
BP256r1
BP256t1
BP320r1
BP320t1
BP384r1
BP384t1
BP512r1
BP512t1
Constructor & Destructor Documentation
~BrainpoolCurveFactory()
virtual BrainpoolCurveFactory::~BrainpoolCurveFactory () inline virtual
References getCurve().
Member Function Documentation
getCurve()
const EllipticCurve * BrainpoolCurveFactory::getCurve (BrainpoolCurveFactory::CurveName curveName) throw (BigIntegerException) static
References BP160r1, BP160t1, BP192r1, BP192t1, BP224r1, BP224t1, BP256r1, BP256t1, BP320r1, BP320t1, BP384r1, BP384t1, BP512r1, BP512t1, EllipticCurve::setA(), EllipticCurve::setB(), EllipticCurve::setCofactor(), EllipticCurve::setName(), EllipticCurve::setOrder(), EllipticCurve::setP(), EllipticCurve::setX(), and EllipticCurve::setY().
Referenced by ~BrainpoolCurveFactory().
The documentation for this class was generated from the following files:
include/libcryptosec/ec/BrainpoolCurveFactory.h
src/ec/BrainpoolCurveFactory.cpp