libcryptosec Documentation
Hmac Class Reference
Classes Relacionadas Utilitárias de Criptografia
Implementa as funcionalidades de um Hmac.
#include <Hmac.h>
Public Member Functions
Hmac ()
Construtor padrão.
Hmac (std::string key, MessageDigest::Algorithm algorithm) throw (HmacException)
Construtor.
Hmac (ByteArray key, MessageDigest::Algorithm algorithm) throw (HmacException)
Construtor.
Hmac (std::string key, MessageDigest::Algorithm algorithm, Engine &engine) throw (HmacException)
Construtor.
Hmac (ByteArray key, MessageDigest::Algorithm algorithm, Engine &engine) throw (HmacException)
Construtor.
virtual ~Hmac ()
Destrutor.
void init (ByteArray &key, MessageDigest::Algorithm algorithm) throw (HmacException)
Inicializar a estrutura do hmac.
void init (ByteArray &key, MessageDigest::Algorithm algorithm, Engine &engine) throw (HmacException)
Inicializar a estrutura do hmac.
void init (std::string key, MessageDigest::Algorithm algorithm) throw (HmacException)
Inicializar a estrutura do hmac.
void init (std::string key, MessageDigest::Algorithm algorithm, Engine &engine) throw (HmacException)
Inicializar a estrutura do hmac.
void update (ByteArray &data) throw (HmacException, InvalidStateException)
Atualizar/concatenar o conteúdo de entrada do hmac.
void update (std::string data) throw (HmacException, InvalidStateException)
Atualizar/concatenar o conteúdo de entrada do hmac.
void update (std::vector< std::string > &data) throw (HmacException, InvalidStateException)
Atualizar/concatenar o conteúdo de entrada do hmac.
void update (std::vector< ByteArray > &data) throw (HmacException, InvalidStateException)
Atualizar/concatenar o conteúdo de entrada do hmac.
ByteArray doFinal (ByteArray &data) throw (HmacException, InvalidStateException)
Gerar o hmac.
ByteArray doFinal (std::string data) throw (HmacException, InvalidStateException)
Gerar o hmac.
ByteArray doFinal () throw (HmacException, InvalidStateException)
Gerar o hmac.
Protected Types
enum State { NO_INIT, INIT, UPDATE }
Protected Attributes
MessageDigest::Algorithm algorithm
Algoritmo selecionado.
State state
Estado das estruturas de resumo.
HMAC_CTX ctx
Estrutura OpenSSL que representa o Hmac.
Detailed Description
Implementa as funcionalidades de um Hmac.
Antes de utilizar o Hmac, o algoritmo de resumo (hash) deve ser carregado.
Member Enumeration Documentation
State
enum Hmac::State protected
Enumerator
NO_INIT
INIT
UPDATE
Constructor & Destructor Documentation
Hmac() [1/5]
Hmac::Hmac ()
Construtor padrão.
Controi um objeto Hmac não inicializado.
See also
Hmac::init(std::string key, Hmac::Algorithm algorithm).
Hmac::update(ByteArray &data).
Hmac::doFinal().
References NO_INIT, and state.
Hmac() [2/5]
Hmac::Hmac (std::string key, MessageDigest::Algorithm algorithm) throw (HmacException)
Construtor.
Constroi um objeto Hmac.
Parameters
key chave secreta.
algorithm algoritmo de resumo.
Exceptions
HmacException caso ocorra erro ao inicializar a estrutura do hmac do OpenSSL.
References algorithm, and init().
Hmac() [3/5]
Hmac::Hmac (ByteArray key, MessageDigest::Algorithm algorithm) throw (HmacException)
Construtor.
Constroi um objeto Hmac.
Parameters
key chave secreta.
algorithm algoritmo de resumo.
Exceptions
HmacException caso ocorra erro ao inicializar a estrutura do hmac do OpenSSL.
References algorithm, and init().
Hmac() [4/5]
Hmac::Hmac (std::string key, MessageDigest::Algorithm algorithm, Engine & engine) throw (HmacException)
Construtor.
Constroi um objeto Hmac.
Parameters
key chave secreta.
algorithm algoritmo de resumo.
engine objeto Engine.
Exceptions
HmacException caso ocorra erro ao inicializar a estrutura do hmac do OpenSSL.
References algorithm, and init().
Hmac() [5/5]
Hmac::Hmac (ByteArray key, MessageDigest::Algorithm algorithm, Engine & engine) throw (HmacException)
Construtor.
Constroi um objeto Hmac.
Parameters
key chave secreta.
algorithm algoritmo de resumo.
engine objeto Engine.
Exceptions
HmacException caso ocorra erro ao inicializar a estrutura do hmac do OpenSSL.
References algorithm, and init().
~Hmac()
Hmac::~Hmac () virtual
Destrutor.
Member Function Documentation
doFinal() [1/3]
ByteArray Hmac::doFinal (ByteArray & data) throw (HmacException, InvalidStateException)
Gerar o hmac.
Parameters
data conteúdo para geração do hmac.
Returns
bytes que representam o hmac.
Exceptions
HmacException caso ocorra erro ao finalizar o contexto do hmac do OpenSSL.
InvalidStateException caso o objeto Hmac não tenha sido inicializado corretamente ou caso não tenha sido passado o conteúdo para calculo do hmac.
References doFinal(), and update().
doFinal() [2/3]
ByteArray Hmac::doFinal (std::string data) throw (HmacException, InvalidStateException)
Gerar o hmac.
Parameters
data conteúdo para geração do hmac.
Returns
bytes que representam o hmac.
Exceptions
HmacException caso ocorra erro ao finalizar o contexto do hmac do OpenSSL.
InvalidStateException caso o objeto Hmac não tenha sido inicializado corretamente ou caso não tenha sido passado o conteúdo para calculo do hmac.
References doFinal(), and update().
doFinal() [3/3]
ByteArray Hmac::doFinal () throw (HmacException, InvalidStateException)
Gerar o hmac.
Returns
bytes que representam o hmac.
Exceptions
HmacException caso ocorra erro ao finalizar o contexto do hmac do OpenSSL.
InvalidStateException caso o objeto Hmac não tenha sido inicializado corretamente ou caso não tenha sido passado o conteúdo para calculo do hmac.
References ctx, HmacException::CTX_FINISH, INIT, NO_INIT, ByteArray::setDataPointer(), and state.
Referenced by doFinal().
init() [1/4]
void Hmac::init (ByteArray & key, MessageDigest::Algorithm algorithm) throw (HmacException)
Inicializar a estrutura do hmac.
Parameters
key chave secreta.
algorithm algoritmo de resumo.
Exceptions
HmacException caso ocorra erro ao inicializar a estrutura do hmac do OpenSSL.
References algorithm, ctx, HmacException::CTX_INIT, MessageDigest::getMessageDigest(), INIT, NO_INIT, and state.
Referenced by Hmac(), and init().
init() [2/4]
void Hmac::init (ByteArray & key, MessageDigest::Algorithm algorithm, Engine & engine) throw (HmacException)
Inicializar a estrutura do hmac.
Parameters
key chave secreta.
algorithm algoritmo de resumo.
engine objeto Engine.
Exceptions
HmacException caso ocorra erro ao inicializar a estrutura do hmac do OpenSSL.
References algorithm, ctx, HmacException::CTX_INIT, MessageDigest::getMessageDigest(), INIT, NO_INIT, and state.
init() [3/4]
void Hmac::init (std::string key, MessageDigest::Algorithm algorithm) throw (HmacException)
Inicializar a estrutura do hmac.
Parameters
key chave secreta.
algorithm algoritmo de resumo.
Exceptions
HmacException caso ocorra erro ao inicializar a estrutura do hmac do OpenSSL.
References algorithm, and init().
init() [4/4]
void Hmac::init (std::string key, MessageDigest::Algorithm algorithm, Engine & engine) throw (HmacException)
Inicializar a estrutura do hmac.
Parameters
key chave secreta.
algorithm algoritmo de resumo.
engine objeto Engine.
Exceptions
HmacException caso ocorra erro ao inicializar a estrutura do hmac do OpenSSL.
References algorithm, and init().
update() [1/4]
void Hmac::update (ByteArray & data) throw (HmacException, InvalidStateException)
Atualizar/concatenar o conteúdo de entrada do hmac.
Parameters
data conteúdo para geração do hmac.
Exceptions
HmacException caso ocorra erro ao atualizar o contexto do hmac do OpenSSL.
InvalidStateException caso o objeto Hmac não tenha sido inicializado corretamente.
References ctx, HmacException::CTX_UPDATE, NO_INIT, state, and UPDATE.
Referenced by doFinal(), and update().
update() [2/4]
void Hmac::update (std::string data) throw (HmacException, InvalidStateException)
Atualizar/concatenar o conteúdo de entrada do hmac.
Parameters
data conteúdo para geração do hmac.
Exceptions
HmacException caso ocorra erro ao atualizar o contexto do hmac do OpenSSL.
InvalidStateException caso o objeto Hmac não tenha sido inicializado corretamente.
References update().
update() [3/4]
void Hmac::update (std::vector< std::string > & data) throw (HmacException, InvalidStateException)
Atualizar/concatenar o conteúdo de entrada do hmac.
Parameters
data conteúdo para geração do hmac usando vector<string>.
Exceptions
HmacException caso ocorra erro ao atualizar o contexto do hmac do OpenSSL.
InvalidStateException caso o objeto Hmac não tenha sido inicializado corretamente.
References update().
update() [4/4]
void Hmac::update (std::vector< ByteArray > & data) throw (HmacException, InvalidStateException)
Atualizar/concatenar o conteúdo de entrada do hmac.
Parameters
data conteúdo para geração do hmac usando vector<ByteArray>.
Exceptions
HmacException caso ocorra erro ao atualizar o contexto do hmac do OpenSSL.
InvalidStateException caso o objeto Hmac não tenha sido inicializado corretamente.
References update().
Member Data Documentation
algorithm
MessageDigest::Algorithm Hmac::algorithm protected
Algoritmo selecionado.
Referenced by Hmac(), and init().
ctx
HMAC_CTX Hmac::ctx protected
Estrutura OpenSSL que representa o Hmac.
Referenced by doFinal(), init(), and update().
state
State Hmac::state protected
Estado das estruturas de resumo.
Referenced by doFinal(), Hmac(), init(), and update().
The documentation for this class was generated from the following files:
include/libcryptosec/Hmac.h
src/Hmac.cpp