libcryptosec Documentation
Extension Class Reference
#include <Extension.h>
Public Types
enum Name {
UNKNOWN, KEY_USAGE, EXTENDED_KEY_USAGE, AUTHORITY_KEY_IDENTIFIER,
CRL_DISTRIBUTION_POINTS, AUTHORITY_INFORMATION_ACCESS, BASIC_CONSTRAINTS, CERTIFICATE_POLICIES,
ISSUER_ALTERNATIVE_NAME, SUBJECT_ALTERNATIVE_NAME, SUBJECT_INFORMATION_ACCESS, SUBJECT_KEY_IDENTIFIER,
CRL_NUMBER, DELTA_CRL_INDICATOR
}
Public Member Functions
Extension (X509_EXTENSION *ext) throw (CertificationException)
Extension (std::string oid, bool critical, std::string valueBase64) throw (CertificationException)
virtual ~Extension ()
virtual std::string getXmlEncoded ()
virtual std::string getXmlEncoded (std::string tab)
std::string toXml (std::string tab="") throw (CertificationException)
virtual std::string extValue2Xml (std::string tab="")
ObjectIdentifier getObjectIdentifier () const
std::string getName ()
Extension::Name getTypeName ()
ByteArray getValue () const
std::string getBase64Value ()
void setCritical (bool critical)
bool isCritical () const
virtual X509_EXTENSION * getX509Extension ()
Static Public Member Functions
static Extension::Name getName (int nid)
static Extension::Name getName (X509_EXTENSION *ext)
Protected Member Functions
Extension ()
Protected Attributes
ObjectIdentifier objectIdentifier
bool critical
ByteArray value
Member Enumeration Documentation
Name
enum Extension::Name
Enumerator
UNKNOWN
KEY_USAGE
EXTENDED_KEY_USAGE
AUTHORITY_KEY_IDENTIFIER
CRL_DISTRIBUTION_POINTS
AUTHORITY_INFORMATION_ACCESS
BASIC_CONSTRAINTS
CERTIFICATE_POLICIES
ISSUER_ALTERNATIVE_NAME
SUBJECT_ALTERNATIVE_NAME
SUBJECT_INFORMATION_ACCESS
SUBJECT_KEY_IDENTIFIER
CRL_NUMBER
DELTA_CRL_INDICATOR
Constructor & Destructor Documentation
Extension() [1/3]
Extension::Extension (X509_EXTENSION * ext) throw (CertificationException)
References critical, CertificationException::INVALID_EXTENSION, objectIdentifier, and value.
Extension() [2/3]
Extension::Extension (std::string oid, bool critical, std::string valueBase64) throw (CertificationException)
References critical, Base64::decode(), ObjectIdentifierFactory::getObjectIdentifier(), objectIdentifier, and value.
~Extension()
Extension::~Extension () virtual
Extension() [3/3]
Extension::Extension () protected
References critical.
Member Function Documentation
extValue2Xml()
std::string Extension::extValue2Xml (std::string tab = "") virtual
Reimplemented in KeyUsageExtension, AuthorityInformationAccessExtension, SubjectInformationAccessExtension, CertificatePoliciesExtension, AuthorityKeyIdentifierExtension, CRLDistributionPointsExtension, CRLNumberExtension, IssuerAlternativeNameExtension, SubjectAlternativeNameExtension, ExtendedKeyUsageExtension, SubjectKeyIdentifierExtension, DeltaCRLIndicatorExtension, and BasicConstraintsExtension.
References getBase64Value().
Referenced by toXml().
getBase64Value()
std::string Extension::getBase64Value ()
References Base64::encode(), and value.
Referenced by extValue2Xml(), and getXmlEncoded().
getName() [1/3]
std::string Extension::getName ()
References ObjectIdentifier::getName(), and objectIdentifier.
Referenced by CertificateRevocationList::getExtension(), Certificate::getExtension(), CertificateRequest::getExtension(), CertificateRevocationListBuilder::getExtension(), CertificateBuilder::getExtension(), CertificateRevocationList::getExtensions(), Certificate::getExtensions(), CertificateRequest::getExtensions(), CertificateRevocationListBuilder::getExtensions(), CertificateBuilder::getExtensions(), getName(), getTypeName(), CertificateRevocationList::getUnknownExtensions(), Certificate::getUnknownExtensions(), CertificateRequest::getUnknownExtensions(), CertificateRevocationListBuilder::getUnknownExtensions(), CertificateBuilder::getUnknownExtensions(), BasicConstraintsExtension::getXmlEncoded(), DeltaCRLIndicatorExtension::getXmlEncoded(), SubjectKeyIdentifierExtension::getXmlEncoded(), ExtendedKeyUsageExtension::getXmlEncoded(), IssuerAlternativeNameExtension::getXmlEncoded(), SubjectAlternativeNameExtension::getXmlEncoded(), CRLNumberExtension::getXmlEncoded(), CRLDistributionPointsExtension::getXmlEncoded(), AuthorityKeyIdentifierExtension::getXmlEncoded(), CertificatePoliciesExtension::getXmlEncoded(), SubjectInformationAccessExtension::getXmlEncoded(), AuthorityInformationAccessExtension::getXmlEncoded(), KeyUsageExtension::getXmlEncoded(), getXmlEncoded(), CertificateRequest::removeExtension(), CertificateBuilder::removeExtension(), and toXml().
getName() [2/3]
Extension::Name Extension::getName (int nid) static
References AUTHORITY_INFORMATION_ACCESS, AUTHORITY_KEY_IDENTIFIER, BASIC_CONSTRAINTS, CERTIFICATE_POLICIES, CRL_DISTRIBUTION_POINTS, CRL_NUMBER, DELTA_CRL_INDICATOR, EXTENDED_KEY_USAGE, ISSUER_ALTERNATIVE_NAME, KEY_USAGE, SUBJECT_ALTERNATIVE_NAME, SUBJECT_INFORMATION_ACCESS, SUBJECT_KEY_IDENTIFIER, and UNKNOWN.
getName() [3/3]
Extension::Name Extension::getName (X509_EXTENSION * ext) static
References getName().
getObjectIdentifier()
ObjectIdentifier Extension::getObjectIdentifier () const
References objectIdentifier.
Referenced by toXml().
getTypeName()
Extension::Name Extension::getTypeName ()
References getName(), ObjectIdentifier::getNid(), and objectIdentifier.
getValue()
ByteArray Extension::getValue () const
References value.
getX509Extension()
X509_EXTENSION * Extension::getX509Extension () virtual
Reimplemented in KeyUsageExtension, AuthorityKeyIdentifierExtension, CertificatePoliciesExtension, CRLDistributionPointsExtension, CRLNumberExtension, IssuerAlternativeNameExtension, SubjectAlternativeNameExtension, ExtendedKeyUsageExtension, SubjectKeyIdentifierExtension, DeltaCRLIndicatorExtension, AuthorityInformationAccessExtension, BasicConstraintsExtension, and SubjectInformationAccessExtension.
References critical, ByteArray::getDataPointer(), ObjectIdentifier::getObjectIdentifier(), objectIdentifier, ByteArray::size(), and value.
Referenced by CertificateRequest::addExtension().
getXmlEncoded() [1/2]
std::string Extension::getXmlEncoded () virtual
Deprecated:
Retorna o conteudo da extensão em formato XML.
Esta função será substituida por toXml().
Reimplemented in KeyUsageExtension, AuthorityInformationAccessExtension, SubjectInformationAccessExtension, CertificatePoliciesExtension, AuthorityKeyIdentifierExtension, CRLDistributionPointsExtension, CRLNumberExtension, IssuerAlternativeNameExtension, SubjectAlternativeNameExtension, ExtendedKeyUsageExtension, SubjectKeyIdentifierExtension, DeltaCRLIndicatorExtension, and BasicConstraintsExtension.
getXmlEncoded() [2/2]
std::string Extension::getXmlEncoded (std::string tab) virtual
Reimplemented in KeyUsageExtension, AuthorityInformationAccessExtension, SubjectInformationAccessExtension, CertificatePoliciesExtension, AuthorityKeyIdentifierExtension, CRLDistributionPointsExtension, CRLNumberExtension, IssuerAlternativeNameExtension, SubjectAlternativeNameExtension, ExtendedKeyUsageExtension, SubjectKeyIdentifierExtension, DeltaCRLIndicatorExtension, and BasicConstraintsExtension.
References critical, getBase64Value(), getName(), and isCritical().
isCritical()
bool Extension::isCritical () const
References critical.
Referenced by KeyUsageExtension::getX509Extension(), BasicConstraintsExtension::getXmlEncoded(), DeltaCRLIndicatorExtension::getXmlEncoded(), SubjectKeyIdentifierExtension::getXmlEncoded(), ExtendedKeyUsageExtension::getXmlEncoded(), CRLNumberExtension::getXmlEncoded(), CRLDistributionPointsExtension::getXmlEncoded(), CertificatePoliciesExtension::getXmlEncoded(), SubjectInformationAccessExtension::getXmlEncoded(), AuthorityInformationAccessExtension::getXmlEncoded(), KeyUsageExtension::getXmlEncoded(), getXmlEncoded(), and toXml().
setCritical()
void Extension::setCritical (bool critical)
References critical.
toXml()
std::string Extension::toXml (std::string tab = "") throw (CertificationException)
References critical, extValue2Xml(), getName(), getObjectIdentifier(), ObjectIdentifier::getOid(), and isCritical().
Member Data Documentation
critical
bool Extension::critical protected
Referenced by Extension(), SubjectInformationAccessExtension::getX509Extension(), AuthorityInformationAccessExtension::getX509Extension(), BasicConstraintsExtension::getX509Extension(), DeltaCRLIndicatorExtension::getX509Extension(), ExtendedKeyUsageExtension::getX509Extension(), SubjectKeyIdentifierExtension::getX509Extension(), IssuerAlternativeNameExtension::getX509Extension(), SubjectAlternativeNameExtension::getX509Extension(), CRLDistributionPointsExtension::getX509Extension(), CertificatePoliciesExtension::getX509Extension(), AuthorityKeyIdentifierExtension::getX509Extension(), getX509Extension(), SubjectAlternativeNameExtension::getXmlEncoded(), IssuerAlternativeNameExtension::getXmlEncoded(), AuthorityKeyIdentifierExtension::getXmlEncoded(), getXmlEncoded(), isCritical(), setCritical(), and toXml().
objectIdentifier
ObjectIdentifier Extension::objectIdentifier protected
Referenced by AuthorityInformationAccessExtension::AuthorityInformationAccessExtension(), AuthorityKeyIdentifierExtension::AuthorityKeyIdentifierExtension(), BasicConstraintsExtension::BasicConstraintsExtension(), CertificatePoliciesExtension::CertificatePoliciesExtension(), CRLDistributionPointsExtension::CRLDistributionPointsExtension(), CRLNumberExtension::CRLNumberExtension(), DeltaCRLIndicatorExtension::DeltaCRLIndicatorExtension(), ExtendedKeyUsageExtension::ExtendedKeyUsageExtension(), Extension(), getName(), getObjectIdentifier(), getTypeName(), getX509Extension(), IssuerAlternativeNameExtension::IssuerAlternativeNameExtension(), KeyUsageExtension::KeyUsageExtension(), SubjectAlternativeNameExtension::SubjectAlternativeNameExtension(), SubjectInformationAccessExtension::SubjectInformationAccessExtension(), and SubjectKeyIdentifierExtension::SubjectKeyIdentifierExtension().
value
ByteArray Extension::value protected
Referenced by ExtendedKeyUsageExtension::ExtendedKeyUsageExtension(), Extension(), BasicConstraintsExtension::extValue2Xml(), getBase64Value(), getValue(), getX509Extension(), BasicConstraintsExtension::getXmlEncoded(), BasicConstraintsExtension::setCa(), BasicConstraintsExtension::setPathLen(), and KeyUsageExtension::setUsage().
The documentation for this class was generated from the following files:
include/libcryptosec/certificate/Extension.h
src/certificate/Extension.cpp