libcryptosec Documentation
IssuerAlternativeNameExtension Class Reference
#include <IssuerAlternativeNameExtension.h>
Public Member Functions
IssuerAlternativeNameExtension ()
IssuerAlternativeNameExtension (X509_EXTENSION *ext) throw (CertificationException)
virtual ~IssuerAlternativeNameExtension ()
std::string getXmlEncoded ()
std::string getXmlEncoded (std::string tab)
virtual std::string extValue2Xml (std::string tab="")
void setIssuerAltName (GeneralNames &generalNames)
GeneralNames getIssuerAltName ()
X509_EXTENSION * getX509Extension ()
Public Member Functions inherited from Extension
Extension (X509_EXTENSION *ext) throw (CertificationException)
Extension (std::string oid, bool critical, std::string valueBase64) throw (CertificationException)
virtual ~Extension ()
std::string toXml (std::string tab="") throw (CertificationException)
ObjectIdentifier getObjectIdentifier () const
std::string getName ()
Extension::Name getTypeName ()
ByteArray getValue () const
std::string getBase64Value ()
void setCritical (bool critical)
bool isCritical () const
Protected Attributes
GeneralNames issuerAltName
Protected Attributes inherited from Extension
ObjectIdentifier objectIdentifier
bool critical
ByteArray value
Additional Inherited Members
Public Types inherited from Extension
enum Name {
UNKNOWN, KEY_USAGE, EXTENDED_KEY_USAGE, AUTHORITY_KEY_IDENTIFIER,
CRL_DISTRIBUTION_POINTS, AUTHORITY_INFORMATION_ACCESS, BASIC_CONSTRAINTS, CERTIFICATE_POLICIES,
ISSUER_ALTERNATIVE_NAME, SUBJECT_ALTERNATIVE_NAME, SUBJECT_INFORMATION_ACCESS, SUBJECT_KEY_IDENTIFIER,
CRL_NUMBER, DELTA_CRL_INDICATOR
}
Static Public Member Functions inherited from Extension
static Extension::Name getName (int nid)
static Extension::Name getName (X509_EXTENSION *ext)
Protected Member Functions inherited from Extension
Extension ()
Constructor & Destructor Documentation
IssuerAlternativeNameExtension() [1/2]
IssuerAlternativeNameExtension::IssuerAlternativeNameExtension ()
References ObjectIdentifierFactory::getObjectIdentifier(), and Extension::objectIdentifier.
IssuerAlternativeNameExtension() [2/2]
IssuerAlternativeNameExtension::IssuerAlternativeNameExtension (X509_EXTENSION * ext) throw (CertificationException)
References CertificationException::INVALID_TYPE, and issuerAltName.
~IssuerAlternativeNameExtension()
IssuerAlternativeNameExtension::~IssuerAlternativeNameExtension () virtual
Member Function Documentation
extValue2Xml()
std::string IssuerAlternativeNameExtension::extValue2Xml (std::string tab = "") virtual
Reimplemented from Extension.
References GeneralNames::getXmlEncoded(), and issuerAltName.
getIssuerAltName()
GeneralNames IssuerAlternativeNameExtension::getIssuerAltName ()
References issuerAltName.
getX509Extension()
X509_EXTENSION * IssuerAlternativeNameExtension::getX509Extension () virtual
Reimplemented from Extension.
References Extension::critical, GeneralNames::getInternalGeneralNames(), and issuerAltName.
getXmlEncoded() [1/2]
std::string IssuerAlternativeNameExtension::getXmlEncoded () virtual
Deprecated:
Retorna o conteudo da extensão em formato XML.
Esta função será substituida por toXml().
Reimplemented from Extension.
getXmlEncoded() [2/2]
std::string IssuerAlternativeNameExtension::getXmlEncoded (std::string tab) virtual
Reimplemented from Extension.
References Extension::critical, Extension::getName(), GeneralNames::getXmlEncoded(), and issuerAltName.
setIssuerAltName()
void IssuerAlternativeNameExtension::setIssuerAltName (GeneralNames & generalNames)
References issuerAltName.
Member Data Documentation
issuerAltName
GeneralNames IssuerAlternativeNameExtension::issuerAltName protected
Referenced by extValue2Xml(), getIssuerAltName(), getX509Extension(), getXmlEncoded(), IssuerAlternativeNameExtension(), and setIssuerAltName().
The documentation for this class was generated from the following files:
include/libcryptosec/certificate/IssuerAlternativeNameExtension.h
src/certificate/IssuerAlternativeNameExtension.cpp