libcryptosec Documentation
Certificate Class Reference
#include <Certificate.h>
Public Member Functions
Certificate (X509 *cert)
Certificate (std::string pemEncoded) throw (EncodeException)
Certificate (ByteArray &derEncoded) throw (EncodeException)
Certificate (const Certificate &cert)
virtual ~Certificate ()
std::string getPemEncoded () const throw (EncodeException)
ByteArray getDerEncoded () const throw (EncodeException)
std::string getXmlEncoded ()
std::string getXmlEncoded (std::string tab)
virtual std::string toXml (std::string tab="")
long getSerialNumber () throw (CertificationException)
BigInteger getSerialNumberBigInt () throw (CertificationException)
MessageDigest::Algorithm getMessageDigestAlgorithm () throw (MessageDigestException)
PublicKey * getPublicKey () throw (CertificationException, AsymmetricKeyException)
ByteArray getPublicKeyInfo () throw (CertificationException)
long getVersion () throw (CertificationException)
DateTime getNotBefore ()
DateTime getNotAfter ()
RDNSequence getIssuer ()
RDNSequence getSubject ()
std::vector< Extension * > getExtension (Extension::Name extensionName)
std::vector< Extension * > getExtensions ()
std::vector< Extension * > getUnknownExtensions ()
ByteArray getFingerPrint (MessageDigest::Algorithm algorithm) const throw (CertificationException, EncodeException, MessageDigestException)
bool verify (PublicKey &publicKey)
X509 * getX509 () const
CertificateRequest getNewCertificateRequest (PrivateKey &privateKey, MessageDigest::Algorithm algorithm) throw (CertificationException)
create a new certificate request using the data from this certificate
Certificate & operator= (const Certificate &value)
bool operator== (const Certificate &value)
bool operator!= (const Certificate &value)
Protected Attributes
X509 * cert
Constructor & Destructor Documentation
Certificate() [1/4]
Certificate::Certificate (X509 * cert)
References cert.
Certificate() [2/4]
Certificate::Certificate (std::string pemEncoded) throw (EncodeException)
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_WRITING, cert, and EncodeException::PEM_DECODE.
Certificate() [3/4]
Certificate::Certificate (ByteArray & derEncoded) throw (EncodeException)
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_WRITING, cert, and EncodeException::DER_DECODE.
Certificate() [4/4]
Certificate::Certificate (const Certificate & cert)
References getX509().
~Certificate()
Certificate::~Certificate () virtual
References cert.
Member Function Documentation
getDerEncoded()
ByteArray Certificate::getDerEncoded () const throw (EncodeException)
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_READING, cert, and EncodeException::DER_ENCODE.
Referenced by getFingerPrint().
getExtension()
std::vector< Extension * > Certificate::getExtension (Extension::Name extensionName)
References Extension::AUTHORITY_INFORMATION_ACCESS, Extension::AUTHORITY_KEY_IDENTIFIER, Extension::BASIC_CONSTRAINTS, cert, Extension::CERTIFICATE_POLICIES, Extension::CRL_DISTRIBUTION_POINTS, Extension::EXTENDED_KEY_USAGE, Extension::getName(), Extension::ISSUER_ALTERNATIVE_NAME, Extension::KEY_USAGE, Extension::SUBJECT_ALTERNATIVE_NAME, Extension::SUBJECT_INFORMATION_ACCESS, and Extension::SUBJECT_KEY_IDENTIFIER.
getExtensions()
std::vector< Extension * > Certificate::getExtensions ()
References Extension::AUTHORITY_INFORMATION_ACCESS, Extension::AUTHORITY_KEY_IDENTIFIER, Extension::BASIC_CONSTRAINTS, cert, Extension::CERTIFICATE_POLICIES, Extension::CRL_DISTRIBUTION_POINTS, Extension::EXTENDED_KEY_USAGE, Extension::getName(), Extension::ISSUER_ALTERNATIVE_NAME, Extension::KEY_USAGE, Extension::SUBJECT_ALTERNATIVE_NAME, Extension::SUBJECT_INFORMATION_ACCESS, and Extension::SUBJECT_KEY_IDENTIFIER.
Referenced by getXmlEncoded(), and toXml().
getFingerPrint()
ByteArray Certificate::getFingerPrint (MessageDigest::Algorithm algorithm) const throw (CertificationException, EncodeException, MessageDigestException)
References MessageDigest::doFinal(), getDerEncoded(), and MessageDigest::init().
getIssuer()
RDNSequence Certificate::getIssuer ()
References cert.
Referenced by getXmlEncoded(), and toXml().
getMessageDigestAlgorithm()
MessageDigest::Algorithm Certificate::getMessageDigestAlgorithm () throw (MessageDigestException)
References cert, and MessageDigest::getMessageDigest().
getNewCertificateRequest()
CertificateRequest Certificate::getNewCertificateRequest (PrivateKey & privateKey, MessageDigest::Algorithm algorithm) throw (CertificationException)
create a new certificate request using the data from this certificate
Parameters
privateKey certificate request signing key
algorithm message digest algorithm
Exceptions
CertificationException error on conversion of x509 to x509 req
References cert, MessageDigest::getMessageDigest(), and CertificationException::INTERNAL_ERROR.
getNotAfter()
DateTime Certificate::getNotAfter ()
References cert.
Referenced by getXmlEncoded(), and toXml().
getNotBefore()
DateTime Certificate::getNotBefore ()
References cert.
Referenced by getXmlEncoded(), and toXml().
getPemEncoded()
std::string Certificate::getPemEncoded () const throw (EncodeException)
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_READING, cert, EncodeException::PEM_ENCODE, and ByteArray::toString().
getPublicKey()
PublicKey * Certificate::getPublicKey () throw (CertificationException, AsymmetricKeyException)
References cert, CertificationException::INVALID_CERTIFICATE, and CertificationException::SET_NO_VALUE.
getPublicKeyInfo()
ByteArray Certificate::getPublicKeyInfo () throw (CertificationException)
References cert, ByteArray::getDataPointer(), and CertificationException::SET_NO_VALUE.
getSerialNumber()
long int Certificate::getSerialNumber () throw (CertificationException)
References cert, CertificationException::INTERNAL_ERROR, CertificationException::INVALID_CERTIFICATE, and CertificationException::SET_NO_VALUE.
Referenced by getXmlEncoded().
getSerialNumberBigInt()
BigInteger Certificate::getSerialNumberBigInt () throw (CertificationException)
References cert, CertificationException::INTERNAL_ERROR, CertificationException::INVALID_CERTIFICATE, and CertificationException::SET_NO_VALUE.
Referenced by toXml().
getSubject()
RDNSequence Certificate::getSubject ()
References cert.
Referenced by getXmlEncoded(), and toXml().
getUnknownExtensions()
std::vector< Extension * > Certificate::getUnknownExtensions ()
References cert, Extension::getName(), and Extension::UNKNOWN.
getVersion()
long Certificate::getVersion () throw (CertificationException)
References cert, CertificationException::INVALID_CERTIFICATE, and CertificationException::SET_NO_VALUE.
Referenced by getXmlEncoded(), and toXml().
getX509()
X509 * Certificate::getX509 () const
References cert.
Referenced by Certificate(), Pkcs12Builder::doFinal(), Pkcs12::getCertificate(), operator=(), operator==(), CertPathValidatorResult::setInvalidCertificate(), and CertPathValidator::verify().
getXmlEncoded() [1/2]
std::string Certificate::getXmlEncoded ()
Deprecated:
Retorna o conteudo da extensão em formato XML.
Esta função será substituida por toXml().
Referenced by getXmlEncoded(), and toXml().
getXmlEncoded() [2/2]
std::string Certificate::getXmlEncoded (std::string tab)
References cert, Base64::encode(), getExtensions(), getIssuer(), getNotAfter(), getNotBefore(), getSerialNumber(), getSubject(), getVersion(), and getXmlEncoded().
operator!=()
bool Certificate::operator!= (const Certificate & value)
References operator==().
operator=()
Certificate & Certificate::operator= (const Certificate & value)
References cert, and getX509().
operator==()
bool Certificate::operator== (const Certificate & value)
References cert, and getX509().
Referenced by operator!=().
toXml()
std::string Certificate::toXml (std::string tab = "") virtual
References cert, Base64::encode(), getExtensions(), getIssuer(), getNotAfter(), getNotBefore(), getSerialNumberBigInt(), getSubject(), getVersion(), getXmlEncoded(), and BigInteger::toDec().
verify()
bool Certificate::verify (PublicKey & publicKey)
References cert, and AsymmetricKey::getEvpPkey().
Member Data Documentation
cert
X509* Certificate::cert protected
Referenced by Certificate(), getDerEncoded(), getExtension(), getExtensions(), getIssuer(), getMessageDigestAlgorithm(), getNewCertificateRequest(), getNotAfter(), getNotBefore(), getPemEncoded(), getPublicKey(), getPublicKeyInfo(), getSerialNumber(), getSerialNumberBigInt(), getSubject(), getUnknownExtensions(), getVersion(), getX509(), getXmlEncoded(), operator=(), operator==(), toXml(), verify(), and ~Certificate().
The documentation for this class was generated from the following files:
include/libcryptosec/certificate/Certificate.h
src/certificate/Certificate.cpp