libcryptosec Documentation
Random Class Reference
Implementa funcionalidades de um Gerador de Números Aleatórios.
#include <Random.h>
Static Public Member Functions
static ByteArray bytes (int nbytes) throw (RandomException)
Gera bytes randômicos.
static ByteArray pseudoBytes (int nbytes) throw (RandomException)
Gera bytes pseudo-randômicos.
static void seedData (ByteArray &data)
Semeia o Gerador de Número Aleatórios com semente.
static void seedFile (std::string &filename, int nbytes) throw (RandomException)
Semeia o Gerador de Número Aleatórios com semente a partir de um arquivo.
static void cleanSeed ()
Limpa recursos utilizados pelo Gerador de Números Aleatórios.
static bool status ()
Verifica se o Gerador de Números Aleatório foi semeado com dados suficientes.
Detailed Description
Implementa funcionalidades de um Gerador de Números Aleatórios.
Esta classe possui apenas métodos estáticos. Antes de gerar dados randômicos deve-se semear o GNA com dados a partir de qualquer fonte. Esta pode ser um arquivo, bytes randômicos ou dados fornecidos por um hardware (através de uma engine).
Member Function Documentation
bytes()
ByteArray Random::bytes (int nbytes) throw (RandomException) static
Gera bytes randômicos.
Parameters
nbytes quantidade de bytes a ser gerada.
Returns
objeto ByteArray que representa bytes randômicos.
Exceptions
RandomException caso função de geração de bytes não esteja implementada ou caso o gerador não tenha sido semeado.
References ByteArray::getDataPointer(), RandomException::NO_DATA_SEEDED, and RandomException::NO_IMPLEMENTED_FUNCTION.
Referenced by SymmetricKeyGenerator::generateKey().
cleanSeed()
void Random::cleanSeed () static
Limpa recursos utilizados pelo Gerador de Números Aleatórios.
pseudoBytes()
ByteArray Random::pseudoBytes (int nbytes) throw (RandomException) static
Gera bytes pseudo-randômicos.
Parameters
nbytes quantidade de bytes a ser gerada.
Returns
objeto ByteArray que representa bytes pseudo-randômicos.
Exceptions
RandomException caso função de geração de bytes não esteja implementada ou caso o gerador não tenha sido semeado.
References ByteArray::getDataPointer(), RandomException::NO_DATA_SEEDED, and RandomException::NO_IMPLEMENTED_FUNCTION.
seedData()
void Random::seedData (ByteArray & data) static
Semeia o Gerador de Número Aleatórios com semente.
Parameters
data dados aleatórios utilizados como semente.
References ByteArray::getDataPointer(), and ByteArray::size().
seedFile()
void Random::seedFile (std::string & filename, int nbytes) throw (RandomException) static
Semeia o Gerador de Número Aleatórios com semente a partir de um arquivo.
Parameters
filename caminho para arquivo.
nbytes número máximo de bytes a ser lido do conteúdo do arquivo.
References RandomException::INTERNAL_ERROR.
status()
bool Random::status () static
Verifica se o Gerador de Números Aleatório foi semeado com dados suficientes.
return true se o GNA foi semeado com sucesso, false caso contrário.
The documentation for this class was generated from the following files:
include/libcryptosec/Random.h
src/Random.cpp