libcryptosec Documentation
Pkcs7SignedDataBuilder Class Reference
Classes relacionadas ao uso de pacotes PKCS7
Implementa o padrão builder para criação de um pacote PKCS7 assinado digitalmente.
#include <Pkcs7SignedDataBuilder.h>
Public Member Functions
Pkcs7SignedDataBuilder (MessageDigest::Algorithm mesDigAlgorithm, Certificate &cert, PrivateKey &privKey, bool attached) throw (Pkcs7Exception)
Construtor recebendo os parâmetros necessários à assinatura dos dados a serem adicionados ao pacote.
virtual ~Pkcs7SignedDataBuilder ()
Destrutor padrão.
void init (MessageDigest::Algorithm mesDigAlgorithm, Certificate &cert, PrivateKey &privKey, bool attached) throw (Pkcs7Exception)
Método responsável pela inicialização do builder.
void addSigner (MessageDigest::Algorithm mesDigAlgorithm, Certificate &cert, PrivateKey &privKey) throw (Pkcs7Exception, InvalidStateException)
Permite a co-assinatura do pacote por mais de uma chave privada.
void addCertificate (Certificate &cert) throw (Pkcs7Exception, InvalidStateException)
Permite adicionar certificados adicionais.
void addCrl (CertificateRevocationList &crl) throw (Pkcs7Exception, InvalidStateException)
Permite adicionar lista de certificados revogados.
Pkcs7SignedData * doFinal () throw (InvalidStateException, Pkcs7Exception)
Implementa uma versão distinta do método Pkcs7Builder::doFinal() para gerar o pacote assinado.
Pkcs7SignedData * doFinal (std::string &data) throw (InvalidStateException, Pkcs7Exception)
Implementa uma versão distinta do método Pkcs7Builder::doFinal() para gerar o pacote assinado.
Pkcs7SignedData * doFinal (ByteArray &data) throw (InvalidStateException, Pkcs7Exception)
Implementa uma versão distinta do método Pkcs7Builder::doFinal() para gerar o pacote assinado.
Public Member Functions inherited from Pkcs7Builder
Pkcs7Builder ()
Construtor padrão.
~Pkcs7Builder ()
Destrutor padrão.
void update (std::string &data) throw (InvalidStateException, Pkcs7Exception)
Concatena novos dados ao pacote PKCS7.
void update (ByteArray &data) throw (InvalidStateException, Pkcs7Exception)
Concatena novos dados ao pacote PKCS7.
void doFinal (std::istream *in, std::ostream *out) throw (InvalidStateException, Pkcs7Exception, EncodeException)
Gera um pacote PKCS7 a partir de de um stream de entrada e põe o resultado no formato PEM em um stream de saída.
Additional Inherited Members
Protected Types inherited from Pkcs7Builder
enum State { NO_INIT, INIT, UPDATE }
Possíveis estados do builder.
Protected Attributes inherited from Pkcs7Builder
Pkcs7Builder::State state
Estado atual do builder.
PKCS7 * pkcs7
Estrutura OpenSSL que representa o pacote PKCS7.
BIO * p7bio
Estrutura OpenSSL usada na geração do pacote PKCS7.
Detailed Description
Implementa o padrão builder para criação de um pacote PKCS7 assinado digitalmente.
Constructor & Destructor Documentation
Pkcs7SignedDataBuilder()
Pkcs7SignedDataBuilder::Pkcs7SignedDataBuilder (MessageDigest::Algorithm mesDigAlgorithm, Certificate & cert, PrivateKey & privKey, bool attached) throw (Pkcs7Exception)
Construtor recebendo os parâmetros necessários à assinatura dos dados a serem adicionados ao pacote.
O método Pkcs7SignedDataBuilder::init() é invocado nesse construtor.
Parameters
mesDigAlgorithm o algoritmo de hash que será usado na assinatura do pacote.
cert referência para o certificado que será usado para assinar o conteúdo do PKCS7 e irá compor o pacote.
privKey chave privada que será usada na assinatura do pacote.
attached se true, o conteúdo do pacote estará contido no mesmo, caso contrário apenas a assinatura do conteúdo estará presente.
Exceptions
Pkcs7Exception caso ocorra algum problema na geração do pacote PKCS7.
See also
Pkcs7SignedDataBuilder::init()
References Pkcs7Exception::ADDING_CERTIFICATE, Pkcs7Exception::ADDING_SIGNER, MessageDigest::getMessageDigest(), and Pkcs7Builder::INIT.
~Pkcs7SignedDataBuilder()
Pkcs7SignedDataBuilder::~Pkcs7SignedDataBuilder () virtual
Destrutor padrão.
Member Function Documentation
addCertificate()
void Pkcs7SignedDataBuilder::addCertificate (Certificate & cert) throw (Pkcs7Exception, InvalidStateException)
Permite adicionar certificados adicionais.
Parameters
cert referência para certificado que será adicionado
Exceptions
InvalidStateException no caso do builder não ter sido inicializado ainda.
Pkcs7Exception caso tenha ocorrido um erro ao adicionar o certificado ao pacote PKCS7.
References Pkcs7Exception::ADDING_CERTIFICATE, Pkcs7Builder::INIT, Pkcs7Builder::pkcs7, Pkcs7Builder::state, and Pkcs7Builder::UPDATE.
addCrl()
void Pkcs7SignedDataBuilder::addCrl (CertificateRevocationList & crl) throw (Pkcs7Exception, InvalidStateException)
Permite adicionar lista de certificados revogados.
Parameters
crl referência para a CRL que será adicionada
Exceptions
InvalidStateException no caso do builder não ter sido inicializado ainda.
Pkcs7Exception caso tenha ocorrido um erro ao adicionar o certificado ao pacote PKCS7.
References Pkcs7Exception::ADDING_CERTIFICATE, Pkcs7Builder::INIT, Pkcs7Builder::pkcs7, Pkcs7Builder::state, and Pkcs7Builder::UPDATE.
addSigner()
void Pkcs7SignedDataBuilder::addSigner (MessageDigest::Algorithm mesDigAlgorithm, Certificate & cert, PrivateKey & privKey) throw (Pkcs7Exception, InvalidStateException)
Permite a co-assinatura do pacote por mais de uma chave privada.
Parameters
mesDigAlgorithm o algoritmo de hash que será usado na assinatura do pacote.
cert referência para o novo certificado que será adicionado como assinador do pacote.
privKey chave privada que será usada na co-assinatura do pacote.
Exceptions
InvalidStateException no caso do builder não ter sido inicializado ainda.
Pkcs7Exception caso tenha ocorrido um erro ao adicionar o certificado ao pacote PKCS7.
References Pkcs7Exception::ADDING_CERTIFICATE, Pkcs7Exception::ADDING_SIGNER, MessageDigest::getMessageDigest(), Pkcs7Builder::INIT, Pkcs7Builder::pkcs7, and Pkcs7Builder::state.
doFinal() [1/3]
Pkcs7SignedData * Pkcs7SignedDataBuilder::doFinal () throw (InvalidStateException, Pkcs7Exception)
Implementa uma versão distinta do método Pkcs7Builder::doFinal() para gerar o pacote assinado.
Returns
Pkcs7EnvelopedData o pacote PKCS7 criado.
Exceptions
InvalidStateException caso o builder não esteja no estado apropriado no momento da invocação.
Pkcs7Exception caso tenha ocorrido um erro na geração do pacote PKCS7.
References Pkcs7Exception::INTERNAL_ERROR, Pkcs7Builder::NO_INIT, Pkcs7Builder::p7bio, Pkcs7Builder::pkcs7, Pkcs7Builder::state, and Pkcs7Builder::UPDATE.
Referenced by doFinal().
doFinal() [2/3]
Pkcs7SignedData * Pkcs7SignedDataBuilder::doFinal (std::string & data) throw (InvalidStateException, Pkcs7Exception)
Implementa uma versão distinta do método Pkcs7Builder::doFinal() para gerar o pacote assinado.
Parameters
data contendo dados a serem concatenados ao conteudo do pacote antes da sua criação definitiva.
Returns
Pkcs7EnvelopedData o pacote PKCS7 criado.
Exceptions
InvalidStateException caso o builder não esteja no estado apropriado no momento da invocação.
Pkcs7Exception caso tenha ocorrido um erro na geração do pacote PKCS7.
References doFinal(), and Pkcs7Builder::update().
doFinal() [3/3]
Pkcs7SignedData * Pkcs7SignedDataBuilder::doFinal (ByteArray & data) throw (InvalidStateException, Pkcs7Exception)
Implementa uma versão distinta do método Pkcs7Builder::doFinal() para gerar o pacote assinado.
Parameters
data contendo dados a serem concatenados ao conteudo do pacote antes da sua criação definitiva.
Returns
Pkcs7EnvelopedData o pacote PKCS7 criado.
Exceptions
InvalidStateException caso o builder não esteja no estado apropriado no momento da invocação.
Pkcs7Exception caso tenha ocorrido um erro na geração do pacote PKCS7.
References doFinal(), and Pkcs7Builder::update().
init()
void Pkcs7SignedDataBuilder::init (MessageDigest::Algorithm mesDigAlgorithm, Certificate & cert, PrivateKey & privKey, bool attached) throw (Pkcs7Exception)
Método responsável pela inicialização do builder.
Após sua invocação, o builder estará pronto para receber os dados a serem empacotados. Pode ser usado também para reinicializar o mesmo com a mudança de um ou mais parâmetros.
Parameters
mesDigAlgorithm o algoritmo de hash que será usado na assinatura do pacote.
cert referência para o certificado que será usado para assinar o conteúdo do PKCS7 e irá compor o pacote.
privKey chave privada que será usada na assinatura do pacote.
attached se true, o conteúdo do pacote estará contido no mesmo, caso contrário apenas a assinatura do conteúdo estará presente.
Exceptions
Pkcs7Exception caso ocorra algum problema na criação do pacote PKCS7.
References Pkcs7Exception::ADDING_CERTIFICATE, Pkcs7Exception::ADDING_SIGNER, MessageDigest::getMessageDigest(), Pkcs7Builder::INIT, Pkcs7Builder::NO_INIT, Pkcs7Builder::p7bio, Pkcs7Builder::pkcs7, Pkcs7Builder::state, and Pkcs7Builder::UPDATE.
The documentation for this class was generated from the following files:
include/libcryptosec/Pkcs7SignedDataBuilder.h
src/Pkcs7SignedDataBuilder.cpp