libcryptosec Documentation
Signer Class Reference
Classes Relacionadas Utilitárias de Criptografia
Implementa funcionalidades de assinatura assimétrica, bem como a verificação dessa.
#include <Signer.h>
Static Public Member Functions
static ByteArray sign (PrivateKey &key, ByteArray &hash, MessageDigest::Algorithm algorithm) throw (SignerException)
Realiza assinatura assimétrica.
static bool verify (PublicKey &key, ByteArray &signature, ByteArray &hash, MessageDigest::Algorithm algorithm) throw (SignerException)
Verifica assinatura assimétrica.
Detailed Description
Implementa funcionalidades de assinatura assimétrica, bem como a verificação dessa.
Member Function Documentation
sign()
ByteArray Signer::sign (PrivateKey & key, ByteArray & hash, MessageDigest::Algorithm algorithm) throw (SignerException) static
Realiza assinatura assimétrica.
Parameters
key chave privada.
hash bytes que representam o hash.
algorithm algoritmo de criptografia assimétrica.
Returns
bytes que representam a assinatura digital.
Exceptions
SignerException caso o algoritmo solicitado não seja suportado ou caso ocorra algum erro interno durante a cifragem.
See also
PrivateKey
ByteArray
MessageDigest::Algorithm
References AsymmetricKey::DSA, AsymmetricKey::ECDSA, ByteArray::getDataPointer(), MessageDigest::getMessageDigest(), AsymmetricKey::RSA, SignerException::SIGNING_DATA, and SignerException::UNSUPPORTED_ASYMMETRIC_KEY_TYPE.
verify()
bool Signer::verify (PublicKey & key, ByteArray & signature, ByteArray & hash, MessageDigest::Algorithm algorithm) throw (SignerException) static
Verifica assinatura assimétrica.
Parameters
key chave pública.
signature bytes que representam a assinatura assimétrica.
hash bytes que representam o hash.
algorithm algoritmo de criptografia assimétrica.
Returns
true caso a assinatura seja verificada, false caso contrário.
Exceptions
SignerException caso o algoritmo solicitado não seja suportado ou caso ocorra algum erro interno durante a verificação.
See also
PublicKey
ByteArray
MessageDigest::Algorithm
References AsymmetricKey::DSA, AsymmetricKey::ECDSA, MessageDigest::getMessageDigest(), AsymmetricKey::RSA, SignerException::UNSUPPORTED_ASYMMETRIC_KEY_TYPE, and SignerException::VERIFYING_DATA.
The documentation for this class was generated from the following files:
include/libcryptosec/Signer.h
src/Signer.cpp