libcryptosec Documentation
CertificationException Class Reference
#include <CertificationException.h>
Public Types
enum ErrorCode {
UNKNOWN, INVALID_CERTIFICATE, INVALID_CRL, INVALID_EXTENSION,
SET_NO_VALUE, INTERNAL_ERROR, UNSUPPORTED_ASYMMETRIC_KEY_TYPE, INVALID_TYPE,
ADDING_EXTENSION, UNKNOWN_OID, KNOWN_OID
}
Public Member Functions
CertificationException (std::string where)
CertificationException (CertificationException::ErrorCode errorCode, std::string where)
virtual ~CertificationException () throw ()
virtual std::string getMessage () const
virtual std::string toString () const
virtual CertificationException::ErrorCode getErrorCode ()
Public Member Functions inherited from LibCryptoSecException
virtual ~LibCryptoSecException () throw ()
virtual const char * what () const throw ()
virtual const std::string getDetails () const throw ()
Static Public Member Functions
static std::string errorCode2Message (CertificationException::ErrorCode errorCode)
Protected Attributes
CertificationException::ErrorCode errorCode
Protected Attributes inherited from LibCryptoSecException
std::string where
std::string details
Member Enumeration Documentation
ErrorCode
enum CertificationException::ErrorCode
Enumerator
UNKNOWN
INVALID_CERTIFICATE
INVALID_CRL
INVALID_EXTENSION
SET_NO_VALUE
INTERNAL_ERROR
UNSUPPORTED_ASYMMETRIC_KEY_TYPE
INVALID_TYPE
ADDING_EXTENSION
UNKNOWN_OID
KNOWN_OID
Constructor & Destructor Documentation
CertificationException() [1/2]
CertificationException::CertificationException (std::string where) inline
References errorCode, UNKNOWN, and LibCryptoSecException::where.
CertificationException() [2/2]
CertificationException::CertificationException (CertificationException::ErrorCode errorCode, std::string where) inline
References errorCode, and LibCryptoSecException::where.
~CertificationException()
virtual CertificationException::~CertificationException () throw () inline virtual
Member Function Documentation
errorCode2Message()
static std::string CertificationException::errorCode2Message (CertificationException::ErrorCode errorCode) inline static
References ADDING_EXTENSION, INTERNAL_ERROR, INVALID_CERTIFICATE, INVALID_CRL, INVALID_EXTENSION, INVALID_TYPE, KNOWN_OID, SET_NO_VALUE, UNKNOWN, UNKNOWN_OID, and UNSUPPORTED_ASYMMETRIC_KEY_TYPE.
Referenced by getMessage(), and toString().
getErrorCode()
virtual CertificationException::ErrorCode CertificationException::getErrorCode () inline virtual
References errorCode.
getMessage()
virtual std::string CertificationException::getMessage () const inline virtual
Implements LibCryptoSecException.
References errorCode, and errorCode2Message().
toString()
virtual std::string CertificationException::toString () const inline virtual
Implements LibCryptoSecException.
References errorCode, errorCode2Message(), UNKNOWN, and LibCryptoSecException::where.
Member Data Documentation
errorCode
CertificationException::ErrorCode CertificationException::errorCode protected
Referenced by CertificationException(), getErrorCode(), getMessage(), and toString().
The documentation for this class was generated from the following file:
include/libcryptosec/exception/CertificationException.h