libcryptosec Documentation
Base64 Class Reference
Classes Relacionadas Utilitárias de Criptografia
class to perform base64 encode/decode.
#include <Base64.h>
Static Public Member Functions
static std::string encode (ByteArray &data)
encode data (readable/unreadable) to base64 format data to be encoded
static ByteArray decode (std::string &data)
decode base64 format data to data (readable/unreadable) data to be decoded
Detailed Description
class to perform base64 encode/decode.
Implements only static functions.
Member Function Documentation
decode()
ByteArray Base64::decode (std::string & data) static
decode base64 format data to data (readable/unreadable) data to be decoded
Returns
decoded data
References ByteArray::getDataPointer(), and ByteArray::size().
Referenced by ECDSAKeyPair::ECDSAKeyPair(), and Extension::Extension().
encode()
std::string Base64::encode (ByteArray & data) static
encode data (readable/unreadable) to base64 format data to be encoded
Returns
encoded data
References ByteArray::getDataPointer(), and ByteArray::size().
Referenced by SubjectKeyIdentifierExtension::extValue2Xml(), AuthorityKeyIdentifierExtension::extValue2Xml(), Extension::getBase64Value(), SubjectKeyIdentifierExtension::getXmlEncoded(), AuthorityKeyIdentifierExtension::getXmlEncoded(), CertificateRevocationList::getXmlEncoded(), CertificateRequest::getXmlEncoded(), CertificateBuilder::getXmlEncoded(), Certificate::getXmlEncoded(), CertificateRequest::toXml(), CertificateBuilder::toXml(), and Certificate::toXml().
The documentation for this class was generated from the following files:
include/libcryptosec/Base64.h
src/Base64.cpp