libcryptosec Documentation
EncodeException Class Reference
#include <EncodeException.h>
Public Types
enum ErrorCode {
UNKNOWN = 0, BUFFER_CREATING = 1, BUFFER_READING = 2, BUFFER_WRITING = 3,
DER_ENCODE = 4, DER_DECODE = 5, PEM_ENCODE = 6, PEM_DECODE = 7,
BASE64_ENCODE = 8, BASE64_DECODE = 9
}
Public Member Functions
EncodeException (std::string where)
EncodeException (EncodeException::ErrorCode errorCode, std::string where)
virtual ~EncodeException () throw ()
virtual std::string getMessage () const
virtual std::string toString () const
virtual EncodeException::ErrorCode getErrorCode ()
Public Member Functions inherited from LibCryptoSecException
virtual ~LibCryptoSecException () throw ()
virtual const char * what () const throw ()
virtual const std::string getDetails () const throw ()
Static Public Member Functions
static std::string errorCode2Message (EncodeException::ErrorCode errorCode)
Protected Attributes
EncodeException::ErrorCode errorCode
Protected Attributes inherited from LibCryptoSecException
std::string where
std::string details
Member Enumeration Documentation
ErrorCode
enum EncodeException::ErrorCode
Enumerator
UNKNOWN
BUFFER_CREATING
BUFFER_READING
BUFFER_WRITING
DER_ENCODE
DER_DECODE
PEM_ENCODE
PEM_DECODE
BASE64_ENCODE
BASE64_DECODE
Constructor & Destructor Documentation
EncodeException() [1/2]
EncodeException::EncodeException (std::string where) inline
References errorCode, UNKNOWN, and LibCryptoSecException::where.
EncodeException() [2/2]
EncodeException::EncodeException (EncodeException::ErrorCode errorCode, std::string where) inline
References errorCode, and LibCryptoSecException::where.
~EncodeException()
virtual EncodeException::~EncodeException () throw () inline virtual
Member Function Documentation
errorCode2Message()
static std::string EncodeException::errorCode2Message (EncodeException::ErrorCode errorCode) inline static
References BASE64_DECODE, BASE64_ENCODE, BUFFER_CREATING, BUFFER_READING, BUFFER_WRITING, DER_DECODE, DER_ENCODE, PEM_DECODE, PEM_ENCODE, and UNKNOWN.
Referenced by getMessage(), and toString().
getErrorCode()
virtual EncodeException::ErrorCode EncodeException::getErrorCode () inline virtual
References errorCode.
getMessage()
virtual std::string EncodeException::getMessage () const inline virtual
Implements LibCryptoSecException.
References errorCode, and errorCode2Message().
toString()
virtual std::string EncodeException::toString () const inline virtual
Implements LibCryptoSecException.
References errorCode, errorCode2Message(), UNKNOWN, and LibCryptoSecException::where.
Member Data Documentation
errorCode
EncodeException::ErrorCode EncodeException::errorCode protected
Referenced by EncodeException(), getErrorCode(), getMessage(), and toString().
The documentation for this class was generated from the following file:
include/libcryptosec/exception/EncodeException.h