libcryptosec Documentation
SignerException Class Reference
#include <SignerException.h>
Public Types
enum ErrorCode { UNKNOWN, SIGNING_DATA, VERIFYING_DATA, UNSUPPORTED_ASYMMETRIC_KEY_TYPE }
Public Member Functions
SignerException (std::string where)
SignerException (SignerException::ErrorCode errorCode, std::string where)
virtual ~SignerException () throw ()
virtual std::string getMessage () const
virtual std::string toString () const
virtual SignerException::ErrorCode getErrorCode ()
Public Member Functions inherited from LibCryptoSecException
virtual ~LibCryptoSecException () throw ()
virtual const char * what () const throw ()
virtual const std::string getDetails () const throw ()
Static Public Member Functions
static std::string errorCode2Message (SignerException::ErrorCode errorCode)
Protected Attributes
SignerException::ErrorCode errorCode
Protected Attributes inherited from LibCryptoSecException
std::string where
std::string details
Member Enumeration Documentation
ErrorCode
enum SignerException::ErrorCode
Enumerator
UNKNOWN
SIGNING_DATA
VERIFYING_DATA
UNSUPPORTED_ASYMMETRIC_KEY_TYPE
Constructor & Destructor Documentation
SignerException() [1/2]
SignerException::SignerException (std::string where) inline
References errorCode, UNKNOWN, and LibCryptoSecException::where.
SignerException() [2/2]
SignerException::SignerException (SignerException::ErrorCode errorCode, std::string where) inline
References errorCode, and LibCryptoSecException::where.
~SignerException()
virtual SignerException::~SignerException () throw () inline virtual
Member Function Documentation
errorCode2Message()
static std::string SignerException::errorCode2Message (SignerException::ErrorCode errorCode) inline static
References SIGNING_DATA, UNKNOWN, UNSUPPORTED_ASYMMETRIC_KEY_TYPE, and VERIFYING_DATA.
Referenced by getMessage(), and toString().
getErrorCode()
virtual SignerException::ErrorCode SignerException::getErrorCode () inline virtual
References errorCode.
getMessage()
virtual std::string SignerException::getMessage () const inline virtual
Implements LibCryptoSecException.
References errorCode, and errorCode2Message().
toString()
virtual std::string SignerException::toString () const inline virtual
Implements LibCryptoSecException.
References errorCode, errorCode2Message(), UNKNOWN, and LibCryptoSecException::where.
Member Data Documentation
errorCode
SignerException::ErrorCode SignerException::errorCode protected
Referenced by getErrorCode(), getMessage(), SignerException(), and toString().
The documentation for this class was generated from the following file:
include/libcryptosec/exception/SignerException.h