libcryptosec Documentation
KeyPair Class Reference
Classes relacionadas ao uso de chaves assimétricas.
Representa um par de chaves assimétricas.
#include <KeyPair.h>
Public Member Functions
KeyPair (AsymmetricKey::Algorithm algorithm, int length) throw (AsymmetricKeyException)
create a KeyPair object, creating a new key pair
KeyPair (Engine *engine, std::string keyId) throw (EngineException)
KeyPair (std::string pemEncoded, ByteArray passphrase) throw (EncodeException)
create a KeyPair object, loading the key pair from encoded (PEM format), decrypting with key
KeyPair (std::string pemEncoded) throw (EncodeException)
create a KeyPair object, loading the key pair from encoded (PEM format)
KeyPair (ByteArray derEncoded) throw (EncodeException)
create a KeyPair object, loading the key pair from encoded (DER format)
KeyPair (const KeyPair &keyPair)
virtual ~KeyPair ()
virtual PublicKey * getPublicKey () throw (AsymmetricKeyException, EncodeException)
gets the public key from key pair
virtual PrivateKey * getPrivateKey () throw (AsymmetricKeyException)
gets the private from key pair
std::string getPemEncoded (SymmetricKey &passphrase, SymmetricCipher::OperationMode mode) throw (SymmetricCipherException, EncodeException)
encode the key pair in PEM format encrypted
std::string getPemEncoded () throw (EncodeException)
encode the key pair in PEM format
ByteArray getDerEncoded () throw (EncodeException)
encode the key pair in DER format
virtual AsymmetricKey::Algorithm getAlgorithm () throw (AsymmetricKeyException)
gets algorithm id from the key
int getSize () throw (AsymmetricKeyException)
gets the key size
int getSizeBits () throw (AsymmetricKeyException)
gets the key size in bits
EVP_PKEY * getEvpPkey () const
ENGINE * getEngine () const
std::string getKeyId () const
Protected Member Functions
KeyPair ()
std::string getPublicKeyPemEncoded () throw (EncodeException)
Static Protected Member Functions
static int passphraseCallBack (char *buf, int size, int rwflag, void *u)
Protected Attributes
EVP_PKEY * key
struct from OpenSSL that represents the key pair
std::string keyId
ENGINE * engine
Detailed Description
Representa um par de chaves assimétricas.
Essa classe deve ser usada para a criação de chaves assimétricas bem como a condificação e decodificação do par para os formatos PEM e DER.
Constructor & Destructor Documentation
KeyPair() [1/7]
KeyPair::KeyPair (AsymmetricKey::Algorithm algorithm, int length) throw (AsymmetricKeyException)
create a KeyPair object, creating a new key pair
Parameters
algorithm key pair algorithm
length key lenght
Exceptions
AsymmetricKeyException if the key cannot be created
References AsymmetricKey::DSA, AsymmetricKey::ECDSA, engine, AsymmetricKeyException::INTERNAL_ERROR, key, and AsymmetricKey::RSA.
KeyPair() [2/7]
KeyPair::KeyPair (Engine * engine, std::string keyId) throw (EngineException)
References engine, EngineException::INIT_FAILED, key, EngineException::KEY_NOT_FOUND, and keyId.
KeyPair() [3/7]
KeyPair::KeyPair (std::string pemEncoded, ByteArray passphrase) throw (EncodeException)
create a KeyPair object, loading the key pair from encoded (PEM format), decrypting with key
Parameters
pemEncoded key pair encoded em PEM format
passphrase passphrase to decrypt the key pair
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_WRITING, engine, key, passphraseCallBack(), and EncodeException::PEM_DECODE.
KeyPair() [4/7]
KeyPair::KeyPair (std::string pemEncoded) throw (EncodeException)
create a KeyPair object, loading the key pair from encoded (PEM format)
Parameters
pemEncoded key pair encoded em PEM format
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_WRITING, engine, key, and EncodeException::PEM_DECODE.
KeyPair() [5/7]
KeyPair::KeyPair (ByteArray derEncoded) throw (EncodeException)
create a KeyPair object, loading the key pair from encoded (DER format)
Parameters
derEncoded key pair encoded em DER format
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_WRITING, EncodeException::DER_DECODE, engine, and key.
KeyPair() [6/7]
KeyPair::KeyPair (const KeyPair & keyPair)
References engine, getEngine(), getEvpPkey(), getKeyId(), key, and keyId.
~KeyPair()
KeyPair::~KeyPair () virtual
References engine, and key.
KeyPair() [7/7]
KeyPair::KeyPair () protected
Member Function Documentation
getAlgorithm()
AsymmetricKey::Algorithm KeyPair::getAlgorithm () throw (AsymmetricKeyException) virtual
gets algorithm id from the key
Returns
algorithm id
Reimplemented in ECDSAKeyPair, DSAKeyPair, and RSAKeyPair.
References AsymmetricKey::DSA, AsymmetricKey::ECDSA, AsymmetricKeyException::INVALID_TYPE, key, AsymmetricKey::RSA, and AsymmetricKeyException::SET_NO_VALUE.
Referenced by getPrivateKey(), and getPublicKey().
getDerEncoded()
ByteArray KeyPair::getDerEncoded () throw (EncodeException)
encode the key pair in DER format
Returns
key pair encoded in DER format
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_READING, EncodeException::DER_ENCODE, and key.
getEngine()
ENGINE * KeyPair::getEngine () const
References engine.
Referenced by KeyPair().
getEvpPkey()
EVP_PKEY * KeyPair::getEvpPkey () const
References key.
Referenced by KeyPair().
getKeyId()
std::string KeyPair::getKeyId () const
References keyId.
Referenced by KeyPair().
getPemEncoded() [1/2]
std::string KeyPair::getPemEncoded (SymmetricKey & passphrase, SymmetricCipher::OperationMode mode) throw (SymmetricCipherException, EncodeException)
encode the key pair in PEM format encrypted
Parameters
passphrase key for encrypt the key pair
mode cipher operation mode
Returns
key pair encrypted encoded in PEM format
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_READING, SymmetricCipher::getCipher(), key, passphraseCallBack(), EncodeException::PEM_ENCODE, and ByteArray::toString().
getPemEncoded() [2/2]
std::string KeyPair::getPemEncoded () throw (EncodeException)
encode the key pair in PEM format
Returns
key pair encoded in PEM format
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_READING, key, EncodeException::PEM_ENCODE, and ByteArray::toString().
getPrivateKey()
PrivateKey * KeyPair::getPrivateKey () throw (AsymmetricKeyException) virtual
gets the private from key pair
Returns
a private key from key pair
Reimplemented in ECDSAKeyPair, DSAKeyPair, and RSAKeyPair.
References AsymmetricKey::DSA, AsymmetricKey::ECDSA, engine, getAlgorithm(), AsymmetricKeyException::INVALID_TYPE, key, keyId, AsymmetricKey::RSA, and AsymmetricKeyException::UNAVAILABLE_KEY.
getPublicKey()
PublicKey * KeyPair::getPublicKey () throw (AsymmetricKeyException, EncodeException) virtual
gets the public key from key pair
Returns
a public key from key pair
Reimplemented in ECDSAKeyPair, DSAKeyPair, and RSAKeyPair.
References AsymmetricKey::DSA, AsymmetricKey::ECDSA, getAlgorithm(), getPublicKeyPemEncoded(), and AsymmetricKey::RSA.
getPublicKeyPemEncoded()
std::string KeyPair::getPublicKeyPemEncoded () throw (EncodeException) protected
References EncodeException::BUFFER_CREATING, EncodeException::BUFFER_READING, key, EncodeException::PEM_ENCODE, and ByteArray::toString().
Referenced by DSAKeyPair::getPublicKey(), RSAKeyPair::getPublicKey(), ECDSAKeyPair::getPublicKey(), and getPublicKey().
getSize()
int KeyPair::getSize () throw (AsymmetricKeyException)
gets the key size
Returns
key size
References AsymmetricKeyException::INTERNAL_ERROR, key, and AsymmetricKeyException::SET_NO_VALUE.
getSizeBits()
int KeyPair::getSizeBits () throw (AsymmetricKeyException)
gets the key size in bits
Returns
key size in bits
References AsymmetricKeyException::INTERNAL_ERROR, key, and AsymmetricKeyException::SET_NO_VALUE.
passphraseCallBack()
int KeyPair::passphraseCallBack (char * buf, int size, int rwflag, void * u) static protected
References ByteArray::getDataPointer(), and ByteArray::size().
Referenced by getPemEncoded(), and KeyPair().
Member Data Documentation
engine
ENGINE* KeyPair::engine protected
Referenced by ECDSAKeyPair::createGroup(), getEngine(), DSAKeyPair::getPrivateKey(), RSAKeyPair::getPrivateKey(), ECDSAKeyPair::getPrivateKey(), getPrivateKey(), KeyPair(), DSAKeyPair::~DSAKeyPair(), ECDSAKeyPair::~ECDSAKeyPair(), ~KeyPair(), and RSAKeyPair::~RSAKeyPair().
key
EVP_PKEY* KeyPair::key protected
struct from OpenSSL that represents the key pair
Referenced by ECDSAKeyPair::createGroup(), ECDSAKeyPair::generateKey(), getAlgorithm(), getDerEncoded(), getEvpPkey(), getPemEncoded(), RSAKeyPair::getPrivateKey(), DSAKeyPair::getPrivateKey(), ECDSAKeyPair::getPrivateKey(), getPrivateKey(), getPublicKeyPemEncoded(), getSize(), getSizeBits(), KeyPair(), DSAKeyPair::~DSAKeyPair(), ECDSAKeyPair::~ECDSAKeyPair(), ~KeyPair(), and RSAKeyPair::~RSAKeyPair().
keyId
std::string KeyPair::keyId protected
Referenced by getKeyId(), DSAKeyPair::getPrivateKey(), RSAKeyPair::getPrivateKey(), ECDSAKeyPair::getPrivateKey(), getPrivateKey(), and KeyPair().
The documentation for this class was generated from the following files:
include/libcryptosec/KeyPair.h
src/KeyPair.cpp