libcryptosec Documentation
CertPathValidatorResult Class Reference
#include <CertPathValidatorResult.h>
Public Types
enum ErrorCode {
UNKNOWN, OK = X509_V_OK, UNABLE_TO_GET_ISSUER_CERT = X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT, UNABLE_TO_GET_CRL = X509_V_ERR_UNABLE_TO_GET_CRL,
UNABLE_TO_DECRYPT_CERT_SIGNATURE = X509_V_ERR_UNABLE_TO_DECRYPT_CERT_SIGNATURE, UNABLE_TO_DECRYPT_CRL_SIGNATURE = X509_V_ERR_UNABLE_TO_DECRYPT_CRL_SIGNATURE, UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY = X509_V_ERR_UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY, CERT_SIGNATURE_FAILURE = X509_V_ERR_CERT_SIGNATURE_FAILURE,
CRL_SIGNATURE_FAILURE = X509_V_ERR_CRL_SIGNATURE_FAILURE, CERT_NOT_YET_VALID = X509_V_ERR_CERT_NOT_YET_VALID, CRL_NOT_YET_VALID = X509_V_ERR_CRL_NOT_YET_VALID, CERT_HAS_EXPIRED = X509_V_ERR_CERT_HAS_EXPIRED,
CRL_HAS_EXPIRED = X509_V_ERR_CRL_HAS_EXPIRED, ERROR_IN_CERT_NOT_BEFORE_FIELD = X509_V_ERR_ERROR_IN_CERT_NOT_BEFORE_FIELD, ERROR_IN_CERT_NOT_AFTER_FIELD = X509_V_ERR_ERROR_IN_CERT_NOT_AFTER_FIELD, ERROR_IN_CRL_LAST_UPDATE_FIELD = X509_V_ERR_ERROR_IN_CRL_LAST_UPDATE_FIELD,
ERROR_IN_CRL_NEXT_UPDATE_FIELD = X509_V_ERR_ERROR_IN_CRL_NEXT_UPDATE_FIELD, OUT_OF_MEM = X509_V_ERR_OUT_OF_MEM, DEPTH_ZERO_SELF_SIGNED_CERT = X509_V_ERR_DEPTH_ZERO_SELF_SIGNED_CERT, SELF_SIGNED_CERT_IN_CHAIN = X509_V_ERR_SELF_SIGNED_CERT_IN_CHAIN,
UNABLE_TO_GET_ISSUER_CERT_LOCALLY = X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY, UNABLE_TO_VERIFY_LEAF_SIGNATURE = X509_V_ERR_UNABLE_TO_VERIFY_LEAF_SIGNATURE, CERT_CHAIN_TOO_LONG = X509_V_ERR_CERT_CHAIN_TOO_LONG, CERT_REVOKED = X509_V_ERR_CERT_REVOKED,
INVALID_CA = X509_V_ERR_INVALID_CA, INVALID_NON_CA =X509_V_ERR_INVALID_NON_CA, PATH_LENGTH_EXCEEDED = X509_V_ERR_PATH_LENGTH_EXCEEDED, PROXY_PATH_LENGTH_EXCEEDED = X509_V_ERR_PROXY_PATH_LENGTH_EXCEEDED,
PROXY_CERTIFICATES_NOT_ALLOWED = X509_V_ERR_PROXY_CERTIFICATES_NOT_ALLOWED, INVALID_PURPOSE = X509_V_ERR_INVALID_PURPOSE, CERT_UNTRUSTED = X509_V_ERR_CERT_UNTRUSTED, CERT_REJECTED = X509_V_ERR_CERT_REJECTED,
APPLICATION_VERIFICATION = X509_V_ERR_APPLICATION_VERIFICATION, SUBJECT_ISSUER_MISMATCH = X509_V_ERR_SUBJECT_ISSUER_MISMATCH, AKID_SKID_MISMATCH = X509_V_ERR_AKID_SKID_MISMATCH, AKID_ISSUER_SERIAL_MISMATCH = X509_V_ERR_AKID_ISSUER_SERIAL_MISMATCH,
KEYUSAGE_NO_CERTSIGN = X509_V_ERR_KEYUSAGE_NO_CERTSIGN, UNABLE_TO_GET_CRL_ISSUER = X509_V_ERR_UNABLE_TO_GET_CRL_ISSUER, UNHANDLED_CRITICAL_EXTENSION = X509_V_ERR_UNHANDLED_CRITICAL_EXTENSION, KEYUSAGE_NO_CRL_SIGN = X509_V_ERR_KEYUSAGE_NO_CRL_SIGN,
KEYUSAGE_NO_DIGITAL_SIGNATURE = X509_V_ERR_KEYUSAGE_NO_DIGITAL_SIGNATURE, UNHANDLED_CRITICAL_CRL_EXTENSION = X509_V_ERR_UNHANDLED_CRITICAL_CRL_EXTENSION, NO_EXPLICIT_POLICY = X509_V_ERR_NO_EXPLICIT_POLICY
}
Possíveis erros de validação de certificado X509.
Public Member Functions
CertPathValidatorResult ()
CertPathValidatorResult (const CertPathValidatorResult &cve)
virtual ~CertPathValidatorResult ()
virtual void setErrorCode (ErrorCode error)
virtual void setDetails (string details)
virtual ErrorCode getErrorType () const
virtual string getDetails () const
virtual string getMessage () const
virtual std::string toString () const
virtual ErrorCode getErrorCode () const
virtual void setInvalidCertificate (Certificate *cert)
virtual Certificate & getInvalidCertificate () const
virtual int getDepth () const
virtual void setDepth (int depth)
virtual void setValidationFlag (ValidationFlags flag)
virtual void setValidationFlag (vector< ValidationFlags > flags=vector< ValidationFlags >())
virtual vector< ValidationFlags > getValidationFlags ()
Static Public Member Functions
static string errorCode2Message (ErrorCode errorCode)
static ErrorCode long2ErrorCode (long n)
Protected Attributes
Certificate * invalidCert
int depth
ErrorCode errorCode
string details
vector< ValidationFlags > validationFlags
Member Enumeration Documentation
ErrorCode
enum CertPathValidatorResult::ErrorCode
Possíveis erros de validação de certificado X509.
Enumerator
UNKNOWN
OK
UNABLE_TO_GET_ISSUER_CERT
UNABLE_TO_GET_CRL
UNABLE_TO_DECRYPT_CERT_SIGNATURE
UNABLE_TO_DECRYPT_CRL_SIGNATURE
UNABLE_TO_DECODE_ISSUER_PUBLIC_KEY
CERT_SIGNATURE_FAILURE
CRL_SIGNATURE_FAILURE
CERT_NOT_YET_VALID
CRL_NOT_YET_VALID
CERT_HAS_EXPIRED
CRL_HAS_EXPIRED
ERROR_IN_CERT_NOT_BEFORE_FIELD
ERROR_IN_CERT_NOT_AFTER_FIELD
ERROR_IN_CRL_LAST_UPDATE_FIELD
ERROR_IN_CRL_NEXT_UPDATE_FIELD
OUT_OF_MEM
DEPTH_ZERO_SELF_SIGNED_CERT
SELF_SIGNED_CERT_IN_CHAIN
UNABLE_TO_GET_ISSUER_CERT_LOCALLY
UNABLE_TO_VERIFY_LEAF_SIGNATURE
CERT_CHAIN_TOO_LONG
CERT_REVOKED
INVALID_CA
INVALID_NON_CA
PATH_LENGTH_EXCEEDED
PROXY_PATH_LENGTH_EXCEEDED
PROXY_CERTIFICATES_NOT_ALLOWED
INVALID_PURPOSE
CERT_UNTRUSTED
CERT_REJECTED
APPLICATION_VERIFICATION
SUBJECT_ISSUER_MISMATCH
AKID_SKID_MISMATCH
AKID_ISSUER_SERIAL_MISMATCH
KEYUSAGE_NO_CERTSIGN
UNABLE_TO_GET_CRL_ISSUER
UNHANDLED_CRITICAL_EXTENSION
KEYUSAGE_NO_CRL_SIGN
KEYUSAGE_NO_DIGITAL_SIGNATURE
UNHANDLED_CRITICAL_CRL_EXTENSION
NO_EXPLICIT_POLICY
Constructor & Destructor Documentation
CertPathValidatorResult() [1/2]
CertPathValidatorResult::CertPathValidatorResult () inline
CertPathValidatorResult() [2/2]
CertPathValidatorResult::CertPathValidatorResult (const CertPathValidatorResult & cve) inline
~CertPathValidatorResult()
virtual CertPathValidatorResult::~CertPathValidatorResult () inline virtual
Member Function Documentation
errorCode2Message()
static string CertPathValidatorResult::errorCode2Message (ErrorCode errorCode) inline static
Referenced by getMessage().
getDepth()
virtual int CertPathValidatorResult::getDepth () const inline virtual
getDetails()
virtual string CertPathValidatorResult::getDetails () const inline virtual
getErrorCode()
virtual ErrorCode CertPathValidatorResult::getErrorCode () const inline virtual
getErrorType()
virtual ErrorCode CertPathValidatorResult::getErrorType () const inline virtual
getInvalidCertificate()
virtual Certificate& CertPathValidatorResult::getInvalidCertificate () const inline virtual
getMessage()
virtual string CertPathValidatorResult::getMessage () const inline virtual
References errorCode2Message().
getValidationFlags()
virtual vector<ValidationFlags> CertPathValidatorResult::getValidationFlags () inline virtual
long2ErrorCode()
static ErrorCode CertPathValidatorResult::long2ErrorCode (long n) inline static
Referenced by Pkcs7SignedData::callback(), and CertPathValidator::callback().
setDepth()
virtual void CertPathValidatorResult::setDepth (int depth) inline virtual
Referenced by Pkcs7SignedData::callback(), and CertPathValidator::callback().
setDetails()
virtual void CertPathValidatorResult::setDetails (string details) inline virtual
setErrorCode()
virtual void CertPathValidatorResult::setErrorCode (ErrorCode error) inline virtual
Referenced by Pkcs7SignedData::callback(), and CertPathValidator::callback().
setInvalidCertificate()
virtual void CertPathValidatorResult::setInvalidCertificate (Certificate * cert) inline virtual
References Certificate::getX509().
Referenced by Pkcs7SignedData::callback(), and CertPathValidator::callback().
setValidationFlag() [1/2]
virtual void CertPathValidatorResult::setValidationFlag (ValidationFlags flag) inline virtual
setValidationFlag() [2/2]
virtual void CertPathValidatorResult::setValidationFlag (vector< ValidationFlags > flags = vector<ValidationFlags>()) inline virtual
toString()
virtual std::string CertPathValidatorResult::toString () const inline virtual
Member Data Documentation
depth
int CertPathValidatorResult::depth protected
details
string CertPathValidatorResult::details protected
errorCode
ErrorCode CertPathValidatorResult::errorCode protected
invalidCert
Certificate* CertPathValidatorResult::invalidCert protected
validationFlags
vector<ValidationFlags> CertPathValidatorResult::validationFlags protected
The documentation for this class was generated from the following file:
include/libcryptosec/certificate/CertPathValidatorResult.h