libcryptosec Documentation
Pkcs7EnvelopedDataBuilder Class Reference
Classes relacionadas ao uso de pacotes PKCS7
Implementa o padrão builder para criação de um pacote PKCS7 envelopado com o uso de criptografia.
#include <Pkcs7EnvelopedDataBuilder.h>
Public Member Functions
Pkcs7EnvelopedDataBuilder (Certificate &cert, SymmetricKey::Algorithm symAlgorithm, SymmetricCipher::OperationMode symOperationMode) throw (Pkcs7Exception, SymmetricCipherException)
Construtor recebendo os parâmetros necessários à envelopagem dos dados a serem adicionados ao pacote.
virtual ~Pkcs7EnvelopedDataBuilder ()
Destrutor padrão.
void init (Certificate &cert, SymmetricKey::Algorithm symAlgorithm, SymmetricCipher::OperationMode symOperationMode) throw (Pkcs7Exception, SymmetricCipherException)
Método responsável pela inicialização do builder.
void addCipher (Certificate &certificate) throw (InvalidStateException, Pkcs7Exception)
Permite a adição de novos certificados cujas chaves privadas correspondentes estarão aptas a abrir o pacote PKCS7.
Pkcs7EnvelopedData * doFinal () throw (InvalidStateException, Pkcs7Exception)
Implementa uma versão distinta do método Pkcs7Builder::doFinal() para gerar o pacote envelopado.
Pkcs7EnvelopedData * doFinal (std::string &data) throw (InvalidStateException, Pkcs7Exception)
Implementa uma versão distinta do método Pkcs7Builder::doFinal() para gerar o pacote envelopado.
Pkcs7EnvelopedData * doFinal (ByteArray &data) throw (InvalidStateException, Pkcs7Exception)
Implementa uma versão distinta do método Pkcs7Builder::doFinal() para gerar o pacote envelopado.
Public Member Functions inherited from Pkcs7Builder
Pkcs7Builder ()
Construtor padrão.
~Pkcs7Builder ()
Destrutor padrão.
void update (std::string &data) throw (InvalidStateException, Pkcs7Exception)
Concatena novos dados ao pacote PKCS7.
void update (ByteArray &data) throw (InvalidStateException, Pkcs7Exception)
Concatena novos dados ao pacote PKCS7.
void doFinal (std::istream *in, std::ostream *out) throw (InvalidStateException, Pkcs7Exception, EncodeException)
Gera um pacote PKCS7 a partir de de um stream de entrada e põe o resultado no formato PEM em um stream de saída.
Additional Inherited Members
Protected Types inherited from Pkcs7Builder
enum State { NO_INIT, INIT, UPDATE }
Possíveis estados do builder.
Protected Attributes inherited from Pkcs7Builder
Pkcs7Builder::State state
Estado atual do builder.
PKCS7 * pkcs7
Estrutura OpenSSL que representa o pacote PKCS7.
BIO * p7bio
Estrutura OpenSSL usada na geração do pacote PKCS7.
Detailed Description
Implementa o padrão builder para criação de um pacote PKCS7 envelopado com o uso de criptografia.
Constructor & Destructor Documentation
Pkcs7EnvelopedDataBuilder()
Pkcs7EnvelopedDataBuilder::Pkcs7EnvelopedDataBuilder (Certificate & cert, SymmetricKey::Algorithm symAlgorithm, SymmetricCipher::OperationMode symOperationMode) throw (Pkcs7Exception, SymmetricCipherException)
Construtor recebendo os parâmetros necessários à envelopagem dos dados a serem adicionados ao pacote.
O método Pkcs7EnvelopedDataBuilder::init() é invocado nesse construtor.
Parameters
cert referência para o certificado que será usado para proteger o conteúdo do PKCS7 e irá compor o pacote.
symAlgorithm o algoritmo simétrico que everá ser usado na envelopagem do pacote.
symOperationMode o modo de operação necessário para alguns cifradores, deve ser SymmetricCipher::NO_MODE para algoritmos que não precisem desse parâmetro.
Exceptions
Pkcs7Exception caso ocorra algum problema na criação do pacote PKCS7.
SymmetricCipherException caso ocorra algum problema na envelopagem do pacote PKCS7.
See also
Pkcs7EnvelopedDataBuilder::init()
References SymmetricCipher::getCipher(), Pkcs7Builder::INIT, Pkcs7Exception::INVALID_CERTIFICATE, and Pkcs7Exception::INVALID_SYMMETRIC_CIPHER.
~Pkcs7EnvelopedDataBuilder()
Pkcs7EnvelopedDataBuilder::~Pkcs7EnvelopedDataBuilder () virtual
Destrutor padrão.
Member Function Documentation
addCipher()
void Pkcs7EnvelopedDataBuilder::addCipher (Certificate & certificate) throw (InvalidStateException, Pkcs7Exception)
Permite a adição de novos certificados cujas chaves privadas correspondentes estarão aptas a abrir o pacote PKCS7.
Parameters
certificate referência para o novo certificado que estará apto a abrir o pacote.
Exceptions
InvalidStateException no caso do builder não ter sido inicializado ainda.
Pkcs7Exception caso tenha ocorrido um erro ao adicionar o certificado ao pacote PKCS7.
References Pkcs7Builder::INIT, Pkcs7Exception::INVALID_CERTIFICATE, Pkcs7Builder::NO_INIT, Pkcs7Builder::pkcs7, and Pkcs7Builder::state.
doFinal() [1/3]
Pkcs7EnvelopedData * Pkcs7EnvelopedDataBuilder::doFinal () throw (InvalidStateException, Pkcs7Exception)
Implementa uma versão distinta do método Pkcs7Builder::doFinal() para gerar o pacote envelopado.
Returns
Pkcs7EnvelopedData o pacote PKCS7 criado.
Exceptions
InvalidStateException caso o builder não esteja no estado apropriado no momento da invocação.
Pkcs7Exception caso tenha ocorrido um erro na geração do pacote PKCS7.
References Pkcs7Exception::INTERNAL_ERROR, Pkcs7Builder::NO_INIT, Pkcs7Builder::p7bio, Pkcs7Builder::pkcs7, Pkcs7Builder::state, and Pkcs7Builder::UPDATE.
Referenced by doFinal().
doFinal() [2/3]
Pkcs7EnvelopedData * Pkcs7EnvelopedDataBuilder::doFinal (std::string & data) throw (InvalidStateException, Pkcs7Exception)
Implementa uma versão distinta do método Pkcs7Builder::doFinal() para gerar o pacote envelopado.
Parameters
data contendo dados a serem concatenados ao conteudo do pacote antes da sua criação definitiva.
Returns
Pkcs7EnvelopedData o pacote PKCS7 criado.
Exceptions
InvalidStateException caso o builder não esteja no estado apropriado no momento da invocação.
Pkcs7Exception caso tenha ocorrido um erro ao adicionar o certificado ao pacote PKCS7.
References doFinal(), and Pkcs7Builder::update().
doFinal() [3/3]
Pkcs7EnvelopedData * Pkcs7EnvelopedDataBuilder::doFinal (ByteArray & data) throw (InvalidStateException, Pkcs7Exception)
Implementa uma versão distinta do método Pkcs7Builder::doFinal() para gerar o pacote envelopado.
Parameters
data contendo dados a serem concatenados ao conteudo do pacote antes da sua criação definitiva.
Returns
Pkcs7EnvelopedData o pacote PKCS7 criado.
Exceptions
InvalidStateException caso o builder não esteja no estado apropriado no momento da invocação.
Pkcs7Exception caso tenha ocorrido um erro ao adicionar o certificado ao pacote PKCS7.
References doFinal(), and Pkcs7Builder::update().
init()
void Pkcs7EnvelopedDataBuilder::init (Certificate & cert, SymmetricKey::Algorithm symAlgorithm, SymmetricCipher::OperationMode symOperationMode) throw (Pkcs7Exception, SymmetricCipherException)
Método responsável pela inicialização do builder.
Após sua invocação, o builder estará pronto para receber os dados a serem empacotados. Pode ser usado também para reinicializar o mesmo com a mudança de um ou mais parâmetros.
Parameters
cert referência para o certificado que será usado para proteger o conteúdo do PKCS7.
symAlgorithm o algoritmo simétrico que everá ser usado na envelopagem do pacote.
symOperationMode o modo de operação necessário para alguns cifradores, deve ser SymmetricCipher::NO_MODE para algoritmos que não precisem desse parâmetro.
Exceptions
Pkcs7Exception caso ocorra algum problema na criação do pacote PKCS7.
SymmetricCipherException caso ocorra algum problema na envelopagem do pacote PKCS7.
See also
Pkcs7EnvelopedDataBuilder::init()
References SymmetricCipher::getCipher(), Pkcs7Builder::INIT, Pkcs7Exception::INVALID_CERTIFICATE, Pkcs7Exception::INVALID_SYMMETRIC_CIPHER, Pkcs7Builder::NO_INIT, Pkcs7Builder::p7bio, Pkcs7Builder::pkcs7, Pkcs7Builder::state, and Pkcs7Builder::UPDATE.
The documentation for this class was generated from the following files:
include/libcryptosec/Pkcs7EnvelopedDataBuilder.h
src/Pkcs7EnvelopedDataBuilder.cpp