libcryptosec Documentation
CertPathValidator Class Reference
Classes Relacionadas Utilitárias de Criptografia
Valida certificados X509.
#include <CertPathValidator.h>
Public Member Functions
CertPathValidator (Certificate &untrusted, vector< Certificate > &untrustedChain, vector< Certificate > &trustedChain, DateTime when=DateTime(time(NULL)), vector< CertificateRevocationList > crls=vector< CertificateRevocationList >(), vector< ValidationFlags > flags=vector< ValidationFlags >())
virtual ~CertPathValidator ()
void setTime (DateTime when)
void setUntrusted (Certificate &cert)
void setUnstrustedChain (vector< Certificate > &certs)
void setTrustedChain (vector< Certificate > &certs)
void setCrls (vector< CertificateRevocationList > &crls)
void setVerificationFlags (ValidationFlags flag)
bool verify ()
bool getWarningsStatus ()
vector< CertPathValidatorResult > getResults ()
Static Public Member Functions
static int callback (int ok, X509_STORE_CTX *ctx)
Protected Attributes
vector< ValidationFlags > flags
DateTime when
Certificate & untrusted
vector< Certificate > & trustedChain
vector< Certificate > & untrustedChain
vector< CertificateRevocationList > crls
Static Protected Attributes
static vector< CertPathValidatorResult > results
Detailed Description
Valida certificados X509.
Constructor & Destructor Documentation
CertPathValidator()
CertPathValidator::CertPathValidator (Certificate & untrusted, vector< Certificate > & untrustedChain, vector< Certificate > & trustedChain, DateTime when = DateTime(time(NULL)), vector< CertificateRevocationList > crls = vector<CertificateRevocationList>(), vector< ValidationFlags > flags = vector<ValidationFlags>()) inline
~CertPathValidator()
virtual CertPathValidator::~CertPathValidator () inline virtual
References callback(), crls, getResults(), getWarningsStatus(), setCrls(), setTime(), setTrustedChain(), setUnstrustedChain(), setUntrusted(), setVerificationFlags(), verify(), and when.
Member Function Documentation
callback()
int CertPathValidator::callback (int ok, X509_STORE_CTX * ctx) static
References CertPathValidatorResult::long2ErrorCode(), results, CertPathValidatorResult::setDepth(), CertPathValidatorResult::setErrorCode(), and CertPathValidatorResult::setInvalidCertificate().
Referenced by verify(), and ~CertPathValidator().
getResults()
vector< CertPathValidatorResult > CertPathValidator::getResults ()
References results.
Referenced by ~CertPathValidator().
getWarningsStatus()
bool CertPathValidator::getWarningsStatus ()
References results.
Referenced by ~CertPathValidator().
setCrls()
void CertPathValidator::setCrls (vector< CertificateRevocationList > & crls)
References crls.
Referenced by ~CertPathValidator().
setTime()
void CertPathValidator::setTime (DateTime when)
References when.
Referenced by ~CertPathValidator().
setTrustedChain()
void CertPathValidator::setTrustedChain (vector< Certificate > & certs)
References trustedChain.
Referenced by ~CertPathValidator().
setUnstrustedChain()
void CertPathValidator::setUnstrustedChain (vector< Certificate > & certs)
References untrustedChain.
Referenced by ~CertPathValidator().
setUntrusted()
void CertPathValidator::setUntrusted (Certificate & cert)
References untrusted.
Referenced by ~CertPathValidator().
setVerificationFlags()
void CertPathValidator::setVerificationFlags (ValidationFlags flag)
References flags.
Referenced by ~CertPathValidator().
verify()
bool CertPathValidator::verify ()
References callback(), CRL_CHECK, CRL_CHECK_ALL, crls, flags, DateTime::getDateTime(), Certificate::getX509(), results, trustedChain, untrusted, untrustedChain, and when.
Referenced by ~CertPathValidator().
Member Data Documentation
crls
vector<CertificateRevocationList> CertPathValidator::crls protected
Referenced by setCrls(), verify(), and ~CertPathValidator().
flags
vector<ValidationFlags> CertPathValidator::flags protected
Referenced by setVerificationFlags(), and verify().
results
vector< CertPathValidatorResult > CertPathValidator::results static protected
Referenced by callback(), getResults(), getWarningsStatus(), and verify().
trustedChain
vector<Certificate>& CertPathValidator::trustedChain protected
Referenced by setTrustedChain(), and verify().
untrusted
Certificate& CertPathValidator::untrusted protected
Referenced by setUntrusted(), and verify().
untrustedChain
vector<Certificate>& CertPathValidator::untrustedChain protected
Referenced by setUnstrustedChain(), and verify().
when
DateTime CertPathValidator::when protected
Referenced by setTime(), verify(), and ~CertPathValidator().
The documentation for this class was generated from the following files:
include/libcryptosec/certificate/CertPathValidator.h
src/certificate/CertPathValidator.cpp