libcryptosec Documentation
GeneralName Class Reference
#include <GeneralName.h>
Public Types
enum Type {
UNDEFINED, OTHER_NAME, RFC_822_NAME, DNS_NAME,
DIRECTORY_NAME, UNIFORM_RESOURCE_IDENTIFIER, IP_ADDRESS, REGISTERED_ID
}
Public Member Functions
GeneralName ()
GeneralName (GENERAL_NAME *generalName)
virtual ~GeneralName ()
std::string getXmlEncoded ()
std::string getXmlEncoded (std::string tab)
void setOtherName (std::string oid, std::string data)
pair< std::string, std::string > getOtherName () const
void setRfc822Name (std::string data)
std::string getRfc822Name () const
void setDnsName (std::string data)
std::string getDnsName () const
void setDirectoryName (RDNSequence &data)
RDNSequence getDirectoryName () const
void setUniformResourceIdentifier (std::string data)
std::string getUniformResourceIdentifier () const
void setIpAddress (std::string data)
std::string getIpAddress () const
void setRegisteredId (ObjectIdentifier objectIdentifier)
ObjectIdentifier getRegisteredId () const
GeneralName::Type getType () const
GENERAL_NAME * getGeneralName ()
GeneralName & operator= (const GeneralName &value)
Static Public Member Functions
static std::string type2Name (GeneralName::Type type)
static std::string data2IpAddress (unsigned char *data)
Protected Member Functions
void clean ()
Static Protected Member Functions
static unsigned char * ipAddress2Data (std::string ipAddress)
Protected Attributes
GeneralName::Type type
std::string data
std::string oid
RDNSequence directoryName
ObjectIdentifier registeredId
Member Enumeration Documentation
Type
enum GeneralName::Type
Enumerator
UNDEFINED
OTHER_NAME
RFC_822_NAME
DNS_NAME
DIRECTORY_NAME
UNIFORM_RESOURCE_IDENTIFIER
IP_ADDRESS
REGISTERED_ID
Constructor & Destructor Documentation
GeneralName() [1/2]
GeneralName::GeneralName ()
References type, and UNDEFINED.
GeneralName() [2/2]
GeneralName::GeneralName (GENERAL_NAME * generalName)
References data, data2IpAddress(), directoryName, oid, registeredId, setDirectoryName(), setDnsName(), setIpAddress(), setOtherName(), setRegisteredId(), setRfc822Name(), setUniformResourceIdentifier(), type, and UNDEFINED.
~GeneralName()
GeneralName::~GeneralName () virtual
Member Function Documentation
clean()
void GeneralName::clean () protected
References data, DIRECTORY_NAME, directoryName, DNS_NAME, IP_ADDRESS, oid, OTHER_NAME, REGISTERED_ID, registeredId, RFC_822_NAME, type, and UNIFORM_RESOURCE_IDENTIFIER.
Referenced by setDirectoryName(), setDnsName(), setIpAddress(), setOtherName(), setRegisteredId(), setRfc822Name(), and setUniformResourceIdentifier().
data2IpAddress()
std::string GeneralName::data2IpAddress (unsigned char * data) static
Referenced by GeneralNames::data2IpAddress(), and GeneralName().
getDirectoryName()
RDNSequence GeneralName::getDirectoryName () const
References directoryName.
getDnsName()
std::string GeneralName::getDnsName () const
References data.
getGeneralName()
GENERAL_NAME * GeneralName::getGeneralName ()
References data, DIRECTORY_NAME, directoryName, DNS_NAME, ObjectIdentifier::getObjectIdentifier(), RDNSequence::getX509Name(), IP_ADDRESS, ipAddress2Data(), oid, OTHER_NAME, REGISTERED_ID, registeredId, RFC_822_NAME, type, UNDEFINED, and UNIFORM_RESOURCE_IDENTIFIER.
Referenced by AccessDescription::getAccessDescription().
getIpAddress()
std::string GeneralName::getIpAddress () const
References data.
getOtherName()
pair< std::string, std::string > GeneralName::getOtherName () const
References data, and oid.
getRegisteredId()
ObjectIdentifier GeneralName::getRegisteredId () const
References registeredId.
getRfc822Name()
std::string GeneralName::getRfc822Name () const
References data.
getType()
GeneralName::Type GeneralName::getType () const
References type.
getUniformResourceIdentifier()
std::string GeneralName::getUniformResourceIdentifier () const
References data.
getXmlEncoded() [1/2]
std::string GeneralName::getXmlEncoded ()
Referenced by AccessDescription::getXmlEncoded().
getXmlEncoded() [2/2]
std::string GeneralName::getXmlEncoded (std::string tab)
References data, DIRECTORY_NAME, directoryName, DNS_NAME, ObjectIdentifier::getName(), RDNSequence::getXmlEncoded(), IP_ADDRESS, oid, OTHER_NAME, REGISTERED_ID, registeredId, RFC_822_NAME, type, type2Name(), and UNIFORM_RESOURCE_IDENTIFIER.
ipAddress2Data()
unsigned char * GeneralName::ipAddress2Data (std::string ipAddress) static protected
References data.
Referenced by getGeneralName().
operator=()
GeneralName & GeneralName::operator= (const GeneralName & value)
References data, DIRECTORY_NAME, directoryName, DNS_NAME, IP_ADDRESS, oid, OTHER_NAME, REGISTERED_ID, registeredId, RFC_822_NAME, type, and UNIFORM_RESOURCE_IDENTIFIER.
setDirectoryName()
void GeneralName::setDirectoryName (RDNSequence & data)
References clean(), DIRECTORY_NAME, directoryName, and type.
Referenced by GeneralName().
setDnsName()
void GeneralName::setDnsName (std::string data)
References clean(), data, DNS_NAME, and type.
Referenced by GeneralName().
setIpAddress()
void GeneralName::setIpAddress (std::string data)
References clean(), data, IP_ADDRESS, and type.
Referenced by GeneralName().
setOtherName()
void GeneralName::setOtherName (std::string oid, std::string data)
References clean(), data, oid, OTHER_NAME, and type.
Referenced by GeneralName().
setRegisteredId()
void GeneralName::setRegisteredId (ObjectIdentifier objectIdentifier)
References clean(), REGISTERED_ID, registeredId, and type.
Referenced by GeneralName().
setRfc822Name()
void GeneralName::setRfc822Name (std::string data)
References clean(), data, RFC_822_NAME, and type.
Referenced by GeneralName().
setUniformResourceIdentifier()
void GeneralName::setUniformResourceIdentifier (std::string data)
References clean(), data, type, and UNIFORM_RESOURCE_IDENTIFIER.
Referenced by GeneralName().
type2Name()
std::string GeneralName::type2Name (GeneralName::Type type) static
References DIRECTORY_NAME, DNS_NAME, IP_ADDRESS, OTHER_NAME, REGISTERED_ID, RFC_822_NAME, and UNIFORM_RESOURCE_IDENTIFIER.
Referenced by getXmlEncoded().
Member Data Documentation
data
std::string GeneralName::data protected
Referenced by clean(), GeneralName(), getDnsName(), getGeneralName(), getIpAddress(), getOtherName(), getRfc822Name(), getUniformResourceIdentifier(), getXmlEncoded(), ipAddress2Data(), operator=(), setDnsName(), setIpAddress(), setOtherName(), setRfc822Name(), and setUniformResourceIdentifier().
directoryName
RDNSequence GeneralName::directoryName protected
Referenced by clean(), GeneralName(), getDirectoryName(), getGeneralName(), getXmlEncoded(), operator=(), and setDirectoryName().
oid
std::string GeneralName::oid protected
Referenced by clean(), GeneralName(), getGeneralName(), getOtherName(), getXmlEncoded(), operator=(), and setOtherName().
registeredId
ObjectIdentifier GeneralName::registeredId protected
Referenced by clean(), GeneralName(), getGeneralName(), getRegisteredId(), getXmlEncoded(), operator=(), and setRegisteredId().
type
GeneralName::Type GeneralName::type protected
Referenced by clean(), GeneralName(), getGeneralName(), getType(), getXmlEncoded(), operator=(), setDirectoryName(), setDnsName(), setIpAddress(), setOtherName(), setRegisteredId(), setRfc822Name(), and setUniformResourceIdentifier().
The documentation for this class was generated from the following files:
include/libcryptosec/certificate/GeneralName.h
src/certificate/GeneralName.cpp