libcryptosec Documentation
ObjectIdentifierFactory Class Reference
#include <ObjectIdentifierFactory.h>
Static Public Member Functions
static ObjectIdentifier getObjectIdentifier (std::string oid) throw (CertificationException)
static ObjectIdentifier getObjectIdentifier (int nid) throw (CertificationException)
static ObjectIdentifier createObjectIdentifier (std::string oid, std::string name) throw (CertificationException)
Member Function Documentation
createObjectIdentifier()
ObjectIdentifier ObjectIdentifierFactory::createObjectIdentifier (std::string oid, std::string name) throw (CertificationException) static
References getObjectIdentifier(), and CertificationException::INTERNAL_ERROR.
getObjectIdentifier() [1/2]
ObjectIdentifier ObjectIdentifierFactory::getObjectIdentifier (std::string oid) throw (CertificationException) static
References CertificationException::UNKNOWN_OID.
Referenced by RDNSequence::addEntry(), AuthorityInformationAccessExtension::AuthorityInformationAccessExtension(), AuthorityKeyIdentifierExtension::AuthorityKeyIdentifierExtension(), BasicConstraintsExtension::BasicConstraintsExtension(), CertificatePoliciesExtension::CertificatePoliciesExtension(), createObjectIdentifier(), CRLDistributionPointsExtension::CRLDistributionPointsExtension(), CRLNumberExtension::CRLNumberExtension(), DeltaCRLIndicatorExtension::DeltaCRLIndicatorExtension(), ExtendedKeyUsageExtension::ExtendedKeyUsageExtension(), Extension::Extension(), IssuerAlternativeNameExtension::IssuerAlternativeNameExtension(), KeyUsageExtension::KeyUsageExtension(), PolicyQualifierInfo::setCpsUri(), PolicyQualifierInfo::setUserNotice(), SubjectAlternativeNameExtension::SubjectAlternativeNameExtension(), SubjectInformationAccessExtension::SubjectInformationAccessExtension(), and SubjectKeyIdentifierExtension::SubjectKeyIdentifierExtension().
getObjectIdentifier() [2/2]
ObjectIdentifier ObjectIdentifierFactory::getObjectIdentifier (int nid) throw (CertificationException) static
References CertificationException::UNKNOWN_OID.
The documentation for this class was generated from the following files:
include/libcryptosec/certificate/ObjectIdentifierFactory.h
src/certificate/ObjectIdentifierFactory.cpp