libcryptosec Documentation
RandomException Class Reference
#include <RandomException.h>
Public Types
enum ErrorCode { UNKNOWN, NO_DATA_SEEDED, NO_IMPLEMENTED_FUNCTION, INTERNAL_ERROR }
Public Member Functions
RandomException (std::string where)
RandomException (RandomException::ErrorCode errorCode, std::string where)
virtual ~RandomException () throw ()
virtual std::string getMessage () const
virtual std::string toString () const
virtual RandomException::ErrorCode getErrorCode ()
Public Member Functions inherited from LibCryptoSecException
virtual ~LibCryptoSecException () throw ()
virtual const char * what () const throw ()
virtual const std::string getDetails () const throw ()
Static Public Member Functions
static std::string errorCode2Message (RandomException::ErrorCode errorCode)
Protected Attributes
RandomException::ErrorCode errorCode
Protected Attributes inherited from LibCryptoSecException
std::string where
std::string details
Member Enumeration Documentation
ErrorCode
enum RandomException::ErrorCode
Enumerator
UNKNOWN
NO_DATA_SEEDED
NO_IMPLEMENTED_FUNCTION
INTERNAL_ERROR
Constructor & Destructor Documentation
RandomException() [1/2]
RandomException::RandomException (std::string where) inline
References errorCode, UNKNOWN, and LibCryptoSecException::where.
RandomException() [2/2]
RandomException::RandomException (RandomException::ErrorCode errorCode, std::string where) inline
References errorCode, and LibCryptoSecException::where.
~RandomException()
virtual RandomException::~RandomException () throw () inline virtual
Member Function Documentation
errorCode2Message()
static std::string RandomException::errorCode2Message (RandomException::ErrorCode errorCode) inline static
References INTERNAL_ERROR, NO_DATA_SEEDED, NO_IMPLEMENTED_FUNCTION, and UNKNOWN.
Referenced by getMessage(), and toString().
getErrorCode()
virtual RandomException::ErrorCode RandomException::getErrorCode () inline virtual
References errorCode.
getMessage()
virtual std::string RandomException::getMessage () const inline virtual
Implements LibCryptoSecException.
References errorCode, and errorCode2Message().
toString()
virtual std::string RandomException::toString () const inline virtual
Implements LibCryptoSecException.
References errorCode, errorCode2Message(), UNKNOWN, and LibCryptoSecException::where.
Member Data Documentation
errorCode
RandomException::ErrorCode RandomException::errorCode protected
Referenced by getErrorCode(), getMessage(), RandomException(), and toString().
The documentation for this class was generated from the following file:
include/libcryptosec/exception/RandomException.h