libcryptosec Documentation
DateTime Class Reference
Classes Relacionadas Utilitárias de Criptografia
Implementa a representação da data.
#include <DateTime.h>
Classes
struct DateVal
Contem dados sobre uma data.
Public Member Functions
DateTime () throw (BigIntegerException)
Construtor padrão.
DateTime (time_t dateTime) throw (BigIntegerException)
Construtor.
DateTime (BigInteger const &dateTime) throw (BigIntegerException)
Construtor.
DateTime (ASN1_TIME *asn1Time) throw (BigIntegerException)
Contrutor.
DateTime (std::string utc) throw (BigIntegerException)
Contrutor.
virtual ~DateTime ()
Destrutor.
std::string getXmlEncoded (std::string tab="") const throw (BigIntegerException)
Obtem representação da data em formato Xml.
void setDateTime (time_t dateTime) throw (BigIntegerException)
Define a data do objeto DateTime.
void setDateTime (BigInteger const &dateTime) throw (BigIntegerException)
Define a data do objeto DateTime.
time_t getDateTime () const throw (BigIntegerException)
Obtem data em segundos.
BigInteger const & getSeconds () const throw ()
Obtem data em segundos.
ASN1_TIME * getAsn1Time () const throw (BigIntegerException)
Obtem data em formato ASN1.
ASN1_TIME * getGeneralizedTime () const throw (BigIntegerException)
Obtem data em formato ASN1.
ASN1_TIME * getUTCTime () const throw (BigIntegerException)
Obtem data em formato ASN1.
std::string getISODate () const throw (BigIntegerException)
Obtem data em formato ISO8601.
DateTime & operator= (const DateTime &value) throw (BigIntegerException)
Operador de atribuição.
void addSeconds (long b) throw (BigIntegerException)
Adiciona segundos.
void addMinutes (long b) throw (BigIntegerException)
Adiciona minutos.
void addHours (long b) throw (BigIntegerException)
Adiciona horas.
void addDays (long b) throw (BigIntegerException)
Adiciona dias.
void addYears (long b) throw (BigIntegerException)
Adiciona anos.
bool operator== (const DateTime &other) const throw ()
bool operator== (time_t other) const throw (BigIntegerException)
bool operator< (const DateTime &other) const throw ()
bool operator< (time_t other) const throw (BigIntegerException)
bool operator> (const DateTime &other) const throw ()
bool operator> (time_t other) const throw (BigIntegerException)
Static Public Member Functions
static DateTime::DateVal getDate (BigInteger const &epoch) throw (BigIntegerException)
Transforma do formato em segundos (epoch) para ano, mês, dia, hora, minuto e segundo.
static BigInteger date2epoch (string aString) throw (BigIntegerException)
Transforma de formato UTCTime(YYMMDDHHMMSSZ) ou GeneralizedTime (YYYYMMDDHHMMSSZ) para epoch(segundos).
static BigInteger date2epoch (int year, int month, int day, int hour, int min, int sec) throw (BigIntegerException)
Transforma do formato ano, mês [0-11], dia [1-31], hora [0-23], minuto [0-59] e segundo 0-59 para epoch.
static int getDayOfWeek (int year, int month, int day) throw ()
static bool isLeapYear (int y) throw ()
Retorna dia da semana de referência (doomsday) para um ano específico.
static int getYearSize (int year)
Retorna quantidade de dias de um ano.
static int getMonthSize (int month, int year)
Retorna quantidade de dias de um ano.
Protected Attributes
BigInteger seconds
Detailed Description
Implementa a representação da data.
É utilizada em certificados, LCRs. Utiliza o formato epoch (time_t) para representar datas internamente.
Constructor & Destructor Documentation
DateTime() [1/5]
DateTime::DateTime () throw (BigIntegerException)
Construtor padrão.
Cria um objeto DateTime com data 0 (00:00:00 UTC, 1 de Janeiro de 1970).
References setDateTime().
DateTime() [2/5]
DateTime::DateTime (time_t dateTime) throw (BigIntegerException)
Construtor.
Cria um objeto DateTime com uma data específica.
Parameters
dateTime data específica em segundos. obs: linux: time_t = __SLONGWORD_TYPE = long int = long.
References setDateTime().
DateTime() [3/5]
DateTime::DateTime (BigInteger const & dateTime) throw (BigIntegerException)
Construtor.
Cria um objeto DateTime com uma data específica.
Parameters
dateTime data específica em segundos.
References setDateTime().
DateTime() [4/5]
DateTime::DateTime (ASN1_TIME * asn1Time) throw (BigIntegerException)
Contrutor.
Cria um objeto DateTime com uma data específica.
Parameters
asn1Time data específica.
References date2epoch(), and setDateTime().
DateTime() [5/5]
DateTime::DateTime (std::string utc) throw (BigIntegerException)
Contrutor.
Cria um objeto DateTime com uma data específica.
Parameters
utc string no formato UTCTime(YYMMDDHHMMSSZ) ou GeneralizedTime (YYYYMMDDHHMMSSZ). Notar que ambos estão no fuso Zulu (GMT+0).
References date2epoch(), and setDateTime().
~DateTime()
DateTime::~DateTime () virtual
Destrutor.
Member Function Documentation
addDays()
void DateTime::addDays (long b) throw (BigIntegerException)
Adiciona dias.
Parameters
quantidade de dias.
References BigInteger::add(), BigInteger::mul(), and seconds.
Referenced by getDate().
addHours()
void DateTime::addHours (long b) throw (BigIntegerException)
Adiciona horas.
Parameters
quantidade de horas.
References BigInteger::add(), BigInteger::mul(), and seconds.
Referenced by getDate().
addMinutes()
void DateTime::addMinutes (long b) throw (BigIntegerException)
Adiciona minutos.
Parameters
quantidade de minutos.
References BigInteger::add(), BigInteger::mul(), and seconds.
Referenced by getDate().
addSeconds()
void DateTime::addSeconds (long b) throw (BigIntegerException)
Adiciona segundos.
Parameters
quantidade de segundos.
References BigInteger::add(), and seconds.
Referenced by getDate().
addYears()
void DateTime::addYears (long b) throw (BigIntegerException)
Adiciona anos.
Parameters
quantidade de anos.
References BigInteger::add(), BigInteger::mul(), and seconds.
Referenced by getDate().
date2epoch() [1/2]
static BigInteger DateTime::date2epoch (string aString) throw (BigIntegerException) inline static
Transforma de formato UTCTime(YYMMDDHHMMSSZ) ou GeneralizedTime (YYYYMMDDHHMMSSZ) para epoch(segundos).
Parameters
aString string no formato 'YYMMDDHHMMSSZ' ou 'YYYYMMDDHHMMSSZ'. return segundos.
References DateTime::DateVal::hour, DateTime::DateVal::min, DateTime::DateVal::sec, and DateTime::DateVal::year.
Referenced by DateTime().
date2epoch() [2/2]
static BigInteger DateTime::date2epoch (int year, int month, int day, int hour, int min, int sec) throw (BigIntegerException) inline static
Transforma do formato ano, mês [0-11], dia [1-31], hora [0-23], minuto [0-59] e segundo 0-59 para epoch.
Returns
segundos.
References BigInteger::add(), getMonthSize(), getYearSize(), DateTime::DateVal::hour, DateTime::DateVal::min, BigInteger::mul(), DateTime::DateVal::sec, and DateTime::DateVal::year.
getAsn1Time()
ASN1_TIME * DateTime::getAsn1Time () const throw (BigIntegerException)
Obtem data em formato ASN1.
Returns
objeto ASN1_TIME no formato UTCTime se ano inferior a 2050, GeneralizedTime caso contrario.
References getGeneralizedTime(), getUTCTime(), and seconds.
Referenced by RevokedCertificate::getX509Revoked(), getXmlEncoded(), CertificateRevocationListBuilder::setNextUpdate(), CertificateBuilder::setNotAfter(), and CertificateBuilder::setNotBefore().
getDate()
static DateTime::DateVal DateTime::getDate (BigInteger const & epoch) throw (BigIntegerException) inline static
Transforma do formato em segundos (epoch) para ano, mês, dia, hora, minuto e segundo.
Parameters
epoch referência para segundos.
Returns
estrutura com ano, mês, dia, hora, minuto e segundo.
References addDays(), addHours(), addMinutes(), addSeconds(), addYears(), DateTime::DateVal::dayOfMonth, DateTime::DateVal::dayOfWeek, DateTime::DateVal::dayOfYear, BigInteger::div(), getDayOfWeek(), getMonthSize(), BigInteger::getValue(), getYearSize(), DateTime::DateVal::hour, DateTime::DateVal::min, BigInteger::mod(), DateTime::DateVal::mon, DateTime::DateVal::sec, BigInteger::sub(), and DateTime::DateVal::year.
Referenced by getGeneralizedTime(), getISODate(), and getUTCTime().
getDateTime()
time_t DateTime::getDateTime () const throw (BigIntegerException)
Obtem data em segundos.
Returns
data em segundos.
References BigInteger::getValue(), and seconds.
Referenced by CertPathValidator::verify().
getDayOfWeek()
static int DateTime::getDayOfWeek (int year, int month, int day) throw () inline static
References DateTime::DateVal::year.
Referenced by getDate().
getGeneralizedTime()
ASN1_TIME * DateTime::getGeneralizedTime () const throw (BigIntegerException)
Obtem data em formato ASN1.
Returns
objeto ASN1_TIME no formato GeneralizedTime (YYYYMMDDHHMMSSZ).
References DateTime::DateVal::dayOfMonth, getDate(), DateTime::DateVal::hour, DateTime::DateVal::min, DateTime::DateVal::mon, DateTime::DateVal::sec, seconds, and DateTime::DateVal::year.
Referenced by getAsn1Time().
getISODate()
std::string DateTime::getISODate () const throw (BigIntegerException)
Obtem data em formato ISO8601.
Returns
string no formato YYYY-MM-DDTHH:MM:SS (no GMT).
References DateTime::DateVal::dayOfMonth, getDate(), DateTime::DateVal::hour, DateTime::DateVal::min, DateTime::DateVal::mon, DateTime::DateVal::sec, seconds, and DateTime::DateVal::year.
getMonthSize()
static int DateTime::getMonthSize (int month, int year) inline static
Retorna quantidade de dias de um ano.
Parameters
month mês [0-11]
year ano desejado.
Returns
número de dias.
References isLeapYear(), operator<(), operator==(), and operator>().
Referenced by date2epoch(), and getDate().
getSeconds()
BigInteger const & DateTime::getSeconds () const throw ()
Obtem data em segundos.
Returns
data em segundos.
References seconds.
Referenced by operator<(), operator==(), and operator>().
getUTCTime()
ASN1_TIME * DateTime::getUTCTime () const throw (BigIntegerException)
Obtem data em formato ASN1.
Returns
objeto ASN1_TIME no formato UTCTime (YYMMDDHHMMSSZ).
References DateTime::DateVal::dayOfMonth, getDate(), DateTime::DateVal::hour, DateTime::DateVal::min, DateTime::DateVal::mon, DateTime::DateVal::sec, seconds, and DateTime::DateVal::year.
Referenced by getAsn1Time(), and CertificateRevocationListBuilder::setLastUpdate().
getXmlEncoded()
std::string DateTime::getXmlEncoded (std::string tab = "") const throw (BigIntegerException)
Obtem representação da data em formato Xml.
Returns
data em formato Xml
References getAsn1Time().
Referenced by RevokedCertificate::getXmlEncoded(), CertificateRevocationList::getXmlEncoded(), and CertificateRevocationListBuilder::getXmlEncoded().
getYearSize()
static int DateTime::getYearSize (int year) inline static
Retorna quantidade de dias de um ano.
Parameters
year ano desejado.
Returns
número de dias.
References isLeapYear().
Referenced by date2epoch(), and getDate().
isLeapYear()
static bool DateTime::isLeapYear (int y) throw () inline static
Retorna dia da semana de referência (doomsday) para um ano específico.
Parameters
year ano.
Returns
dia da semana: 0 para Domingo, 6 para Sábado. Verifica se um ano é bissexto.
Parameters
y ano.
Returns
true se é bissexto, false caso contrário.
Referenced by getMonthSize(), and getYearSize().
operator<() [1/2]
bool DateTime::operator< (const DateTime & other) const throw ()
References getSeconds().
Referenced by getMonthSize().
operator<() [2/2]
bool DateTime::operator< (time_t other) const throw (BigIntegerException)
References getSeconds().
operator=()
DateTime & DateTime::operator= (const DateTime & value) throw (BigIntegerException)
Operador de atribuição.
Parameters
value referência para objeto DateTime.
References setDateTime().
operator==() [1/2]
bool DateTime::operator== (const DateTime & other) const throw ()
References getSeconds().
Referenced by getMonthSize().
operator==() [2/2]
bool DateTime::operator== (time_t other) const throw (BigIntegerException)
References getSeconds().
operator>() [1/2]
bool DateTime::operator> (const DateTime & other) const throw ()
References getSeconds().
Referenced by getMonthSize().
operator>() [2/2]
bool DateTime::operator> (time_t other) const throw (BigIntegerException)
References getSeconds().
setDateTime() [1/2]
void DateTime::setDateTime (time_t dateTime) throw (BigIntegerException)
Define a data do objeto DateTime.
Parameters
dateTime data específica em segundos.
References seconds.
Referenced by DateTime(), and operator=().
setDateTime() [2/2]
void DateTime::setDateTime (BigInteger const & dateTime) throw (BigIntegerException)
Define a data do objeto DateTime.
Parameters
dateTime data específica em segundos.
References seconds.
Member Data Documentation
seconds
BigInteger DateTime::seconds protected
Referenced by addDays(), addHours(), addMinutes(), addSeconds(), addYears(), getAsn1Time(), getDateTime(), getGeneralizedTime(), getISODate(), getSeconds(), getUTCTime(), and setDateTime().
The documentation for this class was generated from the following files:
include/libcryptosec/DateTime.h
src/DateTime.cpp